### ISSUE TITLE
コードレビューについて

### ISSUE THREAD

**Issue by knokmki612** [npocccties/chiloportal#10]
なにかしら変更をおこなった際は、第三者によるコードレビューがおこなわれるとバグの混入の抑制や実装のブラッシュアップが促され品質管理の観点で有用と思う

- フロントエンドの変更でのレビュワー
  - なし、セルフレビュー @knokmki612 
- バックエンドの変更でのレビュワー
  - 基本セルフレビュー
  - 必要に応じて @m-takay
  - oopenapi.jsonとかDDLのSQL文等のドキュメンテーション @knokmki612 
- それ以外（ドキュメンテーション等）のレビュワー
  - 未定（必要に応じて）

~~に誰を指定すればいいか明確化したい~~

**Comment by knokmki612** [comment]
レビュワーなしということであればセルフレビューですすめていく

**Comment by knokmki612** [comment]
> レビュワーなしということであればセルフレビューですすめていく

ミーティングで確認したところひとまず私のフロントエンド開発の範囲ではセルフレビューですすめていく

**Comment by m-takay** [comment]
バックエンドも基本はコード作成者のセルフレビューとし、必要に応じて高柳がレビューしたいと思います。
ドキュメント（openapi.jsonとかDDLのSQL文とか）についてはUI側の要求仕様に合わせる必要があると思いますので、最終的にはフロントエンド側にレビューをお願いしたいです。

**Comment by knokmki612** [comment]
了解です、異存ないです。

逆にフロントエンド開発をすすめていく上で、バックエンド開発と協調するために私からレビューを依頼するとよさそうな内容はありますか？

**Comment by m-takay** [comment]
とくに思いあたることは今のところありません。 @knokmki612

**Comment by knokmki612** [comment]
ありがとうございます、レビュワー指定について明確化できたかと思いますので完了します。

issueをissue一覧に固定表示して参照しやすいようにしておきます。
