### ISSUE TITLE
ポータル機能以外のページの作成

### ISSUE THREAD

**Issue by Hidetaro7** [npocccties/chiloportal#119]
- [x] #126
- [ ] #133
- [x] #130
- [x] #127 
- [x] #129 
- [x] #131 
- [x] #128
- [x] #126

必要とあれば各issueにする。

**Comment by Hidetaro7** [comment]
各issueに分けた。
［静的ページ］があるタイトルのものは、直接.mdファイルに書いてビルド、というのもいい気がする。

**Comment by Hidetaro7** [comment]
関連 #130 #127 #129 #131 #128 #126

**Comment by Hidetaro7** [comment]
こちらミーティングによって 11/15 の完成を目指すことになりました。
Wikiで原稿を書いていくという流れで二人担当で進めましょう。
期限を付けておきます。 @horimasumi

**Comment by ties-makimura** [comment]
https://github.com/npocccties/oku-private/wiki で進める

**Comment by knokmki612** [comment]
実装済み&内容についてはWikiで検討済み　随時反映する
