### ISSUE TITLE
知識バッジの役割を知らない学習者が一定数いる問題

### ISSUE THREAD

**Issue by Hidetaro7** [npocccties/chiloportal#125]
まちがって教育委員会に能力バッジではなく知識バッジを送ってくる学習者が一定数いる。
教育委員会の方は能力バッジという存在に慣れ親しんでいる。

小野さんのアイデア
能力バッジ => 修了バッジ
という呼称に変更する。
バッジであればなんでも修了したと思わせないために、知識バッジではなく能力バッジの呼称を変更するべきではないか？

おおよその意見として
知識バッジという呼称を消すのは抵抗がある。

- [ ] バッジの呼称もしくは存在をどうするか、方針が決まること。
- [ ] コンセプトページに解説すること。

以上で完了。

**Comment by Hidetaro7** [comment]
コンセプトページには図版ももとに2つの関係性をわかりやすくするようにしたらよいと思います。

**Comment by Hidetaro7** [comment]
マイレコのこととかまだ良くわかっていない私ですが、UIデザインも絡めて解決できないでしょうか？
修了証明書のような見た目にバッジが入っていて、
次にこれをどうしたらよいか？がシンプルにデザインされていることは重要かと思います。

ちょっと見た目の案です（仕様的にわかっていない部分もありますが、何か解決策になれば、、）

![image](https://user-images.githubusercontent.com/281424/193486571-e31d18c8-e867-4980-b0bd-265262ec9fef.png)

**Comment by dynamis** [comment]
メール送信ボタンとかのアクションが分かるバッジの表示というのも良いですね。
ポータルの方はバッジのバックパック機能やダウンロード機能を持っていない/持たせる予定はまだないと思うので、Moodle 側の拡張をする必要が生じるものだと思いますけど。

「バッジを DL して送付してください」よりも「バッジの URL を送付してください」とかできるようになると少しマシになったりするのではないかとか、そもそも LMS 感でユーザ認証してバッジの送信・インポートが出来るプラグインなりアプリなりが双方にあるのが本来の姿だろうが、それが出来ないならユーザがバッジを目にする場所で、次のアクションが分かり易いようにするという秀樹さんもいう方針が大事そうですね (通知メールなのか LMS のバッジ一覧画面なのか、そこをどれだけ変えられるのか問題になりますが)。

**Comment by ties-makimura** [comment]
#493 #496 で実現させるのでこちらはクローズ
