### ISSUE TITLE
［静的ページ］コンセプトページ

### ISSUE THREAD

**Issue by Hidetaro7** [npocccties/chiloportal#126]
- [ ] このサイトが持つミッションやポリシーについて、原稿を完成させる（ @horimasumi ）
- [ ] フロントエンドに静的なページが作成される（  ）

以上で完了

なお、この内容に https://github.com/npocccties/chiloportal/issues/125 の問題が伝わりやすい内容が望ましい。

**Comment by horimasumi** [comment]
できたのでクローズする．
