### ISSUE TITLE
CHiLO-Portalのペルソナ

### ISSUE THREAD

**Issue by horimasumi** [npocccties/chiloportal#13]
### 大学

大学は，教師に提供したいオンラインコースのデジタルバッジに，カテゴリ，レベル，対象などの属性毎（タグをつけて？）にポータルに登録する．

### 教師

教師がオンライン研修を始めるきっかけは2つ

1. 自ら抱えている課題の解決や目的を達成するため（主体的）
2. 教育委員会にいわれて（能動的）

本来は1を目指しているが，そのためには，何らかの仕組みが必要．従って当面2になると考えている．

教師の選択方法は，以下が考えられる（要検討）

- 大学が分類したバッジの属性から選ぶ（中央卸売市場から探す，に相当）
- 教育委員会がマップした教員育成指標から選ぶ（小売店から探す，に相当）
- フリーワードで検索する
- 最終課題の種類，ビデオ再生時間など，取得のしやすさから選ぶ
- 代替できる研修数で選ぶ

### 教育委員会

教育委員会は，大学が登録したバッジそれぞれが，自らの教員育成指標のどれに相当するのか指定する
教育委員会は，教師に，オンライン講習を受講し，バッジを獲得することを指示する

<img width="976" alt="image" src="https://user-images.githubusercontent.com/9005132/183550516-d616558a-61ef-4720-9c9c-cce0491c4f46.png">

**Comment by knokmki612** [comment]
チロポータルの利用者をA～Dまで分類し、必要な画面、見た目のタスクの抽出までできている状態と思うのですが、こちらのissueの取り扱いいかがしましょうか

ペルソナの認識が共有できたということで完了できますでしょうか
