### ISSUE TITLE
ひととおりのバックエンドの実装

### ISSUE THREAD

**Issue by yoshinobu-etou-id** [npocccties/chiloportal#132]
実装
-
- [x] https://github.com/npocccties/chiloportal/issues/155
- [x] https://github.com/npocccties/chiloportal/issues/96
- [x] https://github.com/npocccties/chiloportal/issues/97
- [x] https://github.com/npocccties/chiloportal/issues/98
- [x] https://github.com/npocccties/chiloportal/issues/99
- [x] https://github.com/npocccties/chiloportal/issues/100
- [x] https://github.com/npocccties/chiloportal/issues/101
- [x] https://github.com/npocccties/chiloportal/issues/102
- [x] https://github.com/npocccties/chiloportal/issues/103
- [x] https://github.com/npocccties/chiloportal/issues/104
- [x] https://github.com/npocccties/chiloportal/issues/105
- [x] https://github.com/npocccties/chiloportal/issues/106
- [x] https://github.com/npocccties/chiloportal/issues/107
- [x] https://github.com/npocccties/chiloportal/issues/108
- [x] https://github.com/npocccties/chiloportal/issues/123

単体テスト
-
- [x] https://github.com/npocccties/chiloportal/issues/156
- [x] https://github.com/npocccties/chiloportal/issues/134
- [x] https://github.com/npocccties/chiloportal/issues/135
- [x] https://github.com/npocccties/chiloportal/issues/136
- [x] https://github.com/npocccties/chiloportal/issues/137
- [x] https://github.com/npocccties/chiloportal/issues/138
- [x] https://github.com/npocccties/chiloportal/issues/139
- [x] https://github.com/npocccties/chiloportal/issues/140
- [x] https://github.com/npocccties/chiloportal/issues/141
- [x] https://github.com/npocccties/chiloportal/issues/142
- [x] https://github.com/npocccties/chiloportal/issues/143
- [x] https://github.com/npocccties/chiloportal/issues/144
- [x] https://github.com/npocccties/chiloportal/issues/145
- [x] https://github.com/npocccties/chiloportal/issues/146
- [x] https://github.com/npocccties/chiloportal/issues/147

カバレッジ
-
- [x] https://github.com/npocccties/chiloportal/issues/219

課題
-
- [x] https://github.com/npocccties/chiloportal/issues/221
- [x] https://github.com/npocccties/chiloportal/issues/245
- [x] https://github.com/npocccties/chiloportal/issues/248
- [x] https://github.com/npocccties/chiloportal/issues/238
- [x] https://github.com/npocccties/chiloportal/issues/274
- [x] https://github.com/npocccties/chiloportal/issues/295
- [x] https://github.com/npocccties/chiloportal/issues/310
- [x] https://github.com/npocccties/chiloportal/issues/319
- [x] https://github.com/npocccties/chiloportal/issues/454
- [x] https://github.com/npocccties/chiloportal/issues/414
- [x] https://github.com/npocccties/chiloportal/issues/528
- [x] https://github.com/npocccties/chiloportal/issues/500
- [x] https://github.com/npocccties/chiloportal/issues/557
- [x] https://github.com/npocccties/chiloportal/issues/561
- [x] https://github.com/npocccties/chiloportal/issues/562

**Comment by yoshinobu-etou-id** [comment]
フロントで動作確認が済んだ後に、チェックを付けて作業完了を行う

**Comment by knokmki612** [comment]
フロントでの動作確認を実施するために自分をアサインしますね

**Comment by knokmki612** [comment]
動作確認は https://github.com/npocccties/chiloportal/tree/develop/frontend#%E3%83%AD%E3%83%BC%E3%82%AB%E3%83%AB%E7%92%B0%E5%A2%83 に記載のある、モックサーバーを無効化しバックエンドの開発サーバーを使用する手順で実施します

**Comment by knokmki612** [comment]
> 動作確認は https://github.com/npocccties/chiloportal/tree/develop/frontend#%E3%83%AD%E3%83%BC%E3%82%AB%E3%83%AB%E7%92%B0%E5%A2%83 に記載のある、モックサーバーを無効化しバックエンドの開発サーバーを使用する手順で実施します

これだとインポートされた画像が参照できないので、バックエンドの開発サーバーが起動している環境でフロントエンドサーバーを起動させる必要があるように思う

**Comment by knokmki612** [comment]
フロントエンド側で実装したコンポーネント、画面と使用しているAPIの対応関係です。
動作確認できるurlを記載したので、そのurlにアクセスし利用できていることが確認できたものにチェックを入れようと思います

- ヘッダー
  - コンシューマ情報一覧API `/consumer/list`
  - ポータルカテゴリ一覧API `/portalCategory/list`
- 認定している教育委員会一覧のダイアログ
  - バッジを承認しているコンシューマの一覧API `/wisdomBadges/consumer/list`
- ポータルトップ `/` https://dev-portal.oku.cccties.org/
  - コンシューマ情報一覧API `/consumer/list`
  - ポータルカテゴリ一覧API `/portalCategory/list`
  - バッジ情報取得API `/badges`
- カテゴリトップ `/portal_category/[portalCategoryId]` https://dev-portal.oku.cccties.org/portal_categories/1
  - ポータルカテゴリ一覧API `/portalCategory/list`
  - ポータルカテゴリーに属するバッジ一覧取得API `/portalCategory/badges/list`
- 能力バッジ `/wisdom_badges/[wisdomBadgesId]` https://dev-portal.oku.cccties.org/wisdom_badges/1
  - バッジ情報取得API `/badges`
- 検索結果 `/search` https://dev-portal.oku.cccties.org/search?q=%E3%81%BB%E3%81%92
  - キーワードバッジ検索API `/wisdomBadges/list/keyword`
- 育成指標から成長段階を選ぶ `/consumer/[consumerId]` https://dev-portal.oku.cccties.org/consumers/1
  - コンシューマ情報取得API `/consumer`
  - 指定したコンシューマIDの育成指標一覧API `/consumer/framework/list`
  - 育成指標に関連する成長段階一覧API `/consumer/framework/stage/list`
- 成長段階別バッジ一覧 `/consumer/[consumerId]/frameworks/[frameworkId]/stages/[stageId]` https://dev-portal.oku.cccties.org/consumers/1/frameworks/1/stages/1
  - コンシューマ情報取得API `/consumer`
  - 育成指標取得API `/framework`
  - 育成指標に関連する成長段階一覧API `/framework/stage/list`
  - 成長段階に関連する指標項目一覧API `/stage/field/list`
  - バッジ情報取得API `/badges`

**Comment by knokmki612** [comment]
@yoshinobu-etou-id 現状他のAPIのレスポンスで得られており使用していないAPIが3点ありますが、こちらどう取扱いましょうか？（最初から必要十分のAPIが検討されていれば未使用のAPIはででこなかったと思います、すみません & ひととおりAPI用意いただいたおかげでスムーズにフロントエンド実装できました :pray:）

**Comment by yoshinobu-etou-id** [comment]
バックエンドAPIのソースはそのままにしておいて、OpenAPIからは消しておきますか。

**Comment by yoshinobu-etou-id** [comment]
残しておくと、それはそれでメンテが発生しそうで嫌なので、全部消したほうがいいかもしれませんね。

**Comment by yoshinobu-etou-id** [comment]
何かあれば履歴から復活できますし。

**Comment by knokmki612** [comment]
> メンテが発生しそうで嫌

同感です、必要最低限のコードが提供されていた方がメンテナンスしやすいかと個人的には思います

**Comment by yoshinobu-etou-id** [comment]
@knokmki612 
OpenAPI、更新しましたので、チェックサムの変更をお願いいたします。
というか、こちらで更新した方が良いですね。。。
チャレンジしてみます。

**Comment by yoshinobu-etou-id** [comment]
@knokmki612 
何やら消したAPIに引きずられて frontend のビルドでエラーが発生しました。
```
out: ./mocks/handlers.ts:19:28
out: Type error: Property 'field' does not exist on type '{ stage: { list: { get: (option: { query: { framework_id: number; }; config?: FetchConfig | undefined; }) => Promise<AspidaResponse<Stage[], BasicHeaders, 200>>; $get: (option: { ...; }) => Promise<...>; $path: (option?: { ...; } | undefined) => string; }; }; get: (option: { ...; }) => Promise<...>; $get: (option: {...'.
out: 
out:   17 |     res(ctx.json([...Array(10)].map(consumer)))
out:   18 |   ),
out: >**m 19 |   restGet(client.framework.field.list, (_req, res, ctx) =>
out:      |                            ^**m
out:   20 |     res(ctx.json(field()))
out:   21 |   ),
out:   *** |   restGet(client.stage.field.list, (_req, res, ctx) => res(ctx.json(field()))),

```

**Comment by knokmki612** [comment]
> @knokmki612 何やら消したAPIに引きずられて frontend のビルドでエラーが発生しました。
> 
> ```
> out: ./mocks/handlers.ts:19:28
> out: Type error: Property 'field' does not exist on type '{ stage: { list: { get: (option: { query: { framework_id: number; }; config?: FetchConfig | undefined; }) => Promise<AspidaResponse<Stage[], BasicHeaders, 200>>; $get: (option: { ...; }) => Promise<...>; $path: (option?: { ...; } | undefined) => string; }; }; get: (option: { ...; }) => Promise<...>; $get: (option: {...'.
> out: 
> out:   17 |     res(ctx.json([...Array(10)].map(consumer)))
> out:   18 |   ),
> out: >**m 19 |   restGet(client.framework.field.list, (_req, res, ctx) =>
> out:      |                            ^**m
> out:   20 |     res(ctx.json(field()))
> out:   21 |   ),
> out:   *** |   restGet(client.stage.field.list, (_req, res, ctx) => res(ctx.json(field()))),
> ```

対応ありがとうございます :pray:

これはフロントエンドの実装としては未使用のAPIもモックサーバーの振る舞いを定義していることに起因してイルカと思います。

19-21行 を削除すればこの箇所については問題ないかと思います。

**Comment by knokmki612** [comment]
> 消したAPIに引きずられて frontend のビルドでエラーが発生しました

こちら作業します

**Comment by knokmki612** [comment]
https://github.com/npocccties/chiloportal/pull/389 にて作業しました

**Comment by yoshinobu-etou-id** [comment]
もしかして、さっき画像が見れないと騒いでいたのは、ビルドできてなかったからかも。。。

**Comment by knokmki612** [comment]
画像をフロントエンドのアセットディレクトリに追加した後、必ずビルドする必要ありますね

**Comment by knokmki612** [comment]
@yoshinobu-etou-id 現状ひととおりバックエンドの実装ができており、チェックリストについても一通りチェックされている状態なので、完了（close）できそうかと思ったのですがいかがでしょうか
