### ISSUE TITLE
レスポンシブデザイン

### ISSUE THREAD

**Issue by Hidetaro7** [npocccties/chiloportal#149]
小さなタブレットまではサイドカラムが表示できないので、とくに「他の成長段階」についてはボタンを押したときにModalDialog が立ち上がり表が出てくるようにしてみました。

表組みの一部が崩れてしまいましたが、意図としては横幅768pxを超えたら2カラムになるという考えです。

https://www.figma.com/file/dCE06JShf29eqnvZ4vcE8U/OKUTEP?node-id=26%3A83

<img width="1268" alt="image" src="https://user-images.githubusercontent.com/281424/192474079-39c8b9de-2ade-4c1d-9906-bdcf29a758ab.png">

合意が得られたら完了

**Comment by Hidetaro7** [comment]
こちらについてご確認いただけたら幸いです。 @horimasumi 
https://www.figma.com/file/dCE06JShf29eqnvZ4vcE8U?node-id=564:8764#274587125

**Comment by knokmki612** [comment]
関連 https://github.com/npocccties/chiloportal/issues/51

**Comment by horimasumi** [comment]
横幅768px未満なら，モーダルウィンドウが表示されるけど，横幅768px以上なら2カラムになると言うことでしょうか．であればこれでお願いします．その他，ページタイトルについてコメントをつけておきましたので，ご確認ください．

**Comment by Hidetaro7** [comment]
ブレイクポイントごとの方針は固まったのでイシューはクローズします。
