### ISSUE TITLE
ワイヤフレームの合意

### ISSUE THREAD

**Issue by horimasumi** [npocccties/chiloportal#174]
@Hidetaro7 さん
顧客とワイヤフレームについての合意をえるため，以下の仕上げをする．
前提条件：育成指標は大阪市の育成指標を示す．

1．「チロポータル」という文言を「OKUTEP」に変更
　-トップページの「チロポータルからのお知らせ」へのリンク
　-「チロポータルからのお知らせ」ページ

2．トップページの「育成指標から探す」の下のエリアを，以下のカテゴリだけ表示．
・社会主導主事講習（別ウィンドウマーク）
・オープン教育資源（OER)（別ウィンドウマーク）

3．大阪市教員育成指標の「指標項目からバッジを選ぶ」の文言を「バッジを選ぶ」に変更

4．教員育成指標のページのパンくず，タイトルについては，協議中だが，時間がなければ現時点の最新版を提示
https://github.com/npocccties/chiloportal/issues/164

**Comment by Hidetaro7** [comment]
> 2．トップページの「育成指標から探す」の下のエリアを，以下のカテゴリだけ表示．

<img width="739" alt="image" src="https://user-images.githubusercontent.com/281424/193500446-d3f49cd4-3cef-4787-b6c8-8443ae514a78.png">

こうなりますか？ できたら見出しがほしいです。 @horimasumi

**Comment by Hidetaro7** [comment]
> 「バッジを選ぶ」に変更

検討中ですが、良さそうだと思います。

> 教員育成指標のページのパンくず，タイトルについては，協議中だが，時間がなければ現時点の最新版を提示

方針さえ決まればすぐに差し替えは可能ですよ

**Comment by horimasumi** [comment]
>「バッジを選ぶ」に変更

に変更して下さい．

>教員育成指標のページのパンくず，タイトルについては，協議中だが，時間がなければ現時点の最新版を提示

#164 に方針を書きました．よろしくお願いします．

**Comment by ties-makimura** [comment]
> 教材としておすすめのコンテンツ

ここは，おすすめのバッジで，ワイヤーフレームとしては，おすすめのバッジが並ぶイメージにしてほしいです．
コース名が直接並ぶことはありません．

**Comment by Hidetaro7** [comment]
> > 教材としておすすめのコンテンツ
> 
> ここは，おすすめのバッジで，ワイヤーフレームとしては，おすすめのバッジが並ぶイメージにしてほしいです． コース名が直接並ぶことはありません．

私が誤解していたかもしれませんが、バッジが取得できないコースがあるもあるのでそれを知ってほしいという意図からこのセクションができたと思っていました。
バッジが並ぶということであればどのようなコンテンツ、というかセクションなのでしょうか？ @ties-makimura

**Comment by horimasumi** [comment]
「おすすめ」とあるので，おすすめバッジの話と，混乱しているように思います．

あくまでも，

>バッジが取得できないコースがあるもあるのでそれを知ってほしいという意図からこのセクションができたと思っていました。

なので，「育成指標から探す」より下のセクションは

------------------------
## その他のコンテンツ
バッジは取得できませんが，以下のコンテンツも提供しています（ダサい・・・）

### ・社会主導主事講習（別ウィンドウマーク）
### ・オープン教育資源（OER)（別ウィンドウマーク

------------------------
**みたいにして，カテゴリーに飛んでいく感じにして，「教材としてのおすすめのコンテンツ」のセクションは削除してください．

自由記述なので，どうにでもなりますが，今のままだと，顧客に誤解されそうですので・・・・orz

**Comment by ties-makimura** [comment]
> バッジが取得できないコースがあるもあるのでそれを知ってほしいという意図からこのセクションができたと思っていました。

ああ，バッジが取得できない項目なのですね．勘違いしてましたすみません．
@horimasumi さんのいう内容で大丈夫です．

**Comment by Hidetaro7** [comment]
すいません、ちょっと把握しておきたいのですが、「社会主導主事講習」「オープン教育資源（OER）」はカテゴリなんですか？どこにあるのかURLを教えていただけたらと思います。 @horimasumi 

あと、「GIGAスクール構想研修用教材集（教員養成コミュニティ）」以降のコンテンツへのリンクはどうしましょう。
今こんな感じで並べています。

<img width="786" alt="image" src="https://user-images.githubusercontent.com/281424/193737014-1a1993f0-d09b-42eb-a6b4-591ef8f58136.png">

**Comment by horimasumi** [comment]
@Hidetaro7 さん，

>「社会主導主事講習」「オープン教育資源（OER）」はカテゴリなんですか？

https://opedu.lib.osaka-kyoiku.ac.jp/
の下にあります．
今，↑のトップページからサブカテゴリのリンクを張らないようにしていますが，サブカテゴリのリンクを張ると以下のサブカテゴリのページに飛びます．

- 社会主導主事講習」

https://opedu.lib.osaka-kyoiku.ac.jp/course/index.php?categoryid=18

- オープン教育資源（OER）
（現在の名前は，「オープンエデュケーション（試行中）」）
https://opedu.lib.osaka-kyoiku.ac.jp/course/index.php?categoryid=6

> あと、「GIGAスクール構想研修用教材集（教員養成コミュニティ）」以降のコンテンツへのリンクはどうしましょう。

コンテンツのリンクは，不要です．カテゴリのリンクだけにしたいと思っています．

**Comment by Hidetaro7** [comment]
承知しました Figma に反映しておきますね @horimasumi

**Comment by horimasumi** [comment]
資料を作成しました．
https://github.com/npocccties/oku-private/tree/main/docs/デザイン
ご確認下さい．

**Comment by Hidetaro7** [comment]
重要で言語化されたメッセージとして

調達の背景及び目的
https://github.com/npocccties/oku-private/blob/main/docs/%E4%BB%95%E6%A7%98%E6%9B%B8%E3%83%BB%E6%8F%90%E6%A1%88%E6%9B%B8/%E4%BB%95%E6%A7%98%E6%9B%B8.pdf

と
https://github.com/npocccties/oku-private/blob/main/docs/%E3%83%87%E3%82%B6%E3%82%A4%E3%83%B3/%E3%83%96%E3%83%A9%E3%83%B3%E3%83%87%E3%82%A3%E3%83%B3%E3%82%B0%E5%A0%B1%E5%91%8A%E6%9B%B8.pdf
の4.1 のピラミッドの図版

がサイトに記載されている内容という話をいただいた。

**Comment by Hidetaro7** [comment]
変更点1

教育委員会-育成指標トップ

- パンくず
- h1

の表記が変更、教育委員会名がわかりやすく見えること

**Comment by Hidetaro7** [comment]
変更点2

育成指標別バッジ一覧

- パンくず
- h1
- h1の下の成長段階名の表記
  - 詳細な説明は省くことになった
  - その他の成長段階を見るUIは、モバイルのUIと同様にボタンでモーダルされるようになる
- サイドバーの成長段階の表はなくなる

詳しくは Figma 参照

**Comment by Hidetaro7** [comment]
合意が取れたのでクローズする
