### ISSUE TITLE
［静的ページ］トップページ

### ISSUE THREAD

**Issue by Hidetaro7** [npocccties/chiloportal#175]
以前のミーティングにおいて、管理側の手元でデータを持たせて、ビルドさせる静的サイトジェネレータ（SSG）のような仕組みを導入、Jamstackにすることで特集ページなどの編集を行うという話があった。

将来的にはヘッドレスCMSでコンテンツ管理もできるとさらに便利になると思われるが、当初はコマンドライン実行もしくはgithub workflowにて行うという想定で進めたらよいかと思われる。

**Comment by Hidetaro7** [comment]
Next.js の静的サイトジェネレータで生成するフロントエンド側の実装を想定している。

**Comment by knokmki612** [comment]
#47 でも取り扱っているタスクなのですが、なにか別々に取り扱う理由がないのであれば整理したいのですがいかがでしょうか

**Comment by Hidetaro7** [comment]
静的サイトとしての実装のつもりで立てたissueなので整理していいです、おまかせします。 @knokmki612

**Comment by knokmki612** [comment]
トップページ画面の実装については #46 
静的生成に関する実装については #84 
で取り扱うものとして完了
