### ISSUE TITLE
ブランチ戦略について

### ISSUE THREAD

**Issue by knokmki612** [npocccties/chiloportal#18]
各機能の開発にあたって、プルリクエストの作成、そのマージ先の指定などに影響する

- [x] 機能開発（プルリクエストの作成）のベースブランチを何にするのか

等チームで相談し合意を得られれば完了

**Comment by m-takay** [comment]
ブランチの切り方はオーソドックスに
master
develop
feature（必要都度、developからの枝分かれ、名前は適当に）
でよいかなと思いました。
フロントエンドとバックエンドでトップのディレクトリからわかれているので、マージリクエストでのコードレビューは不要と思ってよいでしょうか？（それぞれで更新者が複数人いる場合はその間のレビュー依頼でよいと思われるので）

**Comment by knokmki612** [comment]
> master
> develop
> feature（必要都度、developからの枝分かれ、名前は適当に）
> でよいかなと思いました

この場合

- master: プロダクションデプロイ、バージョンリリースのソースになる。最上位のブランチ
- develop: 開発ブランチ、masterにマージされる
- feature: プルリクエスト（マージリクエスト）になる作業ブランチ、developにマージされる

という理解で合っていますでしょうか。

> フロントエンドとバックエンドでトップのディレクトリからわかれているので、マージリクエストでのコードレビューは不要と思ってよいでしょうか？（それぞれで更新者が複数人いる場合はその間のレビュー依頼でよいと思われるので）

おっしゃるとおりフロントエンドとバックエンドでディレクトリが分かれているので、どのファイルが変更されているかによって https://github.com/npocccties/chiloportal/issues/10 にしたがいレビューを依頼するということになるかと思いました。

例: 私が `frontend/**` 下のファイルを変更するfeatureブランチを作成し、プルリクエスト（マージリクエスト）作成→私のセルフレビューによってマージの判断をおこなう

というので返答になってますでしょうか

**Comment by m-takay** [comment]
その理解で合ってます。レビューについても了解です。
featureブランチはとくに必要でなければ煩雑になるので、同じコードに複数人が修正かける（または先に対応する必要があるバグ修正等が発生したときなどの）必要がなければ、直接、developに対してcommitしてもいいとは思うのですが、そのあたりどう思われますでしょうか？

**Comment by knokmki612** [comment]
> 直接、developに対してcommitしてもいいとは思うのですが、そのあたりどう思われますでしょうか？

考え方次第とは思います。developには必ずレビューを通したコミットが積まれたいということであれば、作業は必ずfeatureブランチに切っておこなうということになるかと思います。
逆にmasterにマージする段階で改めてリリース判定、コードレビュー等おこなうのでdevelopへのコミットは必ずしもレビューを通す必要がないということであれば、developへの直接コミットは許容されると思います。

私としては私の作業はfeatureブランチで作業してプルリクエストにしていくとは思います。
バックエンド開発についてdevelopで直接コミットしていきたいということであればそれはそれですすめ方に競合は生じないと思いますので、異存ないです。

**Comment by knokmki612** [comment]
> 私としては私の作業はfeatureブランチで作業してプルリクエストにしていくとは思います。

背景を補足すると、現状フロントエンド開発のCIに関してはプルリクエスト作成時動作させるように設定していることもあり、新しい変更はプルリクエストを通すようにしています

https://github.com/npocccties/chiloportal/blob/be61bc8196930aebc1f93e6e7d7bda6d1162d2d8/.github/workflows/frontend.yaml#L1-L2

プルリクエスト時でなくdevelopへのプッシュ時などにすれば、developに直接コミットした場合でもCIを動作させることはできます

プルリクエスト単位で作業するのは、他にはissueを完了する際の紐付けに使えるなどGitHubの機能を利用したいという点もあります。

ただあくまで私が作業しやすい（便利&たぶん閲覧者も見やすい？）かなと思ってそうしているだけで、他の人も必ずそうしなければならないとまでは思っていないです。

**Comment by knokmki612** [comment]
現状以下のような方針で合意して開発がすすんでおり、ドキュメンテーションしておいた方がいい気もしますがissueの目標は達成できているので完了します

- master: プロダクションデプロイ、バージョンリリースのソースになる。最上位のブランチ
- develop: 開発ブランチ、masterにマージされる（ここにプッシュしてもよい）
- feature: プルリクエスト（マージリクエスト）になる作業ブランチ、developにマージされる
