### ISSUE TITLE
デザインシステムの開発

### ISSUE THREAD

**Issue by Hidetaro7** [npocccties/chiloportal#194]
ワイヤーフレーム（WF）もほぼできつつあることと、現在の見た目においての検討の一部は WF でも行われているが、
全体的なデザインのルールや基準を定めたデザインシステムが未検討である。

1. プライマリーカラーは何色か？
2. ~トーンアンドマナーで決めるべきことは何なのか~ 見た目のテイストはどうするべきか？
3. デザインガイドラインとして必要な内容はツクロアから提案できる

目的としては、今後運用を続けるにあたって一定の基準がないと、各人が各人のセンスや好みによって表現の一貫性がなくなり、それが閲覧者にとって迷わせることになるのを避ける、などの理由がある。

進め方として、上記の 1. 2. について、TIESさんで思っていることがあれば、~どんなことでもいいのでここのコメントに残していただけますでしょうか~  何かこのあたりについてブランディングミーティングまでに軽くでもいいので何か考えておいていただいてよろしいでしょうか？  @horimasumi @ties-makimura @seishiono 

例：色については従来どおり赤を考えている、その理由としては、、、くらいのレベルでOKです

それと平行して、私は 3. をできることから進めておきます。

**Comment by Hidetaro7** [comment]
たまたまこのタイミングで @seishiono さんより Slack でミーティングの打診があったので、その時に話すことにしたいとおもいます。

**Comment by ties-makimura** [comment]
紙芝居でもいいからWebブラウザで動くものを見てみたい

**Comment by horimasumi** [comment]
>1. プライマリーカラーは何色か？

https://osaka-kyoiku.ac.jp/university/kouhou/logo/　
の基本色がプライマリーカラーかなとは思っています．

>2．トーンアンドマナーで決めるべきことは何なのか？

トーンアンドマナーってなんですか？

**Comment by Hidetaro7** [comment]
> トーンアンドマナーってなんですか？

大教大のトーンであれば、学ぶ人の様々な表情が見る人に伝わるように、写真もしっかり撮られていますが、
今回そのような見せ方に合わせるにしても、使える写真がない、など問題がありそうなので、イラストテイストでWFはつくっています。
トンマナと書きましたが、要はテイストをどういう方向性なのかが決定しないと、見え方がブレてしまいがちなので決めましょう、というお話です。
その意味で「こういう見せ方の方向性を目指している」という方向性がみなさまの頭のなかにあれば、教えてください、少なくともミーティング中に考えると時間的に収まらないと思いますので。

（トーンアンドマナー => 見た目のテイスト に変更しておきます） @horimasumi

**Comment by Hidetaro7** [comment]
> 紙芝居でいいからWebブラウザで動くものを見てみたい

紙芝居だったら Figma でも可能だと思うのですが、どういった意図があるのかお聞かせいただけたらと思います。 @ties-makimura

**Comment by Hidetaro7** [comment]
> [https://osaka-kyoiku.ac.jp/university/kouhou/logo/　](https://osaka-kyoiku.ac.jp/university/kouhou/logo/%E3%80%80)
の基本色がプライマリーカラーかなとは思っています．

大阪教育大学の印象を連想させる、もしくは関連が感じられるような意図が込められているということでしょうか？ （意図の確認です） @horimasumi

**Comment by ties-makimura** [comment]
> 紙芝居でいいからWebブラウザで動くものを見てみたい

Webブラウザでアクセスして表示される画面が見たいです．各画面はイメージ貼り付けなどでよく，ボタンなど中身の機能は動いていない状態で構わないです．
その辺りは， @knokmki612 さんのお仕事かもしれません．誤解があればすみません．

**Comment by Hidetaro7** [comment]
こちらも触れておきたいこと https://github.com/npocccties/chiloportal/issues/173

**Comment by knokmki612** [comment]
> > 紙芝居でいいからWebブラウザで動くものを見てみたい
> 
> Webブラウザでアクセスして表示される画面が見たいです．各画面はイメージ貼り付けなどでよく，ボタンなど中身の機能は動いていない状態で構わないです． その辺りは， @knokmki612 さんのお仕事かもしれません．誤解があればすみません．

この要件の場合、ひでさんがおっしゃるようなFigmaのプロトタイプモードでも満たせるかと思います。作業のアサインは私も着手可能かもしれませんが、ひでさんがメインでFigmaの管理をしていますから、ひでさんが適任という気がします。

**Comment by Hidetaro7** [comment]
10月中を目標に、デザインの基本ルールを文面で起こし、トップページのビジュルデザインと一緒に先方に提出できるようにすることになった。

https://github.com/npocccties/oku-private/issues/44

**Comment by Hidetaro7** [comment]
一旦ドラフトとしてトップページのビジュアルデザインを検討してみました。
https://www.figma.com/file/dCE06JShf29eqnvZ4vcE8U/OKUTEP?node-id=731%3A6806

全体的に、テーマカラーの赤を多めに使っていますが、ちょっとくどい気もしているので、文字の色は基本、黒をつかってもいいかもしれない、という途中段階で一度お見せします。

@horimasumi

**Comment by Hidetaro7** [comment]
「ポータルトップ（黒案）」も横に並べておきました。

**Comment by Hidetaro7** [comment]
@knokmki612 デザインシステムのカラー定義について共有

https://www.figma.com/file/dCE06JShf29eqnvZ4vcE8U/OKUTEP?node-id=731%3A6445

グレースケールについて、今回は少し赤みをもたせた tailwind css の colors.stone を使うつもりです。

**Comment by Hidetaro7** [comment]
@knokmki612 基本デザインシステムは Jumpu UI のデザインシステムを継承してください。
独自のルールについては
https://www.figma.com/file/dCE06JShf29eqnvZ4vcE8U/OKUTEP?node-id=731%3A6445
にある通りです。
検討が必要なコンポーネント等については個別に質問してください。

**Comment by knokmki612** [comment]
> https://www.figma.com/file/dCE06JShf29eqnvZ4vcE8U/OKUTEP?node-id=731%3A6445

上記Figmaにて色づかい、Card等角丸を使用する物についてはrounded-xlを指定すること、その他はJumpu UIに準拠することで合意しました。

これにてデザインシステムが定まったということで完了で差し支えないです。
