### ISSUE TITLE
能力バッジ発行者の画像

### ISSUE THREAD

**Issue by knokmki612** [npocccties/chiloportal#228]
見た目の検討としては能力バッジについては発行者の画像を表示する見た目が検討されています

Figma https://www.figma.com/file/dCE06JShf29eqnvZ4vcE8U/OKUTEP?node-id=249%3A1719

一方で #23 時点のテーブル定義の検討としては発行者(issuer)の画像のパスは保持していない状態

https://github.com/npocccties/chiloportal/blob/419d58c87716e2bbc25dcd4479c2799625bb4b2c/backend/sql/create_table.sql#L22-L25

そもそも #25 を参照する限り発行者の画像はインポートしようがないという認識であっていますでしょうか

この場合、バックエンドのテーブルやAPIのレスポンスを拡張するというよりも、フロント側で別途画像を配置しフロント側アプリケーションから参照するような実装になるのでしょうか

そもそもインポート処理でとれないものならば上記のような実装はしないということも考えられるかと思いました

何らかの方針に明確化したいです

**Comment by dynamis** [comment]
@ties-makimura Moodle側からバッジ発行者のアイコンを取得するようなAPIなり決まったパスなりありますか？あればそれを使うのもあり。

ただ、インポートはあくまでバッジのインポートであってissuerのインポートではないからその段階で処理する必要はあまりないとも思います。

発行者は頻繁には増えないし、増えるときには色々と実装変えたり登録作業は必要そうに思います。そう思うと、発行者の登録は issuer テーブルへの追加をするということだろうから、そこに追加してもらって入れる＆ issuer の情報返すらAPI のレスポンスに含めていただいて使うのがシンプル？

**Comment by dynamis** [comment]
issuerの他の情報はissuerテーブルに手作業入力初期化でしょうから、画像だけフロント側に持つというのは不統一でできれば避けたい。

**Comment by ties-makimura** [comment]
> @ties-makimura Moodle側からバッジ発行者のアイコンを取得するようなAPIなり決まったパスなりありますか？あればそれを使うのもあり。

Moodleのバッジ発行者の設定に，画像の設定項目がそもそもないので，今のMoodleでは無理そう．

> issuerの他の情報はissuerテーブルに手作業入力初期化でしょうから、画像だけフロント側に持つというのは不統一でできれば避けたい。

issuer.url  ( https://opedu.lib.osaka-kyoiku.ac.jp/ とか) + 能力バッジ発行者の画像パス ( issuer/image.png とか) を呼び出すルールにしておいて，
Moodleサーバ管理者に画像を配置してもらう所から始めるのがよさそうですかね．

**Comment by knokmki612** [comment]
コメントありがとうございます、

> issuer.url ( https://opedu.lib.osaka-kyoiku.ac.jp/ とか) + 能力バッジ発行者の画像パス ( issuer/image.png とか) を呼び出すルールにしておいて，
> Moodleサーバ管理者に画像を配置してもらう所から始めるのがよさそうですかね．

この方針で異存ないですが、

> Moodleのバッジ発行者の設定に，画像の設定項目がそもそもないので，今のMoodleでは無理そう．

にあるようにそもそもバッジ発行者の画像が（Moodleとしては）想定されていないということであれば、アプリとしても画像は想定しない、という方針も考えられますがいかがでしょうか？

いずれかの方針に決めていただければこのissueについて完了できそうと思いました。

**Comment by ties-makimura** [comment]
> アプリとしても画像は想定しない、という方針も考えられますがいかがでしょうか？

発行者の画像を表示しないという意味であればNo

Moodleにバッジ発行者の画像はないが，IMSの仕様では，バッジ発行者(Issuer)の情報として image はあるので，あったほうがいい．
https://www.imsglobal.org/sites/default/files/Badges/OBv2p0Final/index.html#Profile

**Comment by knokmki612** [comment]
ありがとうございます、方針が決まりましたので実装のタスクを用意しました。
