### ISSUE TITLE
SQL のテーブル定義を確認する

### ISSUE THREAD

**Issue by dynamis** [npocccties/chiloportal#23]
画面仕様案-テーブル定義等_20220609.drawio.pdf を元にテーブル定義を書いて頂いたが、実際にポータルでの表示に必要なデータを返す API の実装をする上で過不足がないか (特に不足がないか) 確認し、テーブル定義を (一旦) 固めたい。

https://github.com/npocccties/chiloportal/blob/develop/backend/sql/create_table.sql

**Comment by dynamis** [comment]
badge テーブルの定義についてはインポート時の処理 #25 と合わせて考える

**Comment by dynamis** [comment]
全体的に: テーブルの各フィールドの命名規則が [table_name]_xxxx なのか xxxx なのか不統一で規則性がちょっと分からなかったのが気になりました (単に長くなると prefix なしになる？)。外部テーブルのプライマリキー id を参照するときに [table_name]_id なのは分かりますがそれ以外の場合に [自分のテーブル名]_ を付けたり付けなかったりするのが気になります。

## badges テーブルのフィールド
https://github.com/npocccties/chiloportal/blob/93beda24f95033edbb8e038132387babe986aeea/backend/sql/create_table.sql#L3-L15

> id		serial		not null,	-- バッジID
> badge_class	int		not null,	-- BadgeClass ID
> badge_url	varchar(256)	null,		-- URL

"BadgeClass ID" は OB の仕様通り URL であるべきではないかと思ったら、それを badge_url に格納した上で Moodle 上での id を badge_class に int で入れようとしてますか？

BadgeClass は Open Badge のフォーマット定義する型の名称で https://opedu.lib.osaka-kyoiku.ac.jp/pluginfile.php/1/badges/badgeimage/41/f1 のようなのが具体例。その id プロパティが BadgeClass ID といわれるもののハズでフォーマットは int ではなく IRI (URL)。

仕様上の名前とマッチしないと混乱するので id の方に URL を入れた方が良いのですが、SQL テーブル上のシーケンス id と区別を付けやすくしたいから名前を変えるということですよね。badge_url とか badge_iri といったフィールド名にするか、テーブル名と同じ prefix がついたりついてなかったりする不統一あるのを、prefix ナシにするのであれば単に url とか iri とかでしょうか

LMS における ID については例えば badge_json_id や badge_json_index (lms の URL が badge_json.php?id=xxx なので) なり id_in_lms みたいな感じで LMS 側のものであると少しでも伝わり、かつ、OpenBadge 仕様書上の用語定義がされていないワードにするのもありかも。

取りあえず badge_class というのは OB 仕様上の名称なので、違うものを入れるフィールド名には使わないようにしたいです。

> badge_name	varchar(128)	not null,	-- バッジ名称

多分長さが足りない。問答無用でもっと長い名称を付けてしまう残念な人がいるに違いない。

> description	varchar(512)	null,		-- 説明

name は badge_name なのにこちらは description という命名規則の不統一が少し気になる

絶対全然長さが足りない

> image_id	varchar(256)	null,		-- 画像 ID

今回の Moodle が生成する URL に対しては十分だと思われるが、一般に大丈夫なのかは少し確認か。

> image_author	varchar(256)	null,		-- 画像 author
> ob_version	varchar(256)	null,		-- OBバージョン

あっても邪魔にはならないがフロントでは特に使わない気がする。

> issuer_name	varchar(128)	null,		-- 発行者

多分足りる、かな。

> badge_type	char(9)		not null,	-- バッジ種別(wisdom or knowledge)

knowledge より長いのが来たらスキーマ更新するって事ですね。はい。

**Comment by m-takay** [comment]
カラム名にテーブル名は付けない方向で修正します。
BadgeClassIDについては私が勘違いしていましたので修正します。
その他のご指摘も再検討して修正しておきます。

**Comment by m-takay** [comment]
項目の名前と桁数（タイプ）の見直しをしてコミットしました。
URLは、RFCでは最大桁数を定義していないらしいので、URLを格納する項目のタイプはvarchar→text型に変更してます。
description（説明）カラムもtext型に変更しました。

**Comment by dynamis** [comment]
https://github.com/npocccties/chiloportal/blob/99534458aa0dfaad7f6c14e6d37b2dd9234b289f/backend/sql/create_table.sql#L56-L62
https://github.com/npocccties/chiloportal/blob/99534458aa0dfaad7f6c14e6d37b2dd9234b289f/backend/sql/create_table.sql#L63-L69

受講対象 (教員職種) と受講レベル (キャリアステージ) は独自のデータとして name, description フィールドだけがあり、その組み合わせで育成指標の PDF の列を絞り込む (対象で PDF を選び、レベルで列を選ぶ) のだが、実際の教育指標によっては同一 PDF 内で受講対象を細分化している場合がある。

具体的には堺市の場合 https://www.city.sakai.lg.jp/kosodate/kyoiku/torikumi/plan/kyoinikuseishihyo.html は教員用の育成指標 https://www.city.sakai.lg.jp/kosodate/kyoiku/torikumi/plan/kyoinikuseishihyo.files/kyouinikusei.pdf を選んでもなおその中に対象者とステージ毎に異なるラベルの定義がある

![image](https://user-images.githubusercontent.com/188166/187354188-22a8f206-a889-46cc-af55-513a68a7b8bf.png)

- 幼小中支高 の 教諭、指導教諭等...
- 幼保連携型こども園 の 保育教諭、主任保育教諭

この辺りは現状の受講対象 x 受講レベルだけのデータでは表現できない。

受講レベル (ステージ)としては表の列に対応させるとして「充実・発展期」は 3 分割 (合計 5 レベル) して、それぞれに対して「充実・発展期 (幼小中支高では教諭、 幼保連携型こども園では保育教諭)」のような (name または) description に書くことも可能だが、description に書くだけだと検索・絞り込みを全文検索するしかなく、レベル横断で「教諭」向けとして絞り込みたい場合にそれが難しくなる。

従って、「幼小中支高では教諭」といった情報は受講レベルテーブルを拡張して tags (複数設定可能) を付与できるようにする必要がありそう。

**Comment by dynamis** [comment]
複数列 (ステージ/レベル) 横断セルについてのメモ: 

レベルは育成指標テーブルの列 (細分化された列) を指定するが、育成指標表において次のように複数の列を横断するセルがある場合はどうするか

![image](https://user-images.githubusercontent.com/188166/187360620-d41db780-3ab6-474e-b188-2fb13c73e1d7.png)

これは育成指標テーブル上はひとまとめになっているが、バッジとしては実際には特定の列だけに対応付けられるケースがあり得る。従って複数セルでひとまとめと決め打ちすることをしてはならないと思われる。

データとしてはやや冗長になりがちだが、同一のバッジセットを複数のセルに割り当てる対応関係の定義 (カテゴライズドバッジ) をべた書きで書くことになりそう。

この場合育成指標に於いて列横断の結合セルがあることがデータで表現できないが、サイトでは Table 表現する予定はないし、PDF 参照しながら見れば利用者も困らない。また、バッジ集合が共通の横のセルは連結表示するという事もできなくはない。

以上の理由により、育成指標テーブル上で連結セルがあってもそれは全て分割したセルで DB に入れる。

因みに、バッジと「育成指標のセル」の対応関係を定義する中間テーブルの名称として categorized_badge という名称が適当かどうかというと、「カテゴリ」というのはセルを特定するための情報の一つに過ぎないので不適切な名称であると考える。

**Comment by dynamis** [comment]
どうするべきか迷ってるが取りあえず改めて考えて気になった点をコメント:

- 能力バッジと知識バッジは同じバッジテーブルに入れるので構わないのか
  - 別テーブルに分けて知識バッジテーブルの外部キーに能力バッジを入れる形にはせず中間テーブルを使う方が良いのか
  - コース (研修) の外部キーとして知識バッジを設定可能なテーブル構造で構わないのか (コースの中のステップとして知識バッジを沢山取得するが、コースを終えて得るのは常に能力バッジなのでは？)
- カテゴライズドバッジに直接バッジとセルじゃなくてバッジとコンシューマ、カテゴリ、対象、レベルの全外部キーを突っ込むのは、外部キー間の制約事項が一切表現されずに不正なデータ入力を防ぐのが大変になるのでは
  - SQL テーブル設計的に今の状態をどう呼ぶのか知らないが、[こちらの説明でいう](https://tech.tabechoku.com/entry/2020/06/15/132518)「3. 三角関係のリレーションを持つテーブルは(できるだけ)作らない」に違反している状態で、意図的そうするメリットはあるのだろうか
  - バッジを育成指標に於けるどの「セル(何と呼ぶの？カテゴリ行とレベル列の交差する場所のこと)」に設定するかを定義したいのであって、バッジに任意のコンシューマ、カテゴリ、対象、レベルの組み合わせを設定したいわけではない
- コンシューマに対してカテゴリ、対象、レベルが並列の子どもになってるが実際には違うのでは
  - コンシューマの配下に受講対象(職種) があり、その配下にカテゴリとレベルの 2 次元表があるのが実際のデータ構造
  - カテゴリや受講レベルの外部キーは受講対象(職種)であるべきで、その更に親であるコンシューマーの ID を直接入れるべきではないのでは
  - コンシューマと受講対象(職種)が 1:N の親子関係、受講対象(職種)に対してカテゴリ(能力)とレベル(ステージ)が共に 1:N の親子関係であり、カテゴリとレベルは N:N の 2 次元テーブルであるので カテゴリ_レベル 中間テーブル(セル)を追加して、受講対象(職種)とカテゴリ_レベル(セル)を 1:N の親子関係にした方が不正なデータ入力を防げるのでは
  - 親子関係がテーブルで表現されることで、コンシューマと受講対象(職種) を指定してカテゴリとレベルの一覧を取得するといったクエリも書きやすくなるのでは
- カテゴリの中に親子関係のあるカテゴリ1,2,3が直接書かれてる件は #36 参照
  - ツリーである事を表現しないので上記と同様に不正なデータが入るのをコードの実装で防ぐ必要がある
  - とはいえ更新もしない、依存関係も比較的明確、段階も最大 3 段階固定なので面倒だから 1 テーブルに入れてしまえというのはアリという気もする

テーブルはどのように設計してもコードを頑張って書きさえすれば動きますしテーブル数は少ない方が簡単に処理も書けますが、テーブル定義の時点で適切な制約や外部キーの設定をしておかないとバグやデータ不整合を生じやすいと思うので、実際のデータ構造をちゃんと理解した上でもう少しこの辺り検討しては如何かなと。

**Comment by m-takay** [comment]
> カテゴリの中に親子関係のあるカテゴリ1,2,3が直接書かれてる件
こちらは手入力のことを考えると（たとえばExcelでデータ作成してCSV保存→SQLで流し込むみたいな）現状のままでよいかなと思いました。

他については私も同意です。他の方のご意見あれば聞いたうえで修正方針を考えたいと思います。

**Comment by ties-makimura** [comment]
https://github.com/npocccties/chiloportal/issues/40#issuecomment-1233739064 で育成指標の構造名を整理しました．構造名とテーブルの対応は以下になります．

- 教育委員会：コンシューマー
  - 教員育成指標：受講対象
    - 成長段階：受講レベル
    - 指標項目：カテゴリ

> コンシューマと受講対象(職種)が 1:N の親子関係、受講対象(職種)に対してカテゴリ(能力)とレベル(ステージ)が共に 1:N の親子関係であり、カテゴリとレベルは N:N の 2 次元テーブルであるので カテゴリ_レベル 中間テーブル(セル)を追加して、受講対象(職種)とカテゴリ_レベル(セル)を 1:N の親子関係にした方が不正なデータ入力を防げるのでは

仰る通りなので，ここのテーブル関係は修正した方がよさそうです．
テーブル名も，構造名に変更してしまった方が分かりやすいかもです．

**Comment by m-takay** [comment]
テーブル定義を見直してCommitしました。


![Image](https://user-images.githubusercontent.com/110453591/188535580-b901f98d-9082-4016-bae1-071c531d557b.png)

**Comment by ties-makimura** [comment]
@m-takay 
能力バッジと知識バッジのテーブルを分けるのであれば，研修内容テーブル（course）は，知識バッジと親子関係になると思います．
https://github.com/npocccties/chiloportal/issues/25#issuecomment-1225496652

**Comment by m-takay** [comment]
> 研修内容テーブル（course）は，知識バッジと親子関係になると思います．

ご指摘ありがとうございます。
修正しておきます。

**Comment by knokmki612** [comment]
- cell同士の並びを定めたいのでそのための情報が必要
  - target_occupations
  - category
  - target_career_stage
- 成長段階ごとの対象者の属性を付与したい
  - target_career_stage

**Comment by knokmki612** [comment]
> - 成長段階ごとの対象者の属性を付与したい
>   - target_career_stage

subnameフィールドのような自由記述でもいいのではという話があった

**Comment by dynamis** [comment]
久野さんが大体書いてくれてますが次も:

- ポータル独自カテゴリの扱い
  - 能力バッジをポータル独自に分類する「カテゴリ分け」については教育委員会に於ける育成指標カテゴリなどとは別途テーブルを用意して widsdom_badges と紐付ける

初回の実装としては問題無いと思うが少し気になる点:
- issuer を別テーブルにしないか
  - badge を発行するのは LMS であり、LSM は複数の運用主体をサポートしていないため、基本的には LMS の数しか issuer は存在しない
  - 複数 LMS 連携であったり、単一 LMS に複数 issuer を登録運用するような拡張を将来していく可能性はあるが、初年度は基本 issuer は一つになるハズ
  - LMS 運用者 = issuer 組織が単一でも、理論的には badge class 定義時点での issuer 情報が含まれるからバッジに依って issuer のプロパティは違う可能性があるが、基本的には LMS で設定されている組織情報が常に同じ値として全ての能力バッジと知識バッジに含められるだろうと思われる
  - issuer が複数になってきたらそれで絞り込むような需要が出てきて、その時には issuer は別テーブルで id 持たせて置く方が絞り込みが効率的になる。その可能性を最初から考えると別テーブルが良い。その時直せばいいやと思うなら今のままでも良い
  
あまり重要度はないコメント
- テーブル名の単数複数が不統一なのが気になった

**Comment by m-takay** [comment]
上記を踏まえて定義を書き直しcommitしました。英語表記で変えた方がよい（cellとか？）箇所はご指摘/ご提案ください。


![Image](https://user-images.githubusercontent.com/110453591/189257595-f4dcb5b7-16e5-4ecb-b63a-0c1d08bdd979.png)

**Comment by ties-makimura** [comment]
できるだけ，バッジクラスのプロパティに揃えたいです．（＝[IMS の定義](https://www.imsglobal.org/sites/default/files/Badges/OBv2p0Final/index.html#BadgeClass)）
で，親子関係にあるプロパティは  image_id のようにしているので，そのルールに揃えた方がいいと思いました．

上記を踏まえて，以下気づいた所です．他にも抜け落ちあればご指摘いただけるでしょうか．

- knowledge_badge/wisdoam_badgeテーブル： narrative → criteria_narrative
- wisdoam_badgeテーブル：url → alignments_targetUrl 
- knowledge_badge/wisdoam_badgeテーブル：ob_version → version
- courseテーブル：course → criteria

**Comment by m-takay** [comment]
修正しました。

![Image](https://user-images.githubusercontent.com/110453591/189626675-40cb3d02-bb21-4fa9-93c4-6c882e69dc70.png)

**Comment by dynamis** [comment]
大分まとまってきた気がしますが、バッジ周りのデータ構造について少し:

knowledge_badges : criteria = 1:N で定義した (course という誤解を招く名前だったものを criteria に変更された) が、criteria.narrative は次のように順序のあるデータであるからこちらも sort_key が必要かと思います。

例: https://opedu.lib.osaka-kyoiku.ac.jp/badges/badge_json.php?id=46
> "次の必要条件を完了した場合、ユーザにこのバッジが授与されます:\n* 「 すべて 」の次の活動が完了しました:\n\"ビデオ - 1.子ども理解とごまかし勉強\"\n\"レッスン - 2.振り返り\"\n\n"

また、この criteria テーブルにデータを入れてしまえば変換元の上記テキストをそのまま保存しておく理由/使う場面はないので knowledge_badges テーブルの criteria_narrative は削除で良いはず。

同様に wisdom_badges の criteria_narrative についても自動生成された説明文だが、こちらはバッジの alignments のうち `^https://[^/]+/course/` にマッチする targetUrl を持つものが常に入る構造なので、保持する必要はない

例: https://opedu.lib.osaka-kyoiku.ac.jp/badges/badge_json.php?id=146
> "次の必要条件を完了した場合、ユーザにこのバッジが授与されます:\n * 以下のコースを完了する必要があります:\n\"子ども理解の教育心理学\"\n\n"

一方、alignment_targeturl だけではなく alignments_targetname は保持しておいた方が良さそうである (コースにリンクするときにコースの名前が欲しい場合がある)。

**Comment by m-takay** [comment]
> criteria.narrative は次のように順序のあるデータであるからこちらも sort_key が必要かと思います。

プログラムで生成されるためPrimaryKeyがsort_keyの代用になるため省略しました。

> この criteria テーブルにデータを入れてしまえば変換元の上記テキストをそのまま保存しておく理由/使う場面はないので knowledge_badges テーブルの criteria_narrative は削除で良いはず。

変換後のデータがおかしかったときの検証用になるので残しましたが、不要であれば削除します。

> alignments_targetname は保持しておいた方が良さそうである

サンプルのJSON見た感じですと、nameと同じ（頭に"能力バッジ"と付加されてますが）内容でしたのでカットしましたが、同じと限らないのであれば追加が必要ですね。

**Comment by m-takay** [comment]
9/15会議受けてテーブル名修正など実施

![image](https://user-images.githubusercontent.com/110453591/190570947-b51e51a3-9196-4ea2-997f-a9bf2bb2edfc.png)

**Comment by dynamis** [comment]
{wisdom|knowledge}_badges テーブルには現在の LMS が吐き出す情報に限らず [Open Badge の BadgeClass](https://www.imsglobal.org/sites/default/files/Badges/OBv2p0Final/index.html#BadgeClass) に書かれるようなデータは (できる限り) 入れられる形にしたい。

具体的には tags だけが今の DB にないので、tags (Text の配列) を入力できるフィールドを {Wisdom|Knowledge}_badges に追加する。

その上で、以下のような仕様の検索を検索ページやチャットボットで利用する:

キーワード全文検索する対象フィールドリスト:
- wisdom_badges
  - name, description, tags, alignments_targetname
- wisdom_badges
  - name, description, tags, alignments_targetname
- criteria
  - name
- issuer
  - name

検索アルゴリズム:
複数の空白区切りの検索キーワードを OR 検索する。

**Comment by dynamis** [comment]
名称についての議論:

- 現在 category (PDF の列に対応, 3 段階) は competency (compitency は typo) とする
- 現在 competency としているもの (PDF のセルに対応) についての用語定義が必要。

**Comment by knokmki612** [comment]
> competency (compitency は typo) 

すみませんtypoの認識がなくwiki等で混入させてしまってました

**Comment by m-takay** [comment]
用語最終案対応済み


![Image](https://user-images.githubusercontent.com/110453591/191729758-70f43ab4-03b8-4d65-9ef8-cb18ecb4e1f9.png)

**Comment by dynamis** [comment]
多分これで SQL テーブルとしても確定、実装を進めてみて問題があったら再検討というか達になるかと思います。

来週 OpenAPI などの方も更新頂く中で問題が見つかったりしなければクローズしましょう。

**Comment by m-takay** [comment]
OpenAPIの更新でとくに問題は見つからなかったためCloseします。
