### ISSUE TITLE
動作確認時 CORS エラーが生じる

### ISSUE THREAD

**Issue by knokmki612** [npocccties/chiloportal#238]
再現手順

1. フロントエンドサーバーを起動する `cd frontend; docker build -t frontend . ; docker run --rm -p 3000:3000 frontend`
2. `ready - started server on 0.0.0.0:3000, url: http://localhost:3000` というターミナル出力から http://localhost:3000 にブラウザーでアクセスする
3. F12 を押下して開発ツールを開く

結果

以下のようなメッセージがブラウザーのコンソールに流れている

`クロスオリジン要求をブロックしました: 同一生成元ポリシーにより、http://dev-portal.oku.cccties.org/api/v1/badges?badges_type=wisdom&badges_ids=1%2C2%2C3 にあるリモートリソースの読み込みは拒否されます (理由: CORS 要求が成功しなかった)。ステータスコード: (null)`

背景

フロントエンド側でバックエンドサーバーのAPIを叩くケースは、

1. ビルド時のコマンド
2. フロントエンドサーバー（SSRで提供しているページがあるため）
3. ブラウザー

の3ケースがあり、ブラウザーからAPIを叩くケースに対応するため、バックエンドサーバーのCORSの設定が必要と思われる

**Comment by yoshinobu-etou-id** [comment]
@knokmki612 
すみません。httpをhttpsにしてみてAPIを叩いてみてください。

**Comment by yoshinobu-etou-id** [comment]
@knokmki612 
ブラウザから叩くときはSchemasのプルダウンをHTTPSで選択してみてください

**Comment by yoshinobu-etou-id** [comment]
> ブラウザから叩くときはSchemasのプルダウンをHTTPSで選択してみてください
選択するのが手間でしたのでローカル以外はHTTPSのみを選択するようにしました

**Comment by knokmki612** [comment]
> 選択するのが手間でしたのでローカル以外はHTTPSのみを選択するようにしました

Swagger UIから各APIエンドポイントのレスポンスが正常に得られることを確認しました

https://dev-portal.oku.cccties.org/api/v1/swagger/

> すみません。httpをhttpsにしてみてAPIを叩いてみてください。

https://github.com/npocccties/chiloportal/pull/249 の変更をしたのち再現手順で確認したところ、結果変わらずでした。コメント分散してしまいましたがこちらに確認結果をメモしました。
https://github.com/npocccties/chiloportal/pull/242#discussion_r997690743

**Comment by yoshinobu-etou-id** [comment]
@knokmki612 
よくわかってないので質問させてください。
開発サーバーのバックエンドAPIがHTTPのときは特に動作に問題はなかったのでしょうか？

**Comment by knokmki612** [comment]
> 今、開発サーバーのバックエンドAPIを止めているのですが、
> front のコンテナを起動し、localhost:3000 にブラウザでアクセスし、
> Consoleを開いてみましたが、CORSのエラーが発生しますね。

バックエンドサーバーが止まっている現状だと確かに以下の種類のエラーメッセージがブラウザーコンソールに表示されるみたいですね。このエラー自体はネットワークエラーなど他の要因で表示される可能性もあるようです

https://developer.mozilla.org/ja/docs/Web/HTTP/CORS/Errors/CORSDidNotSucceed

issueに書けていなかったのがよくないのですが、バックエンドサーバーが動いている状態では以下のエラーも表示されていたのでこちらの原因を疑っていました

https://developer.mozilla.org/ja/docs/Web/HTTP/CORS/Errors/CORSMissingAllowOrigin

> 開発サーバーのバックエンドAPIがHTTPS化する前（HTTPのとき）は特に動作に問題はなかったのでしょうか？

いいえ、issueの起票時点ではHTTPS化する前でしたがその時点で生じていました。

https://github.com/npocccties/chiloportal/pull/242#issuecomment-1281920182 にて curl をつかって CORS テストされているコメントも拝見していますが、何かしらフロントエンド側の不備があるのでしょうか。だとすればどのような対処が必要か明らかにしたいなと思っています。

**Comment by yoshinobu-etou-id** [comment]
@knokmki612 
とりあえずlocalのfrontからlocalのbackendに繋がるか試してみます。
ちなみにbackendは80のポートになってますが、READMEはまだ更新できていません。

**Comment by yoshinobu-etou-id** [comment]
@knokmki612 
front の Dockerfile について以下のように変更してみました。
```
変更前：ARG NEXT_PUBLIC_API_BASE_URL=https://dev-portal.oku.cccties.org/api/v1/
変更後：ARG NEXT_PUBLIC_API_BASE_URL=localhost/api/v1/
```
すると404エラーが発生しました。URLは以下となっておりました。
`http://localhost:3000/localhost/api/v1/portalCategory/list`

URLのJOINの仕方がおかしいのでは？と思いました。

**Comment by yoshinobu-etou-id** [comment]
@knokmki612 
http://が抜けていたためおかしなパス構成になっていたようです。
`ARG NEXT_PUBLIC_API_BASE_URL=http://localhost/api/v1/`

そのうえでローカルでも下記URLでCORSエラーが再現しました。
http://localhost/api/v1/portalCategory/list

ただ、上記URLをブラウザのConsoleからアクセスすると、正しく表示できましたので、

で、ググってみたら多分以下っぽいです。
https://from-age35.com/1985.html

**Comment by yoshinobu-etou-id** [comment]
> axiosにproxy設定すればいい

ここら辺な気がしました

**Comment by yoshinobu-etou-id** [comment]
もしくは問題の切り分けのため、axiosを使用せずにURL直でAPIを叩いてみるとかでしょうか

**Comment by yoshinobu-etou-id** [comment]
ちなみに postman とか django のテストコードで開発サーバーのAPIを叩くと200のレスポンスが返ってきます

**Comment by knokmki612** [comment]
> もしくは問題の切り分けのため、axiosを使用せずにURL直でAPIを叩いてみるとかでしょうか

まず、フロントエンドではNuxt.jsとAxiosいずれも使用しておりません。

また、共有いただいた `@nuxt/axios` パッケージが提供する[ `proxy` オプション](https://axios.nuxtjs.org/options/#proxy)を使う方法が何をしているかといいますと、Nuxt アプリケーションと同一オリジンにプロキシーサーバーのエンドポイントを生やしてCORSへの対応を不要としています。

もちろん現状のNext.jsでも Next に API エンドポイント用意することはでき、かつおそらくプロキシーさせることも可能でしょうから、同じような対処は可能と思いますが、どちらかというとバックエンドサーバーが公開サーバーである想定ならば同一オリジンでないクライアントからのアクセスも許容されている方が妥当ではないでしょうか。

> ちなみに postman とか django のテストコードで開発サーバーのAPIを叩くと200のレスポンスが返ってきます

私もSwagger UIその他ブラウザからリクエストが送られるケース以外では正常にレスポンスが得られている認識でして、そもそもCORS自体はブラウザからの同一オリジンでないオリジン間のHTTPリクエスト時に考慮する必要のある事項かと思います。

> セキュリティ上の理由から、ブラウザーは、スクリプトによって開始されるオリジン間 HTTP リクエストを制限しています。例えば、 XMLHttpRequestや [Fetch API](https://developer.mozilla.org/ja/docs/Web/API/Fetch_API) は[同一オリジンポリシー](https://developer.mozilla.org/ja/docs/Web/Security/Same-origin_policy) (same-origin policy) に従います。つまり、これらの API を使用するウェブアプリケーションは、そのアプリケーションが読み込まれたのと同じオリジンに対してのみリソースのリクエストを行うことができ、それ以外のオリジンからの場合は正しい CORS ヘッダーを含んでいることが必要です。

引用元: https://developer.mozilla.org/ja/docs/Web/HTTP/CORS

https://github.com/npocccties/chiloportal/pull/242#issuecomment-1281920182 で確認いただいてHTTPステータスが200であったりレスポンスが正常に得られるのはよいと思うのですが、みる必要がありそうなのはCORS対応に必要なレスポンスヘッダーが含まれているかどうかという気がします。
以下はAmazon API Gatewayのドキュメントですが、CORSの確認事項についてドキュメンテーションされているように思ったので共有いたします。
https://docs.aws.amazon.com/ja_jp/apigateway/latest/developerguide/apigateway-test-cors.html

**Comment by yoshinobu-etou-id** [comment]
> まず、フロントエンドではNuxt.jsとAxiosいずれも使用しておりません。
失礼いたしました。何やらどこかで見間違えてしまいました。

とりあえずdjangoでCORSを有効にしないと前に進まないような気がしてきましたので、
CORS設定後にエラーが発生する原因を調べてみます。

**Comment by knokmki612** [comment]
正直CORSは私としてもややこしくて知識に自信ないところなので、なにか私の発言に疑問ありましたら遠慮なく指摘くださいませ… :pray:

> CORS設定後にエラーが発生する原因を調べてみます。

ありがとうございます、お願いいたします

**Comment by yoshinobu-etou-id** [comment]
ローカル環境だと何故かCORSの設定エラーが発生しなかったので、
その環境で試してみたところ、ブラウザのConsoleに出ていたCORSエラーは発生しなくなりましたので、
やはりCORSの有効化は避けては通れないようです。
とりあえず、開発サーバー側でのCORS設定エラーについて引き続き調査いたします。
![スクリーンショット 2022-10-19 114050](https://user-images.githubusercontent.com/111824942/196584885-2b39c826-468b-48e3-aea7-fe9476b45f34.png)

**Comment by yoshinobu-etou-id** [comment]
@knokmki612 
開発サーバーでCORSを有効化してみたので、ブラウザからご確認をお願いいたします。
※江藤の端末の front からはテストデータの表示はできました。

**Comment by knokmki612** [comment]
ありがとうございます :pray: 私の方でも 037d3ce3012b8381bff6f2d779bd8007764dbe2b 時点で再現手順を実施したところCORSエラーがブラウザーのコンソールに流れなくなっていることを確認しました。
