### ISSUE TITLE
Badge 種別をどのように表現するか決める

### ISSUE THREAD

**Issue by dynamis** [npocccties/chiloportal#24]
Moodle の現バージョンでは BadgeClass に対して tags フィールドの値を設定する機能を持っていない。
しかし、本システムでは能力/知識バッジの区別が必要である。[今年の大教大のバッジデータ](https://github.com/npocccties/oku-private/issues/21)では取りあえず「知識バッジ "バッジの名前"」といった prefix で表現しているが、CHiLO Portal ではこのようなデータ表現及び下処理では実装したくない

現状の Moodle では version フィールドに任意テキストが記入出来る ([OB 仕様上も許される](http://www.imsglobal.org/sites/default/files/Badges/OBv2p0Final/index.html#Properties)) し、他に使っていないものなので少々ハックだが name などに書くよりマシだろうという話になっている。

version プロパティを使う場合にどのようなフォーマットにすべきか。

Semantic Versioning https://semver.org/ がより一般的で Node でも使われてるからそれでいい気がした。こちらは Mozilla などのバージョン名ルールと違ってハイフンが入るけど文字付きの方がナシより古いというのは一緒 (将来 "-letters" 外せるようになったら外した方が新しくなって自然)。

> - Identifiers consisting of only digits are compared numerically.
> - Identifiers with letters or hyphens are compared lexically in ASCII sort order.
> - Numeric identifiers always have lower precedence than non-numeric identifiers.
> - A larger set of pre-release fields has a higher precedence than a smaller set, if all of the preceding identifiers are equal.
> - Example: 1.0.0-alpha < 1.0.0-alpha.1 < 1.0.0-alpha.beta < 1.0.0-beta < 1.0.0-beta.2 < 1.0.0-beta.11 < 1.0.0-rc.1 < 1.0.0.

従って、1.0-wisdom, 1.0-knowledge のようなバージョンにする感じだろうか。

ちなみに、バッジ定義の作成日というのがデータとして無さそう (個別のバッジの発行/期限は issuedOn, expires に記載) だがもしそのような情報も持っておきたくなったら 1.0.2022-wisdom などとする事も可能。いずれの場合も 最後の "-letters" 部分で判別することとすれば種別が 1 種類だけで済む実装である限り大丈夫。

参考
- version プロパティ http://www.imsglobal.org/sites/default/files/Badges/OBv2p0Final/index.html#Properties
  > The version property allows issuers to specify a version string or number. It is primarily used to update a BadgeClass without changing the meaning of previously awarded Assertions by duplicating and linking to the previous version.
- バージョン利用例 http://www.imsglobal.org/sites/default/files/Badges/OBv2p0Final/examples/index.html#-badgeclass-versioning

**Comment by yoshinobu-etou-id** [comment]
@dynamis 
上記version フィールドについて教えて頂きたいのですが、下記のversionフィールドを指してますでしょうか？

> {
>   "@context": "https://w3id.org/openbadges/v2",
>   "id": "https://example.org/beths-robotics-badge-v2.json",
>   "name": "Awesomer Robotics Badge",
>   "version": 2,
>   "related": {
>     "id": "https://example.org/beths-robotics-badge.json",
>     "version": 1
>   }
> }

**Comment by knokmki612** [comment]
versionフィールドが今のサンプルデータに含まれていないが今後入力していく想定

**Comment by knokmki612** [comment]
> 上記version フィールドについて教えて頂きたいのですが、下記のversionフィールドを指してますでしょうか？

これについては正しい

**Comment by knokmki612** [comment]
> 従って、1.0-wisdom, 1.0-knowledge のようなバージョンにする感じだろうか。

https://github.com/npocccties/oku-private/issues/35 にて上記の通りハイフンをデリミタとして種別については `wisdom` `knowledge` とすることで合意した

**Comment by dynamis** [comment]
> 下記のversionフィールドを指してますでしょうか？

YES.

Moodle 側でバッジに version を記入したらそこに `1.0-wisdom` `1.0-knowledge`  などの値が入るようになる想定です。
