### ISSUE TITLE
LMS から Badge をインポートするときの下処理について明確化する

### ISSUE THREAD

**Issue by dynamis** [npocccties/chiloportal#25]
LMS (Moodle) から Open Badge のデータを定期(手動？)バッチ処理でインポートして SQL DB に格納する処理をするが、Moodle が管理・生成出来る Badge の制限の都合上で表現されるため、インポート時の下処理が必要。

この下処理内容を明確化・意識合わせしたい。

前提: フロントエンドは Badge のパース処理をしない。バックエンドでパース済みのデータを REST API で受け取ったものだけを利用する。従って、バッジの情報として必要な下処理は基本的にインポート時に行う + 認定をする教育委員会などのデータを追加で保持する形となる。

本 issue ではバッジクラスからのインポート処理を定義する。

**Comment by dynamis** [comment]
現時点でのテーブル定義:

https://github.com/npocccties/chiloportal/blob/93beda24f95033edbb8e038132387babe986aeea/backend/sql/create_table.sql#L3-L15

https://github.com/npocccties/chiloportal/blob/93beda24f95033edbb8e038132387babe986aeea/backend/sql/create_table.sql#L17-L22

https://github.com/npocccties/chiloportal/blob/93beda24f95033edbb8e038132387babe986aeea/backend/sql/create_table.sql#L65-L74

今年のポータルでのバッジデータの例 (see also https://github.com/npocccties/oku-private/issues/21) :

能力バッジ
https://opedu.lib.osaka-kyoiku.ac.jp/badges/badge_json.php?id=41
https://opedu.lib.osaka-kyoiku.ac.jp/badges/badge_json.php?id=139
https://opedu.lib.osaka-kyoiku.ac.jp/badges/badge_json.php?id=145

知識バッジ
https://opedu.lib.osaka-kyoiku.ac.jp/badges/badge_json.php?id=36
https://opedu.lib.osaka-kyoiku.ac.jp/badges/badge_json.php?id=72

**Comment by dynamis** [comment]
## badge_type を version プロパティから取得

まず能力バッジと知識バッジの識別は現在のバッジ例のような name の中に入れることはせず version などで表現するという議論 (#24) になっており、そちらをパースして badge_type とすれば良い。

## description

自由入力フィールドだが、特にした処理が必要な特殊な使い方はされていないように見える。要確認。

## criteria.narrative は下処理した上でインポート

narrative は Moodle で設定した取得条件を表現するテキストが自動生成されている。

criteria.narrative の例:
> "次の必要条件を完了した場合、ユーザにこのバッジが授与されます:\n* 「 すべて 」の次の活動が完了しました:\n\"ビデオ - 1.はじめに\"\n\"ビデオ - 2.日本の教育課題を知る\"\n\"ビデオ - 3.教師の働き方を省察する\"\n\"ビデオ - 4.まとめ\"\n\"レッスン - 5.振り返り\"\n\n"

このまま SQL に入れるとフロントエンドでの表現に制約が生じるため、下処理してインポートしたい。これは Moodle 側の設定にもよるところがあるのではないかと思うので、出力されるテキストのフォーマット定義を @ties-makimura さんに決めて貰いたい (説明して貰いたい)

## BadgeClass 全体

badges テーブルに念のためインポート元の BadgeClass 全体を json で突っ込んでおくということも可能な気がするが、するかしないか。しておけば将来的にプロパティが増えても取りあえず全文検索マッチさせるといった荒技が出来たり、テーブルおかしいなというときのデバッグには役立つかも知れないが、当然データ容量は倍以上になる。

**Comment by dynamis** [comment]
その他、現在のサンプルバッジのデータにあるが現在の SQL テーブルにないものについて

# issuer.*
issuer_name だけ varchar(128) として定義されているがそれだけでは足りないのではないだろうか。

- issuer.name - varchar(128) では長さが足りない気がする。
- issuer.url - URL を記録しておかないとポータルから発行元大学のサイトにリンク出来ない
- issuer.email - 記録しておかないと問い合わせが出来ないのだが、現状のサンプルは空文字列が使われているし、実際にポータルに記載する事は今のところ無さそうなので不要か。
- issuer.id - これはまぁ要らないだろうという気がする

issuer = 教育機関

# alignments

バッジを発行するコースや、能力バッジから依存する知識バッジのリスト。
前述のように OB 2.0 仕様としては criteria.narrative に記載した外部リンク先もリストに入れることがあるようだが、現状の Moodle ではそのような賢い機能は無いはず > @ties-makimura 違ったツッコミください。

コースと知識バッジしか入り得ないのであれば、targetUrl のパターンマッチで振り分けて training テーブルや badge_relation を生成する。Moodle 上の機能名としてコースとしょっちゅう読んでるけどここでの用語としては「研修 = training」としてよいのかしら。

https://github.com/npocccties/chiloportal/blob/93beda24f95033edbb8e038132387babe986aeea/backend/sql/create_table.sql#L24-L30

**Comment by dynamis** [comment]
現在インポートするテーブルの定義をしているがそれで大丈夫か気になるところ

## badges テーブルのフィールド
https://github.com/npocccties/chiloportal/blob/93beda24f95033edbb8e038132387babe986aeea/backend/sql/create_table.sql#L3-L15

> id		serial		not null,	-- バッジID
> badge_class	int		not null,	-- BadgeClass ID
> badge_url	varchar(256)	null,		-- URL

"BadgeClass ID" は OB の仕様通り URL であるべきではないかと思ったら、それを badge_url に格納した上で Moodle 上での id を badge_class に int で入れようとしてますか？

BadgeClass は Open Badge のフォーマット定義する型の名称で https://opedu.lib.osaka-kyoiku.ac.jp/pluginfile.php/1/badges/badgeimage/41/f1 のようなのが具体例。その id プロパティが BadgeClass ID といわれるもののハズでフォーマットは int ではなく IRI (URL)。

仕様上の名前とマッチしないと混乱するので id の方に URL を入れた方が良いのですが、SQL テーブル上のシーケンス id と区別を付けやすくしたいから名前を変えるということですよね。url_id とか iri_id とかでしょうかね？

badges というテーブル全体が BadgeClass を入れるものなので badge_class というフィールド名 or prefix は違和感があります。テーブル名自体 badge_classes とかにしておいても良いくらい(個々人に発行する badge を管理する未来がない限り冗長)。

LMS における ID については例えば badge_json_id (lms の URL が badge_json.php?id=xxx なので) なり id_in_lms みたいな感じで LMS 側のものであると少しでも伝わり、かつ、OpenBadge 仕様書上の用語定義がされていないワードにした方が良いかも。

> badge_name	varchar(128)	not null,	-- バッジ名称

多分長さが足りない。問答無用でもっと長い名称を付けてしまう残念な人がいるに違いない。

> description	varchar(512)	null,		-- 説明

name は badge_name なのにこちらは description という命名規則の不統一が少し気になる

絶対全然長さが足りない

> image_id	varchar(256)	null,		-- 画像 ID

今回の Moodle が生成する URL に対しては十分だと思われるが、一般に大丈夫なのかは少し確認か。

> image_author	varchar(256)	null,		-- 画像 author
> ob_version	varchar(256)	null,		-- OBバージョン

あっても邪魔にはならないがフロントでは特に使わない気がする。

> issuer_name	varchar(128)	null,		-- 発行者

多分足りる、かな。

> badge_type	char(9)		not null,	-- バッジ種別(wisdom or knowledge)

knowledge より長いのが来たらスキーマ更新するって事ですね。はい。

**Comment by m-takay** [comment]
> Moodle 上の機能名としてコースとしょっちゅう読んでるけどここでの用語としては「研修 = training」としてよいのかしら。

受講対象/受講レベルの方で「受講＝course」としたので、研修はtrainingにしましたが代案ありましたら変更いたします。

**Comment by ties-makimura** [comment]
> criteria.narrative は下処理した上でインポート

について整理してみました．

## criteria.narrative のフォーマット

- 前提
  - criteria.narrative の情報がインポートされる対象は，知識バッジのみ．
  - Moodleで発行する知識バッジのクライテリア条件は，「対象の活動完了をすべて満たす」という条件のみ．
- 出力されるテキスト
  - 知識バッジで発行される criteria.narrative のテキストは2パターンあるが，どちらのパターンでも必要な箇所は \n\"○○○ - ×××\"\n\n" の範囲にある「○○○ - ×××」のn個分となる
    - パターン1：活動完了が1つ
      > "narrative": "次の必要条件を完了した場合、ユーザにこのバッジが授与されます:\n * 　\n"ビデオ - プロットの分析"\n\n"
    - パターン2：活動完了が2つ以上
      > "narrative": "次の必要条件を完了した場合、ユーザにこのバッジが授与されます:\n* 「 すべて 」の次の活動が完了しました:\n"ビデオ - 1.はじめに"\n"ビデオ - 2.日本の教育課題を知る"\n"ビデオ - 3.教師の働き方を省察する"\n"ビデオ - 4.まとめ"\n"レッスン - 5.振り返り"\n\n"
- 懸念
  - ○○○ 側のテキストは，取得側の言語地域で，日本語や英語などそれぞれの言語に変化する．インポートを行うポータルサーバーからのデータ取得時にどうなるか分からないので心配
    - 例：対象の活動が"小テスト"の場合
      - 日本語：「小テスト」となる
         > "narrative": "この条件でバッジ授与\n * 以下の活動を完了する必要があります:\n\"小テスト - 確認テスト\"\n\n"
      - 英語：「Quiz」となる
         > "narrative": "Users are awarded this badge when they complete the following requirement:\n * The following activity has to be completed:\n\"Quiz - 確認テスト\"\n\n"
  - ○○○ 側のテキストは，言語カスタマイゼーションの設定で，同じ言語地域でも変わる場合がある．
    - 例：対象の活動が"小テスト"の場合
       - 言語カスタマイゼーション変更していない：「小テスト」となる
         > "narrative": "この条件でバッジ授与\n * 以下の活動を完了する必要があります:\n\"小テスト - 確認テスト\"\n\n"
       - 言語カスタマイゼーションで小テストをクイズに変更した場合：「クイズ」となる
         > "narrative": "この条件でバッジ授与\n * 以下の活動を完了する必要があります:\n\"クイズ - 確認テスト\"\n\n"

## 最終的に表示するアイコンの種類

- criteria.narrative から取得した ○○○ の情報を元に，フロントで表示するアイコンを用意する．将来的に増える可能性はある．
  現時点で想定している，アイコンのパターンと該当する criteria.narrative のテキストは以下の通り．
  - ビデオアイコン：ビデオ
  - クイズアイコン：小テスト
  - アンケートアイコン：アンケート，レッスン
- 懸念
  - criteria.narrative のテキスト出力時点では，同じアイコンパターン想定でも異なるテキスト（小テスト，クイズ，Quiz， ...etc）の可能性がある．その場合，どのタイミングでアイコン判定するか決める必要があるかと思う（インポート時点？フロント表示時点？）

**Comment by dynamis** [comment]
> > Moodle 上の機能名としてコースとしょっちゅう読んでるけどここでの用語としては「研修 = training」としてよいのかしら。
> 
> 受講対象/受講レベルの方で「受講＝course」としたので、研修はtrainingにしましたが代案ありましたら変更いたします。

受講対象/受講レベルにおいて「受講」というデータモデルはないのではないか。あくまでもバッジに対してコンシューマーがカテゴリ・受講対象・受講レベルというプロパティを付与しているだけであり、受講対象と受講レベルに親子とか何らかの関係性があるような命名規則 course/course_level のようなものは違和感がある。

データの内容を明確にしておくと:
- コンシューマ: 教育委員会など
- カテゴリ: 大阪市の例で言えば「基本的資質」 -「法令遵守」 -「使命・法令」のようなものが 3 段階のカテゴリ
- 受講対象: 大阪市の例でいえば「管理職」「教員」「幼稚園教員」「養護教諭」など
- 受講レベル: 大阪市の例でいえば 初任教員、若手教員、中堅教員など

参考:
- 大阪市育成指標 http://swa.city-osaka.ed.jp/swas/index.php?id=ocec&frame=sihyou
- 堺市育成指標 https://www.city.sakai.lg.jp/kosodate/kyoiku/torikumi/plan/kyoinikuseishihyo.html

なので、受講対象や受講レベルにはやはり course というラベルは合わない気がします。どういう英語にすべきか迷うけど。

**Comment by knokmki612** [comment]
現状上記議論した内容でインポート機能が実装されており、別途取り上げるべき内容あれば別途issueにしてもらえればと思います
