### ISSUE TITLE
Card UI の角丸は 12px をデフォルトに

### ISSUE THREAD

**Issue by Hidetaro7** [npocccties/chiloportal#256]
このプロジェクトにおいて、デザイン仕様では角丸に 12px を多く使っているので、 JumpuUI Card コンポーネントのデフォルトをオーバーライドしたほうがいいかも、任せます。

TailwindCSS でいうところの `rounded-xl` に相当します。

@knokmki612

**Comment by Hidetaro7** [comment]
実装が済んだらクローズ願います @knokmki612

**Comment by knokmki612** [comment]
tailwindcssの設定値としてなにか上書きする、あるいはjumpu-cardを継承した角丸を変更したクラスを別途定義する、といった対応はとくに現状していないです。

個別にコンポーネントを実装する際にrounded-xlを付与することで対処しています。

そのような状態で差し支えないようであれば完了してもらえればと思います。

**Comment by Hidetaro7** [comment]
先に任せると伝えたのでこれで完了とします
