### ISSUE TITLE
デザインスケジュール

### ISSUE THREAD

**Issue by Hidetaro7** [npocccties/chiloportal#259]
- 10/26 [バッジグラフィックのガイドラインおよびテンプレート](https://github.com/npocccties/oku-private/issues/53)
- 11/02 [ロゴタイプ](https://github.com/npocccties/oku-private/issues/52)

サービス名称を考案中のため、上記の順番を変更

**Comment by Hidetaro7** [comment]
ひとまずデザイン側の予定を立てておきます。
@ties-makimura

**Comment by Hidetaro7** [comment]
11/16
- デザインシステム( Figma )
- 個別のバッジは必要ない
- クラフィック要素はすべて揃っている
- チャットボットの仕様も決まっている

11/24
判明しているデザインに関しては実装されている

**Comment by Hidetaro7** [comment]
次回 10/31 9時〜 
デザイン最終確認

**Comment by Hidetaro7** [comment]
@horimasumi トップページデザインの残りの課題で、本日まで期限となっているトップビジュアルの部分については Figma のほうでコメントを残しているのでご確認ください。
Slackでもコメントしましたが
https://www.figma.com/file/dCE06JShf29eqnvZ4vcE8U?node-id=26:84#295315991
https://www.figma.com/file/dCE06JShf29eqnvZ4vcE8U?node-id=737:6502#295289819
https://www.figma.com/file/dCE06JShf29eqnvZ4vcE8U?node-id=731:7149#295289235
について、ご確認いただけたらと思います。よろしくお願いします。

**Comment by Hidetaro7** [comment]
デザインで稼働が大きなタスクとして

- 全体のデザインに関わる修正（都度上がってくる可能性）（ディスカッション→検討→作業）
- バッジ（能力・知識）のイラレデータ作成とガイドライン作成
- ロゴデザイン

**Comment by knokmki612** [comment]
@Hidetaro7 こちらのissue完了できるようであれば完了いただければとおもいます

**Comment by Hidetaro7** [comment]
12/15のスケジュールを以て完了としたいと思います

**Comment by Hidetaro7** [comment]
> 能力バッジ詳細画面が Figma どおりに実装されている（久野）

こちらが確認できていますので、本件クローズします。
