### ISSUE TITLE
ペルソナAさんのユーザーストーリーの作成

### ISSUE THREAD

**Issue by knokmki612** [npocccties/chiloportal#26]
関連 #12 #13

- ペルソナAさんの利用目的
  - 教育委員会の指定に関係なく自発的に学習したい
- 利用目的から想定されるユースケース
  - 「子どもの一人ひとりの個性を伸ばしてあげたい、具体的な方法を学習したい」
  - 「まだ学び始めなので、できたら少ない学習時間でバッジを取れないだろうか？」

をもとに本システムの利用前～利用中～利用後の過程（○○画面にアクセス、○○にクリック、○○が分かった等）を言語化視覚化できたら完了

**Comment by Hidetaro7** [comment]
考えられる行動

##「子どもの一人ひとりの個性を伸ばしてあげたい、具体的な方法を学習したい」

1. トップのチャットで「子ども　個性」でメッセージ入力
2. トップの検索で「子ども　個性」をテキスト入力
3. 「子ども」や「個性」に見合う導線（ボタン、ナビ）を探す

## 「まだ学び始めなので、できたら少ない学習時間でバッジを取れないだろうか？」

上記3行動からさらに
4. 周りから薦められてチロポータルに来たけど、使いづらいと嫌なので軽く試してみたい、簡単に取得できるものから試してみる

---

現状であれば、検索窓と結果が設計されている必要がある

**Comment by Hidetaro7** [comment]
Figjamにてストーリーを作成した
https://www.figma.com/file/RhtnFKc1eiP1Ycn5g9i0Kk/OKUTEP-UX?node-id=0%3A1

**Comment by knokmki612** [comment]
ユーザーストーリーに関連する実装タスクが起こせているので完了でいいとおもった（ユーザーストーリーの是非等あればコメント等いただければと思います）

1. カテゴリを選択するか検索する #47 #56 #57 #49
2. 能力バッジを選択する #59 #48
3. 学習する
