### ISSUE TITLE
ペルソナBさんのユーザーストーリーの作成

### ISSUE THREAD

**Issue by knokmki612** [npocccties/chiloportal#27]
関連 #12 #13

- ペルソナBさんの利用目的
  - 教育委員会の育成指標から自発的に学習したい
- 利用目的から想定されるユースケース
  - 「大阪市教育委員会の認定であれば、片っ端からバッジ取得したい」
  - 「大阪市教育委員会から、法令に関するバッジを優先して取得したい」
  - 「法令と教室に関係する複数の関心があるので、そのバッジを欲しい物リストのようなものに入れたい」

をもとに本システムの利用前～利用中～利用後の過程（○○画面にアクセス、○○にクリック、○○が分かった等）を言語化視覚化できたら完了

**Comment by Hidetaro7** [comment]
Figjamにてストーリーを作成した
https://www.figma.com/file/RhtnFKc1eiP1Ycn5g9i0Kk/OKUTEP-UX?node-id=0%3A1

**Comment by Hidetaro7** [comment]
> * 「法令と教室に関係する複数の関心があるので、そのバッジを欲しい物リストのようなものに入れたい」

このストーリーは今回見送ることにした
