### ISSUE TITLE
能力バッジからアクセスする Moodle のコースの url

### ISSUE THREAD

**Issue by knokmki612** [npocccties/chiloportal#271]
該当する見た目

Figma: https://www.figma.com/file/dCE06JShf29eqnvZ4vcE8U/OKUTEP?node-id=26%3A84
スクリーンショット:
![image](https://user-images.githubusercontent.com/9744580/196864063-70e1a2ca-72c6-4bf3-a0f7-8693889bef31.png)

該当するSQLテーブル作成クエリ
https://github.com/npocccties/chiloportal/blob/0491c5c7cb80b8fd7fcdc8e5d3119bbf08f7ed3e/backend/sql/create_table.sql#L39-L40

質問

1. alignments_targeturlが能力バッジからアクセスするMoodleのコースのurlという想定で認識相違ないですか
2. ~~現状能力バッジに相当するレスポンスのドキュメンテーション（OpenAPI）に上記が含まれていないように思いますがあってますでしょうか~~
3. 上記SQLではNULL制約になっていますが、必ずしも（インポート時）値が得られるとは限らないということであってますでしょうか

**Comment by knokmki612** [comment]
質問に対する回答を持っていそうな方にメンションさせてください :pray: @ties-makimura @yoshinobu-etou-id @m-takay

**Comment by yoshinobu-etou-id** [comment]
@knokmki612 

> 2. 現状能力バッジに相当するレスポンスのドキュメンテーション（OpenAPI）に上記が含まれていないように思いますがあってますでしょうか

ご指摘の通り、以下はレスポンスに入ってないですね。
* alignments_targetname	
* alignments_targeturl

どのAPIのレスポンスで必要となりますでしょうか？

**Comment by knokmki612** [comment]
> どのAPIのレスポンスで必要となりますでしょうか？

`/badges` API ですね

https://github.com/npocccties/chiloportal/blob/292e908f754c10a92f045725f4d03973151bd050/frontend/pages/wisdom_badges/%5BwisdomBadgesId%5D.tsx#L24-L29

**Comment by yoshinobu-etou-id** [comment]
@knokmki612 
上記対応しましたので、開発サーバでご確認お願い致します。
インポートした wisdom_badge_id[101] の レスポンスの
alignments_targetname, alignments_targeturl に値が入っていることはSwgaggerUIで確認済みです。

**Comment by m-takay** [comment]
> alignments_targeturlが能力バッジからアクセスするMoodleのコースのurlという想定で認識相違ないですか

サンプルのjsonを見た感じではその想定で合っているようです（仕様を調べた上での回答ではありません）
```
"alignments": [
        {
            "targetName": "子どもの変化と教職について省察する",
            "targetUrl": "https:\/\/opedu.lib.osaka-kyoiku.ac.jp\/course\/view.php?id=52"
        },
```

> 上記SQLではNULL制約になっていますが、必ずしも（インポート時）値が得られるとは限らないということであってますでしょうか

能力バッジと知識バッジを同じテーブルで扱っていたときの名残のような気がします。
基本的にはセットされる項目だと思います。

**Comment by knokmki612** [comment]
> 基本的にはセットされる項目だと思います。

だとすれば、SQLテーブルとしてはNOT NULL 制約に、OpenAPIとしては必須のプロパティとしてレスポンスに含まれるように変更されると嬉しいなと思いました。（現状でも値が含まれているかフロント側でチェックして取り扱えばいいということではあるので、大きな支障はないです）

**Comment by knokmki612** [comment]
ありがとうございます、不明点が解消されたので完了します
