### ISSUE TITLE
Criteria.type に想定される値

### ISSUE THREAD

**Issue by knokmki612** [npocccties/chiloportal#275]
Figma https://www.figma.com/file/dCE06JShf29eqnvZ4vcE8U/OKUTEP?node-id=26%3A84
スクリーンショット
![image](https://user-images.githubusercontent.com/9744580/196883575-156f7472-8953-4df3-947d-d37ceca470d6.png)

該当するインポート処理

https://github.com/npocccties/chiloportal/blob/292e908f754c10a92f045725f4d03973151bd050/backend/chiloportal/management/commands/import_badge.py#L282-L296

質問

現状 `criteria_narrative` がインポート時パースされ `type` フィールドに値が格納されることまでは理解しているのですが、その想定される値が知りたいです。

背景

`criteria-${Criteria.type}.png` のような画像をあらかじめフロントエンド側でアセットとして用意する際に、想定される値分の画像を用意する必要があります

**Comment by knokmki612** [comment]
質問に対する回答を持っていそうな方にメンションさせてください :pray: @ties-makimura

**Comment by knokmki612** [comment]
ping おくらせてください :pray: @ties-makimura

**Comment by ties-makimura** [comment]
@knokmki612 

この辺りの話でしょうか．
https://github.com/npocccties/chiloportal/issues/25#issuecomment-1225496652

> ## 最終的に表示するアイコンの種類
> 
> - criteria.narrative から取得した ○○○ の情報を元に，フロントで表示するアイコンを用意する．将来的に増える可能性はある．
>   現時点で想定している，アイコンのパターンと該当する criteria.narrative のテキストは以下の通り．
>   - ビデオアイコン：ビデオ
>   - クイズアイコン：小テスト
>   - アンケートアイコン：アンケート，レッスン
> - 懸念
>   - criteria.narrative のテキスト出力時点では，同じアイコンパターン想定でも異なるテキスト（小テスト，クイズ，Quiz， ...etc）の可能性がある．その場合，どのタイミングでアイコン判定するか決める必要があるかと思う（インポート時点？フロント表示時点？）

**Comment by knokmki612** [comment]
> この辺りの話でしょうか．

はい、おっしゃるとおりです。

**Comment by ties-makimura** [comment]
> 対応するクライテリアの種類とアイコンのパターンはどのようにして決めていきますか？

https://github.com/npocccties/chiloportal/issues/275#issuecomment-1291467088
で伝えたルール通りと思いましたが，どのようなことを確認したいのでしょうか？ @knokmki612 

| クライテリアの種類 | アイコンのパターン |
| - | - |
| ビデオ | ビデオアイコン |
| 小テスト | クイズアイコン |
| アンケート | アンケートアイコン |
| レッスン | アンケートアイコン |

**Comment by knokmki612** [comment]
いえ、それがどこで検討中の内容なのか最終的な決定なのか、それ以外に想定する種類は存在するかなどが把握できていなかったのでお伺いしたかった次第です。

回答ありがとうございます。それではそれでFigma上の画像等確認し実装していこうかと思います。

**Comment by knokmki612** [comment]
現状いずれにも該当しない場合、アンケート、レッスンで用いる画像と同じものが表示されます。

https://github.com/npocccties/chiloportal/blob/57bd058449927c529cdd157110f3c052152d91e3/frontend/lib/criteria.ts#L7-L10

> クライテリアの種類については運用中でもある程度指定したい

おそらく上記引用したモジュールのソースコードを拡張し、 `/frontend/public` 配下に対応する画像を追加するような手順になるかと思います。

クライテリアの種類の追加方法等取り上げたい場合は別途issueにしてもらえればと思います。

**Comment by ties-makimura** [comment]
> おそらく上記引用したモジュールのソースコードを拡張し、 /frontend/public 配下に対応する画像を追加するような手順になるかと思います。

手順が分かれば現状でも大丈夫そうですね．少し様子見ます．
