### ISSUE TITLE
ペルソナCさんのユーザーストーリーの作成

### ISSUE THREAD

**Issue by knokmki612** [npocccties/chiloportal#28]
関連 #12 #13

- ペルソナCさんの利用目的
  - 教育委員会指定のバッジだけを取得
- 利用目的から想定されるユースケース
  - 「「このバッジを取得して報告してください」とURLを渡される」
  - 「「育成指標である『授業を展開する力』に関連するバッジをすべて取得して報告してください」と口頭で言われる」

をもとに本システムの利用前～利用中～利用後の過程（○○画面にアクセス、○○にクリック、○○が分かった等）を言語化視覚化できたら完了

**Comment by Hidetaro7** [comment]
考えられる行動

## 「このバッジを取得して報告してください」とURLを渡される

能力バッジ詳細画面に直接行けるので、URL設計ができていたら問題ないと考えられる。

## 「育成指標である『授業を展開する力』に関連するバッジをすべて取得して報告してください」と口頭で言われる

- 伝えた側は複数のURLをメールなどで伝える、この場合、直接URLを踏めばいい
- トップで「授業を展開する力」でキーワード検索、チャットボットに尋ねる
- トップに「授業を展開する力」というワードがないか、とりあえず探す
  - ワードは大抵限定的な場合見つからないので、指定の教育委員会を探そうとする
  - 教育委員会ごとの育成指標一覧でたくさんのバッジが出た、、テンション下がる、、
  - もっと育成指標のタイトルだけが一覧できたらいいのに。。
  - バッジの見た目が大きいので、バッジを簡略化した一覧表示モードがあると助かるという気持ちになる

例えば[堺市育成指標ごとのバッジ一覧は検討中](https://www.figma.com/file/dCE06JShf29eqnvZ4vcE8U/OKUTEP?node-id=26%3A83)だが、これだと上記のテンションが下がるCさんに対して、バッジの見せ方より、育成指標のカテゴリ一覧が見やすいモードに切り替えられるようなものがあったらよい。

**Comment by Hidetaro7** [comment]
バッジ一覧表示にも、簡易的なバリアントを設計する必要があるので別Issueに立てる

**Comment by Hidetaro7** [comment]
> * トップで「授業を展開する力」でキーワード検索、チャットボットに尋ねる

Cさんの関心事としては育成指標の中にある『授業を展開する力』に関連するバッジしかないので、『授業を展開する力』のような単位の検索結果がないと、他の手がかりがなくなってCさんはお手上げになり、離脱する。

検索結果
○○教育委員会
「授業を展開する力」に関連する能力バッジがn件あります

管理職向け（副校長、教頭、准園長 ・副園長）
能力バッジ
能力バッジ
...

養護教諭向け（若手教員）
能力バッジ
能力バッジ
...

**Comment by knokmki612** [comment]
> トップで「授業を展開する力」でキーワード検索、チャットボットに尋ねる
> トップに「授業を展開する力」というワードがないか、とりあえず探す

#43 を踏まえると検索ではたどり着かないように思います

#27 と同じように育成指標->成長段階->指標項目とたどるのかなと思いましたがどうなんでしょうか

**Comment by Hidetaro7** [comment]
> https://github.com/npocccties/chiloportal/issues/27 と同じように育成指標->成長段階->指標項目とたどるのかなと思いましたがどうなんでしょうか

例えば「教員としての資質の向上に関する指標の学級経営を全部学習してください」と薦められた場合のストーリーだとその流れになるのでCさんに該当します

**Comment by Hidetaro7** [comment]
> https://github.com/npocccties/chiloportal/issues/43 を踏まえると検索ではたどり着かないように思います

育成指標名、成長段階名、指標項目名
それぞれが検索対象に含まれる必要がある、ということだと思います。
（Cさんは優先度が高いペルソナ）

**Comment by knokmki612** [comment]
> > トップで「授業を展開する力」でキーワード検索、チャットボットに尋ねる
> > トップに「授業を展開する力」というワードがないか、とりあえず探す
> 
> #43 を踏まえると検索ではたどり着かないように思います

> 育成指標名、成長段階名、指標項目名
> それぞれが検索対象に含まれる必要がある、ということだと思います。
> （Cさんは優先度が高いペルソナ）

キーワード検索の検索対象に現状含まれないという認識ですが、一方で教育委員会（コンシューマー）、誰向け（職業）、指標項目（カテゴリ）から能力バッジを絞り込む https://github.com/npocccties/chiloportal/issues/60 ということは可能かもしれません

また、能力バッジ https://github.com/npocccties/chiloportal/issues/48 から成長段階別能力バッジ一覧 https://github.com/npocccties/chiloportal/issues/51 への動線があるとよりよいのかもしれません

**Comment by Hidetaro7** [comment]
> また、能力バッジ https://github.com/npocccties/chiloportal/issues/48 から成長段階別能力バッジ一覧 https://github.com/npocccties/chiloportal/issues/51 への動線があるとよりよいのかもしれません

https://www.figma.com/file/dCE06JShf29eqnvZ4vcE8U/OKUTEP?node-id=156%3A636

ここからの導線が妥当かと思います

**Comment by knokmki612** [comment]
ユーザーストーリーに関連する実装タスクが起こせているので完了でいいとおもった（ユーザーストーリーの是非等あればコメント等いただければと思います）

「このバッジを取得して報告してください」とURLを渡される

1. 能力バッジのurlにアクセスする https://github.com/npocccties/chiloportal/issues/48
2. 学習する

育成指標である『授業を展開する力』に関連するバッジをすべて取得して報告してください」と口頭で言われる

1. 育成指標・成長段階から探す https://github.com/npocccties/chiloportal/issues/57 https://github.com/npocccties/chiloportal/issues/50
2. 能力バッジを選択する https://github.com/npocccties/chiloportal/issues/59 https://github.com/npocccties/chiloportal/issues/63 https://github.com/npocccties/chiloportal/issues/48
3. 学習する
