### ISSUE TITLE
alignments_target{name,url}は必ず値が存在する想定として取り扱う

### ISSUE THREAD

**Issue by knokmki612** [npocccties/chiloportal#287]
> 基本的にはセットされる項目だと思います。

だとすれば、SQLテーブルとしてはNOT NULL 制約に、OpenAPIとしては必須のプロパティとしてレスポンスに含まれるように変更されると嬉しいなと思いました。（現状でも値が含まれているかフロント側でチェックして取り扱えばいいということではあるので、大きな支障はないです）

_Originally posted by @knokmki612 in https://github.com/npocccties/chiloportal/issues/271#issuecomment-1286401620_

**Comment by yoshinobu-etou-id** [comment]
@knokmki612 
上記対応しましたので、ご確認をお願いいたします。

**Comment by knokmki612** [comment]
#290 にて対応されていることを確認しました、ありがとうございます :pray:
