### ISSUE TITLE
ペルソナDさんのユーザーストーリーの作成

### ISSUE THREAD

**Issue by knokmki612** [npocccties/chiloportal#29]
関連 #12 #13

- ペルソナDさんの利用目的
  - 教育委員会側の立場の者
- 利用目的から想定されるユースケース
  - 「Cさんに対してURLを探し当てて、URLをCさんに渡したい」

をもとに本システムの利用前～利用中～利用後の過程（○○画面にアクセス、○○にクリック、○○が分かった等）を言語化視覚化できたら完了

**Comment by Hidetaro7** [comment]
Figjamにてストーリーを作成した
https://www.figma.com/file/RhtnFKc1eiP1Ycn5g9i0Kk/OKUTEP-UX?node-id=0%3A1

**Comment by knokmki612** [comment]
ユーザーストーリーに関連する実装タスクが起こせているので完了でいいとおもった（ユーザーストーリーの是非等あればコメント等いただければと思います）

Cさんに対してURLを探し当てて、URLをCさんに渡したい

1. 育成指標から探す #46 #55
2. Cさんの該当する成長段階を選ぶ #50 #63
3. URLをコピー #51
4. Cさんに渡す
