### ISSUE TITLE
能力バッジと教育委員会あるいは育成指標との関連性を示すダイアログの目的の整理

### ISSUE THREAD

**Issue by knokmki612** [npocccties/chiloportal#292]
Figma: https://www.figma.com/file/dCE06JShf29eqnvZ4vcE8U/OKUTEP?node-id=156%3A636
スクリーンショット
![image](https://user-images.githubusercontent.com/9744580/197105928-42f20059-8fb1-4ce2-807d-ad8cb89f54bf.png)

このダイアログがどのような情報を提示するのが目的なのか整理したい

背景としては、現状見た目と振る舞いについて実装はしたものの、データ取得に関して曖昧な点があり、現状だと能力バッジに関連する教育委員会（コンシューマー）のすべての育成指標（フレームワーク）を取得している

https://github.com/npocccties/chiloportal/blob/51808d304a54874bdda4bfb6a2b11cb6219d0923/frontend/lib/use-badges-frameworks.ts#L11-L20

しかし現状の見た目は能力バッジが所属する育成指標を列挙したいようにも見えるので、なにがあるべき姿なのか明確化したい

2つ方向性が考えられるように思う

### 1. この能力バッジを認定している教育委員会を知ってもらいたい

だとすれば育成指標の列挙は不要では

### 2. この能力バッジが所属している育成指標（の成長段階）を回遊してもらいたい

だとすれば現状の実装では能力バッジが所属していない育成指標（とその成長段階）が含まれうるので適切でないのでは

**Comment by knokmki612** [comment]
取得表示するデータが曖昧で影響がありそうなのでバックエンドもラベル付与しておきます

**Comment by knokmki612** [comment]
この議論に必要そうなかたをメンションしておきます @Hidetaro7 @horimasumi

**Comment by knokmki612** [comment]
> 取得表示するデータが曖昧で影響がありそうなのでバックエンドもラベル付与しておきます

方向性 1\. の場合は影響ない想定です（コンシューマ一覧があれば要件満たすため）

**Comment by Hidetaro7** [comment]
> 2. この能力バッジが所属している育成指標（の成長段階）を回遊してもらいたい

ひとつのインターフェースで複数の目的を持つのは混乱する元となることと、
表題に示すとおり「以下の教育委員会に認定されています」という目的を知らせるだけにするべきと思います。
もしくは「教育委員会育成指標に認定されています」であれば育成指標までが表示されているべきだと思います。
後者のほうが今回の場合適切な気もしますが、認識をあわせましょう。

会話の中で出たと思うのですが、どれだけの教育委員会に認定されているかという権威付けも目的に含まれるように思います。

ペルソナCさんについてはダイレクトにこのページにたどり着くこともあるので、そういった場合は関心のある教育委員会育成指標から選択し始めるUIが別になければならないと考えると、いきなり離脱させる可能性もあり、親切設計のつもりが悪い体験を与えてしまうことについては慎重に考えたいし、このページでそれを求めるにはちゃんとユーザビリティテストを行ったほうがいいかもしれません。

ペルソナA, Bさんについては、ここにたどり着く前の段階で教育委員会ごとの成長段階からバッジを選ぶストーリーが考えられているので、バッジ詳細ページから前のページに戻ることとなります。

もっとこのページでも他の成長段階を回遊してもらいたいのであれば、ショッピングサイトのその他のおすすめみたいなサジェスチョンが充実していたほうがユーザーとしてはよりわかりやすいと思いますが、それ相当のしくみも必要かと思いますので将来検討したい内容になるかもしれません。

という私の所感です。

**Comment by knokmki612** [comment]
動線はもたせず 1\. の方針ということで異存ないです。
対応のためのタスクを別途用意するか、直接対応できましたら完了にしようと思います。

**Comment by knokmki612** [comment]
> 表題に示すとおり「以下の教育委員会に認定されています」という目的を知らせるだけにするべきと思います。

これについては現状実装可能ですが

> もしくは「教育委員会育成指標に認定されています」であれば育成指標までが表示されているべきだと思います。

こちらは能力バッジに関連する育成指標（とコンシューマー）を返却するAPIは存在しないので実装不可能という認識です

**Comment by knokmki612** [comment]
バックエンドへの影響ない方針になったと思うのでラベルから取り除いておきます
