### ISSUE TITLE
バッジ一覧表示コンポーネントのバリアントを設計する

### ISSUE THREAD

**Issue by Hidetaro7** [npocccties/chiloportal#30]
バッジ一覧表示にも、簡易的なバリアントを設計する必要があるので別Issueに立てる

_Originally posted by @Hidetaro7 in https://github.com/npocccties/chiloportal/issues/28#issuecomment-1226645396_

- より詳しい内容が記載されているバリアント
- 簡易版のバリアント
  - 能力バッジ名
  - 取得条件
  - 発行大学名、ロゴ
  - n件の育成指標（hoverで詳細表示？）

**Comment by Hidetaro7** [comment]
ペルソナCさんのニーズで、「堺市教育委員会から薦められて『学校園管理職としての資質』の全部を学んでください」と合った場合の導線として、
- バッジ詳細内容より、今は育成指標から探すことのほうが重要
なので、簡素表示のためのバッジコンポーネントのバリアントで設計

図では左がCさん向け、右はBさんのように育成指標、バッジ内容ともに見渡すことができる

<img width="1113" alt="image" src="https://user-images.githubusercontent.com/281424/186554198-e40936ad-bdb7-45ce-8cf6-79e2752ca882.png">

右カラムサイドに table of content を配置

**Comment by Hidetaro7** [comment]
バッジコンポーネントは1つで複数のバリアントを持つように設計中

https://www.figma.com/file/dCE06JShf29eqnvZ4vcE8U/OKUTEP?node-id=265%3A2280

**Comment by knokmki612** [comment]
> バッジ詳細内容より、今は育成指標から探すことのほうが重要
> なので、簡素表示のためのバッジコンポーネントのバリアントで設計

TOC表示があれば指標項目を見渡すことができるので、引用部のような目的があるのであれば、バッジとしてはコンパクトな見た目がなくともよいように思ったのですがいかがですか

**Comment by knokmki612** [comment]
https://www.figma.com/file/dCE06JShf29eqnvZ4vcE8U?node-id=249:1753#261085891 にてバリアントを用意しないことで合意した
