### ISSUE TITLE
トップで「おすすめバッジ」セクションの作り方について議論・確認する

### ISSUE THREAD

**Issue by Hidetaro7** [npocccties/chiloportal#31]
ミーティングにて議題にしたい

トップの入り口として、
運営側がまとめたおすすめバッジリストをどのようにして運営、管理するのか、
あらためて確認した上で画面設計をする。

以前はブログのようなものが案に挙がっていた。

**Comment by Hidetaro7** [comment]
トップでFigmaであれば「おすすめのバッジ」セクションに記事タイトルが並ぶ感じを想定

<img width="484" alt="image" src="https://user-images.githubusercontent.com/281424/186880854-72f4fe34-6114-4c9a-8172-eef78bcd9131.png">

**Comment by Hidetaro7** [comment]
参考 https://www.figma.com/file/dCE06JShf29eqnvZ4vcE8U?node-id=121:1583#260226705

**Comment by knokmki612** [comment]
おすすめバッジはリポジトリ内にyaml、jsonファイル等によって指定してアプリケーションのビルド時に参照することによっておこなうことになった #84
