### ISSUE TITLE
バッチ処理でMoodleからバッジのデータを取得する際のIDについて

### ISSUE THREAD

**Issue by m-takay** [npocccties/chiloportal#33]
バッチ処理でMoodleからバッジのデータを取ってくる際のIDはどのように取得すればよいか？

> 能力バッジ
> https://opedu.lib.osaka-kyoiku.ac.jp/badges/badge_json.php?id=41
> https://opedu.lib.osaka-kyoiku.ac.jp/badges/badge_json.php?id=139
> https://opedu.lib.osaka-kyoiku.ac.jp/badges/badge_json.php?id=145

上記の「id=」の数字

- 能力バッジ一覧取得のAPIがあってそれで取ってくる？（すべて取得するならこれでOK？）
- 取り込みが必要なIDをDBのテーブルであらかじめ定義しておく？（必要なものに絞る必要があるならテーブル化必要？）

**Comment by yoshinobu-etou-id** [comment]
@m-takay 

> Webサービスを使用するのではないかなと思います。
> 例えば下記のように発行済みトークンと機能名をパラメータに指定して取得するのではないかなと思います。
> 
> https://z.cccties.org/39a/webservice/rest/server.php?wstoken=9267fb15f1870152bbf63893fb9ddad2&wsfunction=core_badges_get_user_badges&moodlewsrestformat=json

発行済みトークンはユーザに紐づけられたものに関してのみ、該当ユーザのバッジ一覧しか取得できなかったので、
Moodelの「mdl_badge」テーブルに格納されているバッジの一覧は取得できないですね。
ちなみに、管理者のトークンで取得しようとしても、何も返ってきませんでした。当然といえば当然のような気がしますが。

MoodelのDBから取得した方が早そうな気がしてきました。
https://moodle.org/mod/forum/discuss.php?d=429075

**Comment by yoshinobu-etou-id** [comment]
@m-takay 
テストMoodleでSELECT文を実行できるプラグイン登録してみましたが、
クエリ結果のCSVは手動でしかダウンロードできないようです。
https://z.cccties.org/39a/report/customsql/category.php?id=1

**Comment by yoshinobu-etou-id** [comment]
@m-takay 
テストMoodleでSELECT文を実行できるプラグイン登録してみましたが、
クエリ結果のCSVは手動でしかダウンロードできないようです。
https://z.cccties.org/39a/report/customsql/category.php?id=1

**Comment by yoshinobu-etou-id** [comment]
@m-takay 
恐らくDBのレプリケーションをしないと無理な気がしてきました。
https://moodle.org/mod/forum/discuss.php?d=426387

**Comment by m-takay** [comment]
@yoshinobu-etou-id 
基本的にmoodle側はさわれない前提で、APIでIDを取ってくる必要があると思っています。

**Comment by dynamis** [comment]
一括インポートすると バッジとカテゴライズドバッジの対応を後で設定するのが難しくなるので、バッジのインポートは 1 つずつ行って作業する。

従って、指定 URL (のリスト) をインポートする機能を実装するだけで、対象バッジリストを自動で絞り込む機能の実装は不要。
