### ISSUE TITLE
デフォルトブランチを develop にする

### ISSUE THREAD

**Issue by knokmki612** [npocccties/chiloportal#34]
#18 の議論で開発ブランチを develop にすることになったので、GitHubリポジトリのデフォルトブランチも develop に指定できるとうれしいと思った

手順 https://docs.github.com/ja/repositories/configuring-branches-and-merges-in-your-repository/managing-branches-in-your-repository/changing-the-default-branch

理由

1. プルリクエスト作成時のベースブランチにデフォルトブランチが指定される（現状あやまってmainブランチを指定する可能性がある）
2. 特定のキーワードでissueを完了する機能がデフォルトブランチにのみ対応している 

> キーワードの1つを使用してPull RequestをIssueにリンクしたい場合は、PRがデフォルトブランチ上になければなりません。

https://docs.github.com/ja/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue

**Comment by knokmki612** [comment]
> 現状あやまってmainブランチを指定する可能性がある

あらかじめ特定の条件でコミットが反映されないよう、ブランチを保護するように設定してもいいと思った

https://docs.github.com/ja/repositories/configuring-branches-and-merges-in-your-repository/defining-the-mergeability-of-pull-requests/managing-a-branch-protection-rule

**Comment by knokmki612** [comment]
たぶん @ties-makimura  さんにデフォルトブランチを変更いただけた（ありがとうございます）

**Comment by ties-makimura** [comment]
対応しました．必要に応じて設定変更していきましょう．

- デフォルトブランチを develop に
- mainブランチを保護，以下有効
  - Require a pull request before merging
  - Require approvals (Required number of approvals before merging:1)
