### ISSUE TITLE
キーワードバッジ検索APIに想定する仕様の差異がある

### ISSUE THREAD

**Issue by knokmki612** [npocccties/chiloportal#340]
バックエンドのテストを参照すると

- キーワードが空文字列のケース
- 存在しない（該当するバッジがない）キーワードのケース

は異常系 HTTP ステータスコードが返される仕様

https://github.com/npocccties/chiloportal/blob/34229488060b71709a582a1d000aa940a82f331f/backend/chiloportal/tests/views/localhost/test_wisdom_badges_list_keyword.py#L296-L356

フロントエンド（SSR）時のデータ取得処理では

上記2点のケースは正常時と区別ない想定で実装

https://github.com/npocccties/chiloportal/blob/34229488060b71709a582a1d000aa940a82f331f/frontend/pages/search.tsx#L18-L25

フロントエンドの都合で考えると上記2点のケースは件数ゼロで正常時のレスポンスと同じだと嬉しいが、それ以外の解決方法も視野にいれ実装の差異についてなんらかの方法で解消されれば完了

**Comment by yoshinobu-etou-id** [comment]
@knokmki612 
OpenAPIに基づき404を明示的に返す設計でしたが、世の中的には200っぽいですね。
https://qiita.com/YuyaAbo/items/a8b4b055a3d9dbeffcf3

なので直しておきます。

**Comment by knokmki612** [comment]
> OpenAPIに基づき404を明示的に返す設計

おっしゃる通りですね。この場合の仕様に準拠していない実装はフロント側がおこなっていると思います。
API設計の段階で議論すべき箇所でした。

https://github.com/npocccties/chiloportal/blob/8f61c9f6cc9062caa2b16c1739c12cf0ea2ec399/backend/doc/openapi.yaml#L377-L380

対応ありがとうございます :pray:

**Comment by yoshinobu-etou-id** [comment]
とりあえず404は200を返すようにしました。
ただ、page_numberが0とかの場合に404を返してます。
400がいいような気もしますが。

**Comment by knokmki612** [comment]
page_numberが0の場合は無効というのは同じ認識で、フロント側としては生じないよう実装しているつもりではあります

404なのか400なのかでいえば後者かと思いました（リソースはあるが無効なリクエストのため）

**Comment by yoshinobu-etou-id** [comment]
page_numberが0の場合は400にしました

**Comment by yoshinobu-etou-id** [comment]
そうすると /consumer のAPIも同様に無効な consumer_id が与えられたら、400を返すべきですね。
今は、空のJSONと200を返してますが、何か違和感があったので。

**Comment by yoshinobu-etou-id** [comment]
整理するとクエリパラメータに該当するデータがない場合のふるまいとしては、以下となりますでしょうか。
* キーワード検索のAPI：200の空データを返す
* 上記以外のAPI：400を返す

**Comment by knokmki612** [comment]
> そうすると /consumer のAPIも同様に無効な consumer_id が与えられたら、400を返すべきですね。
> 今は、空のJSONと200を返してますが、何か違和感があったので。

フロントエンド側での /consumer APIの使用は、 /consumer/list APIで取得した値をもとにおこなっている想定でおそらくフロントエンド側としては不都合ないとおもいます&より適切なステータスコードの取り扱いにおもいます

**Comment by knokmki612** [comment]
> 整理するとクエリパラメータに該当するデータがない場合のふるまいとしては、以下となりますでしょうか。
> * キーワード検索やクエリパラメータのないAPI：200の空データを返す
> * 上記以外のAPI：400を返す

私の想定漏れがないか少し自信がありませんが方針として違和感なさそうにおもいます

**Comment by yoshinobu-etou-id** [comment]
直しましたので、ご確認お願い致します。

**Comment by knokmki612** [comment]
バックエンド開発サーバーの Swagger UI では動作確認済みなのですが、（バックエンド開発サーバーを使用した）ローカルのフロントエンドでの動作確認して大丈夫そうか確認しようかと思っていますので、お待ちください

**Comment by knokmki612** [comment]
該当するキーワードがないケースにて、空の正常レスポンスが返されることを開発サーバーの Swagger UI で確認しました。

> キーワードが空文字列のケース

こちらの場合も空の正常レスポンスが返されるとフロントエンド側的には都合がよい（検索結果画面は任意か空文字列のキーワードで必ずAPIを叩くよう実装しているため）のですが、方針としてどうしておきたいというのはありますか？

例 https://dev-portal.oku.cccties.org/api/v1/wisdomBadges/list/keyword/?keyword=

**Comment by knokmki612** [comment]
> フロントエンド側的には都合がよい（検索結果画面は任意か空文字列のキーワードで必ずAPIを叩くよう実装しているため）

空文字列の時APIコールしない風に変更可能なように思うので、フロント側で対応するのが良さそうという気がしてきました

**Comment by knokmki612** [comment]
空文字列許容しないということであれば、OpenAPIで定義されているパラメーターに対して `allowEmptyValue: false` を付与したほうがより厳密なドキュメンテーションになりそうです

https://swagger.io/docs/specification/describing-parameters/#nullable

**Comment by knokmki612** [comment]
https://github.com/npocccties/chiloportal/issues/340#issuecomment-1292887681 https://github.com/npocccties/chiloportal/issues/340#issuecomment-1292888871 の変更を含んだPRを提出しようかとおもいます

**Comment by yoshinobu-etou-id** [comment]
なるほど。空文字は許容しないほうがよさそうですね。

**Comment by yoshinobu-etou-id** [comment]
空白許容しないようにしました。（OpenAPIのみの修正）
