### ISSUE TITLE
成長段階に関連する指標項目一覧APIに想定する仕様の差異がある

### ISSUE THREAD

**Issue by knokmki612** [npocccties/chiloportal#341]
field1プロパティが配列である箇所と連想配列である箇所があり実装の差異が生じている

OpenAPIは配列

https://github.com/npocccties/chiloportal/blob/8f61c9f6cc9062caa2b16c1739c12cf0ea2ec399/backend/doc/openapi.yaml#L534-L540

バックエンドサーバーのレスポンスは連想配列

https://github.com/npocccties/chiloportal/blob/8f61c9f6cc9062caa2b16c1739c12cf0ea2ec399/backend/chiloportal/responses.py#L250-L251

フロントエンドのモックは配列

https://github.com/npocccties/chiloportal/blob/8f61c9f6cc9062caa2b16c1739c12cf0ea2ec399/frontend/mocks/faker.ts#L19-L31

正直この構造自体がややこしいことに起因しているような気もするがいずれかの構造に統一できたら完了かと思う

**Comment by yoshinobu-etou-id** [comment]
すみません。バグってますね。直します。

**Comment by yoshinobu-etou-id** [comment]
直しました。

**Comment by knokmki612** [comment]
バックエンド開発サーバーの Swagger UI では動作確認済みなのですが、（バックエンド開発サーバーを使用した）ローカルのフロントエンドでの動作確認して大丈夫そうか確認しようかと思っていますので、お待ちください

**Comment by knokmki612** [comment]
field1 が配列になっていることを確認しましたが、レスポンスが配列でなくなっている気がします。OpenAPIは配列になってまして、OpenAPIのほうがあやまり（配列が4つネストした構造は生成不能）ということであればOpenAPIを修正したほうがよさそうです。いかがでしょう。

https://github.com/npocccties/chiloportal/blob/ff673f7f8de818102f025319d81eae6bb1caad2a/backend/doc/openapi.yaml#L116-L120

**Comment by yoshinobu-etou-id** [comment]
確かにご指摘の通りだと思いますので、OpenAPIについてFieldDetailは配列ではなく、オブジェクトを返すよう修正いたします。

**Comment by knokmki612** [comment]
構造が変更されるので、フロントエンド側でのデータ取得表示の対応が必要ですね。別途タスクにしておきますね。

**Comment by yoshinobu-etou-id** [comment]
OpenAPI、変更しておきました。
