### ISSUE TITLE
教育委員会が承認したバッジに当たる情報のとり方

### ISSUE THREAD

**Issue by knokmki612** [npocccties/chiloportal#35]
1. Open Badgeの仕様としてはどこからとれるのか
2. テーブル定義 https://github.com/npocccties/chiloportal/blob/develop/backend/sql/create_table.sql としてはどこからとれるのか

について知りたいと思った

**Comment by knokmki612** [comment]
画面仕様案-テーブル定義等_20220609.drawio.pdf を読むと consumer が各自治体に相当し、

1\. としてはとれないのでチロポータルで情報を付加する？

2\. としては

カテゴライズドバッジに consumer の識別子が含まれているのでこれで表現可能ということだろうか

https://github.com/npocccties/chiloportal/blob/f53091185e31aec47b746eed2bd01f3f9794ccc0/backend/sql/create_table.sql#L70-L72

と思った

**Comment by ties-makimura** [comment]
> Open Badgeの仕様としてはどこからとれるのか

Endorsementですかね．[
slackでその辺り話してました](https://webdino-butterfly.slack.com/archives/C032GK7KLUA/p1653395978735499)
で，Moodleではそこの機能が弱いので，チロポータルで用意する感じかと思います．
```
教育委員会の承認，endorsementですね．
 ↓をみるとendorsementは，
1．バッジ発行者に対する裏書，
2．発行するバッジ全体に対する裏書
3．発行された後の裏書
があるようで，Moodleは2の裏書ができるのですが，1つしかできない
https://www.imsglobal.org/sites/default/files/Badges/OBv2p0Final/examples/index.html#Endorsement
```

> カテゴライズドバッジに consumer の識別子が含まれているのでこれで表現可能ということだろうか

はい，consumer が承認者になりますね．

**Comment by knokmki612** [comment]
回答ありがとうございます。たすかりました。
