### ISSUE TITLE
カテゴライズドバッジとカテゴリの構造に関する提案

### ISSUE THREAD

**Issue by knokmki612** [npocccties/chiloportal#36]
カテゴリが何階層になるか不定（これまでの議論としては最大3階層として、それ以上の階層は登録作業者が3階層になるように登録する認識）ということであれば、DBテーブルとその参照関係として表現するより、単一の構造化ドキュメントとして表現したほうが柔軟性という観点でいいのではと思った

例（Markdownで構造化した場合、ただしおそらくショートコードは標準化された仕様ではなく各Markdownパーサーの実装依存の機能）

```markdown
# カテゴリ1

## カテゴリ2

### カテゴリ3

{{ badge <バッジのid> }} <!-- ショートコードとしてバッジを表記可能にする -->
```

関連するテーブルの該当箇所

https://github.com/npocccties/chiloportal/blob/f53091185e31aec47b746eed2bd01f3f9794ccc0/backend/sql/create_table.sql#L48-L55

https://github.com/npocccties/chiloportal/blob/f53091185e31aec47b746eed2bd01f3f9794ccc0/backend/sql/create_table.sql#L70-L73

**Comment by dynamis** [comment]
私もここの、木想像データなのにそのまま単なるフィールド 3 つの組み合わせに過ぎないのは気になっていました。

あくまでバッジ (に色々データを付与したカテゴライズドバッジ) の情報の一つとして所属カテゴリの情報を取得出来ればよいだけであるし、カテゴリの定義は基本的に教育期間毎の育成指標、例えば堺市であればこちらの「堺市教員育成指標[教員版]」他 3 種類の育成指標として整理された、固定の情報を入れるだけで原則更新がないものだから木構造データとしての処理を意識する必要もないだろうという判断で、読み出し時の処理が単純になる事を優先したんだろうか、どうなんだろうか、くらいの印象でした。

SQL で木構造を扱うなら閉包テーブル作りましょうって話になりがちなのだろうけど、ここではその木構造データを書き込み・更新するのではなく単なるツリー上の固定データの属性値がついてるだけだからちゃんとやらなくて良いのかな、などと。

実装コストとクエリのパフォーマンスとなど考えてどうするのが良いのやら、と。

**Comment by dynamis** [comment]
これは一旦保留し、フロントの画面構成やそれに必要な API などの理解が深まってから再検討することになった。

**Comment by dynamis** [comment]
note:

一見するとマルチカラムアトリビュートなのだけど、順序に意味がある＆個数の増減がない保証がされているのであればそのままでも良い。ツリー構造の制約は設けられないのでそこはコードの方で頑張る必要が生じるのだが


https://github.com/npocccties/chiloportal/issues/23#issuecomment-1232646570
>  >   カテゴリの中に親子関係のあるカテゴリ1,2,3が直接書かれてる件
> 
> こちらは手入力のことを考えると（たとえばExcelでデータ作成してCSV保存→SQLで流し込むみたいな）現状のままでよいかなと思いました。

ということだしこのままで良いという判断になりそう。

このコンシューマと受講対象を引数としてカテゴリツリーを要求するクエリというのは多発すると想定されるので、その生成・応答が遅くなってしまうようであれば要対応だという理解。

なお、SQL テーブル外で定義するとか JSON データ突っ込んで定義するという方法は、そもそも SQL テーブルの設計による制約でデータ構造のミスを減らしつつ、SQL 内の処理/クエリだけで完結できるようにするという趣旨に反するので原則避けるべきじゃないかと思っている。必ずしも全て SQL に完結する必要はないが例外実装するほどの特殊事情でも無さそうに思う。

**Comment by knokmki612** [comment]
現状のSQLのテーブル定義を元に

- 成長段階（Stage）から指標項目（Category、Compitency）の一覧を得る
- 成長段階と指標項目から指標項目に関する能力バッジの一覧を得る

ようなAPIが用意されて期待する構造が表現可能になる。提案した内容は採用しない。
