### ISSUE TITLE
Aが存在するがAに関連するBが存在しないケースのAPIのレスポンス

### ISSUE THREAD

**Issue by knokmki612** [npocccties/chiloportal#372]
https://github.com/npocccties/chiloportal/commit/2064aa32302b5502af9acbd34884772fc5990a18 でおこなわれた変更の一部に関して議論したいです

基本的には「Aに関連するBを返すAPI」についてです。

「Aに関連するBを返すAPI」へのリクエストは、A（のid）をパラメータとして指定します。

現状はAが存在するがAに関連するBが存在しない場合、無効なリクエストとしてレスポンスされるように思います。
パラメータとして指定したAが存在しないケースが無効として扱われるのは違和感ないですが、
Aに関連するBが存在するか否かはリクエストしないと判明しないので、リクエストとしては有効な（Aに関するBが存在しない構造の正常なレスポンスを返す）ように取り扱ってほしいです。

**Comment by yoshinobu-etou-id** [comment]
left join 的な感じですかね。ちょっと調べてみます。

**Comment by knokmki612** [comment]
話のきっかけとしては、 https://dev-portal.oku.cccties.org/wisdom_badges/101 でバッジを承認しているコンシューマ一覧を叩いた際に、クライアントエラーになるのがなんでだろうと気になったところからなんですが、

そもそもフロントエンド側がデータ取得する際の例外処理が実装できていないことがよくない気もするので、それについては https://github.com/npocccties/chiloportal/issues/373 に起票しました。ですのでそちらの実装すれば、こちらは変更せずとも問題なさそうか？とも思います

**Comment by yoshinobu-etou-id** [comment]
なるほど。フロントのエラーハンドリングで対応可ということで、了解いたしました。
ただ、関連先データ無しを許容するのであれば、バックエンド側で対応が必要ですね。

**Comment by knokmki612** [comment]
> 関連先データ無しを許容するのであれば、バックエンド側で対応が必要

そうですよね。コストがかかりそうということであれば、変更しない（そういうAPI設計である）ということで完了でも良さそうと思います。

**Comment by knokmki612** [comment]
エラーハンドリングの対応完了しましたので、こちら現状で完了するか、なにかしら対応するかおまかせします :pray:

**Comment by yoshinobu-etou-id** [comment]
エラー回避できたようなのでクローズでよいかと思いました。
