### ISSUE TITLE
docker-compose.dev-server.yml と docker-compose.production.yml の違い

### ISSUE THREAD

**Issue by ties-makimura** [npocccties/chiloportal#386]
docker-compose.dev-server.yml と docker-compose.production.yml はなぜ分けているのでしょうか？

**Comment by yoshinobu-etou-id** [comment]
本番環境は商用のSSL証明書を使用するからです。

**Comment by yoshinobu-etou-id** [comment]
開発サーバーではLet’sEncryptを使用しています。

**Comment by yoshinobu-etou-id** [comment]
https-portalというコンテナでLet'sEncryptのSSL証明書を取得しにいってます。

**Comment by ties-makimura** [comment]
Let’sEncrypt のホストはどこで指定するのでしょうか？.env の ALLOWED_HOSTS？

**Comment by yoshinobu-etou-id** [comment]
@ties-makimura 

> Let’sEncrypt のホストはどこで指定するのでしょうか？.env の ALLOWED_HOSTS？

はい。

**Comment by yoshinobu-etou-id** [comment]
以下に取得した証明書がドメイン毎に出力されます。
`/opt/chiloportal/backend/ssl_certs
`

いろいろ試していたので、直下にはゴミがあふれてますが、気にされないでください。

本番サーバーでは、環境変数の SSL_CERTS_DIR で証明書を配置するディレクトリを指定し、
下記命名で証明書を配置してください。

  * `signed.crt`: サーバー証明書
  * `domain.key`: サーバー証明書の秘密鍵

**Comment by ties-makimura** [comment]
違いについては理解できましたのでクローズします．
