### ISSUE TITLE
環境構築手順でdeploy.shだけ独立しているのが面倒

### ISSUE THREAD

**Issue by ties-makimura** [npocccties/chiloportal#387]
.env.dev-server の内容が dev-portal.oku.cccties.org を想定しており，他サーバで作業する場合は開発・本番関わらず， git clone https://github.com/npocccties/chiloportal.git してから .env ファイル書き換えて，deploy.sh 実行する流れになると思います．

その際，deploy.shを上位ディレクトリに移動して実行するのは面倒な気がするのですが，移動せず利用できないのでしょうか．

**Comment by yoshinobu-etou-id** [comment]
deploy.sh をどこに置けば良いのでしょうか？

**Comment by ties-makimura** [comment]
git clone すると chiloportal/backend/deploy.sh にあるので，その場所のまま実行したいです．

**Comment by yoshinobu-etou-id** [comment]
backend に置いているのも気持ち悪いので、せっかくなので chiloportal に移動してみましょうか。

**Comment by ties-makimura** [comment]
> backend に置いているのも気持ち悪いので、せっかくなので chiloportal に移動してみましょうか。

問題なければお願いします．

**Comment by yoshinobu-etou-id** [comment]
いやごめんなさい。試行錯誤の末の deploy.sh は chiloportal の上位ディレクトリにあるのでした。
何もないところから clone すると chiloportal のディレクトリが作成されるので、
chiloportal のディレクトリの中から clone は不可能です。

デプロイ時の cd.yml の中のスクリプトを見るとイメージがつくかと思います。
```
            sudo rm -rf /tmp/chiloportal
            git clone https://github.com/npocccties/chiloportal.git /tmp/chiloportal
            sudo cp /tmp/chiloportal/backend/deploy.sh /opt
            cd /opt
            sudo chmod 755 deploy.sh
            ./deploy.sh .env.dev-server docker-compose.dev-server.yml
```

**Comment by yoshinobu-etou-id** [comment]
clone された状態ならば、pull するだけなので chiloportal のディレクトリの中から
deploy.sh は実行できますが、最初の clone の問題があるので、致し方なく chiloportal の上位ディレクトリに
deploy.sh を配置しています。

**Comment by ties-makimura** [comment]
clone すると問題なら，cloneしなければいいのではないのでしょうか？
すみません理解できていないのかもしれません．

**Comment by yoshinobu-etou-id** [comment]
よくよく整理してみると makimura さんが仰る通り chiloportal ディレクトリ内から
deploy.sh を実行できた方がすっきりしますので、修正いたします。

**Comment by yoshinobu-etou-id** [comment]
@ties-makimura 
deploy.sh の中では clone しないよう修正しました。
代わりに cd.yml の方で clone するようにしています。
ご確認をお願いいたします。

**Comment by ties-makimura** [comment]
git clone 後，env編集 → deploy.sh 実行の流れができるようになりました．ご対応ありがとうございます．
