### ISSUE TITLE
開発サーバー想定でコンテナ立ち上げた後ブラウザからアクセスできない

### ISSUE THREAD

**Issue by ties-makimura** [npocccties/chiloportal#393]
ALLOWED_HOSTSを変更した後，docker-compose.dev-server.yml で起動した状態で，動作確認にあるページにアクセスできないのですが，他に何か必要な作業ありますか？

作業手順

1. deploy.sh の実行：./deploy.sh .env.dev-server docker-compose.dev-server.yml
2. 停止：chiloportal/backend/server_stop.sh .env.dev-server
3. .env.dev-serverを複製して，ALLOWED_HOSTS変更したファイル用意： .env.test-server
4. 開始：chiloportal/backend/server_start.sh .env.test-server docker-compose.dev-server.yml
5. コンテナの状態：
backend-web-1 などの PORTS が空なのは気になる　
```
$ docker ps
CONTAINER ID   IMAGE                     COMMAND                  CREATED          STATUS                          PORTS                    NAMES
72580dc4a9d6   steveltn/https-portal:1   "/init"                  12 minutes ago   Restarting (1) 35 seconds ago                            backend-https-portal-1
f4a1ed2edb4f   nginx:1.23.1              "/docker-entrypoint.…"   12 minutes ago   Restarting (1) 55 seconds ago                            backend-web-1
528a0f8114bb   backend-app               "python3"                12 minutes ago   Up 12 minutes                   8000/tcp                 backend-app-1
c11c18c91e53   postgres:13               "docker-entrypoint.s…"   12 minutes ago   Up 12 minutes                   0.0.0.0:5433->5432/tcp   backend-db-1
```
6. 管理者作成： docker-compose exec app python /workspace/manage.py createsuperuser

**Comment by yoshinobu-etou-id** [comment]
.env.dev-server はリポジトリに含まれており、それを変更しても
deploy.sh で checkout されて変更が取り消されます。
なので、chiloportal ディレクトリ以外に .env.dev-server を配置したうえで、
その絶対パスを deploy.sh の引数に与えてください。

**Comment by ties-makimura** [comment]
> .env.dev-server はリポジトリに含まれており、それを変更しても
> deploy.sh で checkout されて変更が取り消されます。

手順3 で，env.dev-serverを複製して，.env.test-server として分けているのが駄目なのでしょうか？

> その絶対パスを deploy.sh の引数に与えてください。

手順1以外のタイミングでも deploy.sh を実行する所があるのでしょうか？

**Comment by yoshinobu-etou-id** [comment]
@ties-makimura 
https-portal の調子が悪いかもしれないので、試しに https-portal 抜き版で試していただきたいです。
`./deploy.sh /opt/.env.manual-ssl-certs docker-compose.production.yml`

.envファイルの引数は絶対パスで与えてください。

**Comment by yoshinobu-etou-id** [comment]
すみません。一つ言い忘れておりました。
環境変数のSSL証明書のディレクトリにはデプロイ先のホストのドメインのSSL証明書を配置する必要がありました。

**Comment by yoshinobu-etou-id** [comment]
もしSSL証明書の用意が難しいようでしたら、
とりあえず以下で試して頂きたいです。

`./deploy.sh .env.test-server（※絶対パス） docker-compose.dev-server.yml`

**Comment by ties-makimura** [comment]
> もしSSL証明書の用意が難しいようでしたら、 とりあえず以下で試して頂きたいです。
> 
> `./deploy.sh .env.test-server（※絶対パス） docker-compose.dev-server.yml`

立ち上がりました．

確認ですが， https-portal有り版（docker-compose.dev-server.yml）で， ALLOWED_HOSTSを変更する場合，deploy.shを再実行しなければいけないのでしょうか？
コンテナを再起動する際に，env を更新するだけでは駄目？

**Comment by yoshinobu-etou-id** [comment]
backend のコンテナを再起動する server_restart.sh に対し deploy.sh と同じように、
.env.test-server（※絶対パス）と docker-compose.dev-server.yml を与えれば、
いけると思います。

**Comment by ties-makimura** [comment]
> backend のコンテナを再起動する server_restart.sh に対し deploy.sh と同じように、 .env.test-server（※絶対パス）と docker-compose.dev-server.yml を与えれば、 いけると思います。

コンテナを再起動すると，let's encrypt の再作成も行ってくれるということでしょうか．

**Comment by yoshinobu-etou-id** [comment]
yes

**Comment by yoshinobu-etou-id** [comment]
ドメインが変われば証明書を取得しにいき、
60日経過した状態で同一ドメインでコンテナ再起動すれば証明書を更新してくれます。

**Comment by ties-makimura** [comment]
>ドメインが変われば証明書を取得しにいき、
60日経過した状態で同一ドメインでコンテナ再起動すれば証明書を更新してくれます。

上記想定通り動作しました．
.envファイルの引数は絶対パスということを気を付けるようにします．
