### ISSUE TITLE
教育委員会ごとの育成指標一覧を設計

### ISSUE THREAD

**Issue by Hidetaro7** [npocccties/chiloportal#40]
キャリアステージの名称をステージごとの名称としてつくる

堺市の場合「教員養成期」「基礎形成期」など
大阪市の場合「第一ステージ」など

キャリアステージがまたがっている場合も想定する
（例）

充実 ・ 発展期

  - 教諭, 保育教諭
  - 指導教諭等, 主任保育教諭
  - 主幹教諭, 主任保育教諭

---

- [x] 大阪市教育委員会
- [x] 堺市教育委員会

が~~できたら~~TIESさんに確認いただけたら完了

**Comment by Hidetaro7** [comment]
https://www.figma.com/file/dCE06JShf29eqnvZ4vcE8U/OKUTEP?node-id=26%3A83

こちらに作成しました。
大阪市はすべて対象者ごとに同じ内容になってしまいました（0ステージ〜第4ステージ）

キャリアステージのラベリングはタグのような見た目で配置しています。
余談かもしれませんが、、
これを押したらタグ一覧みたいなものが欲しくなると考えてしまいましたが、情報の数は少ないことと、教育委員会ごとに言い方が違うのであまりそれには意味がないのかなと思いました。

**Comment by horimasumi** [comment]
キャリアステージのタグのようなラベリングは，ちょっと違和感を感じます．
教員育成指標の基本構造は，
自治体
→自治体で分けた教員育成指標
→成長段階
→指標項目
（https://www.mext.go.jp/content/20200626-mxt_kyoikujinzai01-000008267-5.pdf）

なので，成長段階のタグが先に見えてしまうと，上記の基本構造がよくわからなくなるような気がしました．
**〇〇市**
　**・教員育成指標名**（例：管理職としての資質の向上に関する指標）
　　　[第1ステージ][第2ステージ][第3ステージ][第4ステージ]←これをタグかボタンっぽく表示
　**・教員育成指標名**（例：教員としての資質の向上に関する指標（幼稚園参考版）
　　　[第1ステージ][第2ステージ][第3ステージ][第4ステージ]
　　　　　　　　　　：
という感じで，成長段階名をタグっぽく表して，それをクリックして移動するページで，初めて，
・教諭, 保育教諭
・指導教諭等, 主任保育教諭
・主幹教諭, 主任保育教諭
といった，属性が表示された方が，わかりやすいと思いました．

**Comment by Hidetaro7** [comment]
用語の整理

教員育成指標名 （例：管理職としての資質の向上に関する指標）
成長段階 （例：教員養成期, 0ステージ）
属性 （例：教諭, 保育教諭）

教員育成指標名というのが、現在Figmaである「教員向け」という対象を表しているのですが、これにあたると思いました、いただいたPDFの表の上に書いてあるタイトルなんですね。

**Comment by Hidetaro7** [comment]
ただ、ページを移動するとはじめて属性が見えるというのはページや操作が増えることにつながると思ったので今のようなページ構成にしたという意図がありますが、一番の問題は基本構造がよくわからない違和感ということでしょうか？ @horimasumi

**Comment by horimasumi** [comment]
ます，当初，「〇〇向け」としようと決めたのですが，「〇〇向け」とすると，堺市のように成長段階の下にも「〇〇向け」に準ずる内容が記載されているので，混乱すると思いました．
そこで，もう，ダイレクトに，各自治体の教員育成指標名を記載したほうがよいと思いました．

> 一番の問題は基本構造がよくわからない違和感ということでしょうか？

はい，その通りです．どうも，どこの自治体も

>自治体
→自治体で分けた教員育成指標
→成長段階
→指標項目

で，まず，それに準じて表現し，上記の構造に含まれていない情報を属性 （例：教諭, 保育教諭）として表現したほうがよいと思いました．

**Comment by horimasumi** [comment]
属性とするから，混乱しているような気がした．

**基本構造に含まれない情報**（例：教諭, 保育教諭）

と読んだ方がよいかも．

**Comment by Hidetaro7** [comment]
確かに、誰向けという意味が二つあるのが混乱しそうに感じているのはその通りだと思いました。

問題はそのうちの属性（基本構造に含まれない）によって遷移先のページが違うので、その先で属性の切り替えを行う事になる、もしくは間にページを挟むことになると思うのですが、その手間が発生するのは避けたいなと思っています。
（そのための構造が違和感なく伝わるようにできたら1ページにまとめたいという意図です）

**Comment by horimasumi** [comment]
>問題はそのうちの属性（基本構造に含まれない）によって遷移先のページが違うので、

今ご提示のページの遷移先のページの構造がよくわかっていないのかもしれません．どこをみたらよいですか？

**Comment by Hidetaro7** [comment]
すいません、。外出していまスマホから操作してまして、、😅

https://www.figma.com/proto/dCE06JShf29eqnvZ4vcE8U?node-id=26:83

ここから教員向けの充実・発展期を押してもらえますか？？

**Comment by Hidetaro7** [comment]
どうやら先程のurlだとトップページが表示されてしまいました。すいません。
教育委員会から探す、から、堺市教育委員会のリンクをクリックしてみていただけますか？

**Comment by Hidetaro7** [comment]
教育委員会
 → 教育育成指標の名称（サイトにあるものに準拠）
  → 育成段階
    → 指標項目（左側にあるセル）
    
これが一貫して、マニュアルにもデザインにも反映されて違和感なく見える必要がある、という話になった

**Comment by Hidetaro7** [comment]
まず、各ページのタイトルが上記の用語が用いられていることとして考えてみました。

○ 教育育成指標から育成段階を選ぶ
https://www.figma.com/file/dCE06JShf29eqnvZ4vcE8U/OKUTEP?node-id=26%3A83
↑
例えば「充実 ・ 発展期」が複数存在する場合、テーブルのセルを結合するルールを表示側で持たせると技術的には可能ではないかと思います。

○ 指標項目からバッジを選ぶ
https://www.figma.com/file/dCE06JShf29eqnvZ4vcE8U/OKUTEP?node-id=26%3A83
↑
成長段階のセルに「指導教諭等／主任保育教諭」が入っているのがまた混乱させるかもしれないと思いましたが、
文字サイズや色で補足であることを伝えることにしてみるなど考えてみました。（そもそも情報が表示されないことは考えられないので）

**Comment by dynamis** [comment]
ref: 育成指標リストの用意 https://github.com/npocccties/oku-private/issues/34

**Comment by Hidetaro7** [comment]
https://www.figma.com/file/dCE06JShf29eqnvZ4vcE8U/OKUTEP?node-id=26%3A83

指標項目に入っても成長段階を横断できる

**Comment by knokmki612** [comment]
見た目として検討できているように思うので完了します。別途気になることあればissueにしてもらえればと思います
