### ISSUE TITLE
docker-compose.production.yml で起動すると 502 Bad Gateway になる

### ISSUE THREAD

**Issue by ties-makimura** [npocccties/chiloportal#408]
#393 の流れの後，docker-compose.dev-server.yml で立ち上げていたコンテナを，  docker-compose.production.yml で再起動後ブラウザでアクセスすると， 502 Bad Gateway になります．

なにか準備が必要なのでしょうか．
.env の SSL_CERTS_DIR には，とりあえず docker-compose.dev-server.yml で生成されたlet's encryptに向けています．

**Comment by yoshinobu-etou-id** [comment]
backend のディレクトリで以下を行ってみてログに何が出ているか教えていただけますでしょうか。
`docker-compose logs https-portal
`

**Comment by yoshinobu-etou-id** [comment]
> .env の SSL_CERTS_DIR には，とりあえず docker-compose.dev-server.yml で生成されたlet's encryptに向けています．

上記ディレクトリには命名規則に従ったファイルはおいてますでしょうか？

**Comment by yoshinobu-etou-id** [comment]
> * 環境変数 `SSL_CERTS_DIR` のディレクトリにあらかじめ下記のファイルを配置してください
>   * `signed.crt`: サーバー証明書
>   * `domain.key`: サーバー証明書の秘密鍵

READMEからの抜粋です

**Comment by yoshinobu-etou-id** [comment]
https-portalのコンテナは下記にLet’Encryptから取得した証明書を格納します。

`ssl_certs/（ドメイン名）/production/
`

で、上記のディレクトリに以下が出力されますので、
それを chiloportal 以外のどこかに置き、そのディレクトリの絶対パスを`SSL_CERTS_DIR`に記載する、という感じです。

- signed.crt: サーバー証明書
- domain.key: サーバー証明書の秘密鍵

**Comment by ties-makimura** [comment]
原因： SSL_CERTS_DIR の指定先ミス
