### ISSUE TITLE
コンテナ再起動するとDB情報が消える

### ISSUE THREAD

**Issue by ties-makimura** [npocccties/chiloportal#409]
手順

1. 開発サーバー想定でデプロイ
2. 管理者作成
3. Django でログインして，Portal categorys に情報追加
4. 1で用意したenv yml そのままの指定で，コンテナ再起動 (server_restart.sh)
5. Djangoの管理者やPortal categorys に追加した情報が消えてる

**Comment by yoshinobu-etou-id** [comment]
以下のファイルは存在しますか？
`/var/chiloportal.dump`

**Comment by ties-makimura** [comment]
存在します．コンテナ再起動実行後，chiloportal.dumpの更新日時が更新されるのも確認しました．

**Comment by yoshinobu-etou-id** [comment]
> 3. Django でログインして，Portal categorys に情報追加

この時点で以下を実行し、`/var/chiloportal.dump` の日付が更新できているか確認してほしいです。
`server_db_backup.sh .envの絶対パス
`

**Comment by yoshinobu-etou-id** [comment]
上記が確認できたのち、以下を実行してみてください。
`server_db_restore.sh`

上記実行後、Djangoの管理画面の Portal categorys に追加したデータがあれば、リストアできている筈です。

**Comment by yoshinobu-etou-id** [comment]
先ず正常にコンテナが再起動できる状態になってからでないと、
どこに問題が発生しているか分からないので、他の issude で502エラーが発生している問題が片付いてから、
上記を再度確認してください。

**Comment by ties-makimura** [comment]
#408 502エラー問題解決した環境でテスト．


> Django でログインして，Portal categorys に情報追加
>> この時点で以下を実行し、/var/chiloportal.dump の日付が更新できているか確認してほしいです。
>> server_db_backup.sh .envの絶対パス

更新されていました

> 上記が確認できたのち、以下を実行してみてください。
> server_db_restore.sh

Djangoの管理画面の Portal categorys に追加したデータがありました．

---

上記環境の後，server_restart.sh を実行しましたが，
Djangoのログインできなくなり．Portal categorys に情報も空になっていました．

**Comment by yoshinobu-etou-id** [comment]
開発サーバーの方は特に問題なくDjangoの管理画面にログインできてますね。。。

**Comment by ties-makimura** [comment]
#429 や #432 の対応で解決
