### ISSUE TITLE
Docker Compose は V2 想定にする

### ISSUE THREAD

**Issue by ties-makimura** [npocccties/chiloportal#414]
関連：#376

Docker Compose  V2 の環境で動作しているよう開発しているのであれば，コードにあるコマンドも，`docker-compose `ではなく，`docker compose` にするなど，Docker Compose  V2 の仕様にする．

> Compose V2 で動作するようにおいおいしていくといいような気はしますが、このissueのスコーブ外としていいかと思いました（以前私の環境では Compose V2 に置き換えて動作確認したところイメージのビルドで落ちてしまったが想定環境ではないのでとくにレポートしていなかったです）

という意見もあったので，本当に Docker Compose V2 で動作するかは念のため確認しておいた方がよさそう．

**Comment by yoshinobu-etou-id** [comment]
メモ：
現状、docker-composeというように v1 仕様のコマンドの打ち方を前提とし、
各所でその記載を行っているが、v1 はそろそろサポートが終わるので、
docker compose というハイフンなしの v2 仕様にしておくべき。

**Comment by yoshinobu-etou-id** [comment]
v2 インストール手順：
```
# インストール先ディレクトリがなければつくる。説明を楽にするためにカレントディレクトリも変更
sudo mkdir -p /usr/local/libexec/docker/cli-plugins
cd /usr/local/libexec/docker/cli-plugins

# リリースモジュールをダウンロードし、docker-composeという名前でインストール先に保存
sudo curl -L https://github.com/docker/compose/releases/download/v2.6.1/docker-compose-linux-x86_64 -o docker-compose

# docker-composeを実行可能にする
sudo chmod +x docker-compose
```

動作確認：
`docker compose version
`

期待値 ※v2以上になっていればOK：
`Docker Compose version v2.6.1
`

**Comment by yoshinobu-etou-id** [comment]
v1 アンインストール手順：
`sudo yum remove docker-compose-plugin
`
もしくは
`which docker-compose
`で手動インストールされた v1 のモジュールを探し、削除

**Comment by yoshinobu-etou-id** [comment]
@ties-makimura 
#534 にて対応済みですので、makimura さんのテスト環境のサーバーでも v2 に移行されてください。

**Comment by ties-makimura** [comment]
V2 のみ環境で動作確認できました．
