### ISSUE TITLE
本番環境構築時のフロントエンド設定

### ISSUE THREAD

**Issue by ties-makimura** [npocccties/chiloportal#428]
deploy.sh の実行すると，コンテナに フロントエンド も立ち上がりますが，ここからどのようにフロントエンド設定を行えばいいのでしょうか．もしくは，deploy.sh 実行前に設定が必要でしょうか？

環境変数や静的コンテンツをどこかのタイミングで設定しなければならないかと思いますが，どのタイミングで行えばいいのかよく分かりません．

**Comment by yoshinobu-etou-id** [comment]
おおまかには以下の手順ですね。

1. デプロイ後にコンテナ経由でインポート
2. 再度デプロイ

インポートコマンド例はREADMEを参照してください。

**Comment by ties-makimura** [comment]
> 例えば以下のような感じです。

ありがとうございます，その辺りは[バックエンドの動作確認](https://github.com/npocccties/chiloportal/tree/develop/backend#%E5%8B%95%E4%BD%9C%E7%A2%BA%E8%AA%8D)で確認できていますので大丈夫です．

本件で悩んでいるのは，デプロイ後のフロントエンドの設定手順・タイミングが良く分からないです． 確認は @knokmki612 さんの方かな？
https://github.com/npocccties/chiloportal/tree/develop/frontend#frontend

**Comment by knokmki612** [comment]
> デプロイ後のフロントエンドの設定手順・タイミングが良く分からない

設定はデプロイ前におこなったものがビルド時に反映されます。ビルドは

- ローカル環境にて `corepack yarn build` したタイミング
- Docker イメージを作成したタイミング

でおこなわれます。

デプロイ後に環境変数値の変更、マークダウンファイルの編集等おこなった場合は再度ビルドとデプロイが必要です。

**Comment by yoshinobu-etou-id** [comment]
ちょっと横槍すみません。
`frontend/Dockerfile` ですが、環境変数が固定値になっているので、
.envファイルなどを `--env-file` オプションで渡した方がいいかと思いました。
特に `NEXT_PUBLIC_API_BASE_URL` は本番環境で変わると江藤は認識しているので。

以下参考です。
https://www.kabegiwablog.com/entry/2018/07/25/100000

**Comment by knokmki612** [comment]
Docker イメージではdotenvファイルは参照しておらず、 `--build-args` で指定してもらう想定です。
`docker build -t frontend --build-arg NEXT_PUBLIC_API_BASE_URL=<API のベースとなる URL> --build-arg NEXT_PUBLIC_MOODLE_DASHBOARD_URL=<Moodle ダッシュボードの URL> .`

https://github.com/npocccties/chiloportal/tree/develop/frontend#docker-%E7%92%B0%E5%A2%83

**Comment by knokmki612** [comment]
> 特に NEXT_PUBLIC_API_BASE_URL は本番環境で変わると江藤は認識しているので。

おっしゃるとおりです。デプロイ環境ごとに適切な値にする必要があるかと思います

**Comment by ties-makimura** [comment]
> Docker イメージではdotenvファイルは参照しておらず

バックエンドの方も対応して頂いたのですが，フロントエンドも参照するよう対応して欲しいです．

**Comment by knokmki612** [comment]
#437 にて --build-args 廃止、代わりに `.env` を必須としました。

**Comment by ties-makimura** [comment]
> #437 にて --build-args 廃止、代わりに `.env` を必須としました。

試しに， frontend/.env を配置して，
`NEXT_PUBLIC_MOODLE_DASHBOARD_URL=https://opedu.lib.osaka-kyoiku.ac.jp/my/aaaaa `
と設定した後，
docker build -t frontend .  を実行して，その後，deploy.sh を実行したのですが，サイトアクセスした後右上の「Moodleダッシュボード」のリンクは https://opedu.lib.osaka-kyoiku.ac.jp/my/ のままでした．まだ何か手順に問題あるでしょうか．．

**Comment by knokmki612** [comment]
> まだ何か手順に問題あるでしょうか．．

いえ、PRをまだマージしていないことが原因かと思います

**Comment by knokmki612** [comment]
マージしましたので改めてお試しいただければと思います

**Comment by knokmki612** [comment]
@ties-makimura デフォルト値なしとしているものは必ず .env に含めてください。（つまり NEXT_PUBLIC_API_BASE_URL も追加してください。）

**Comment by ties-makimura** [comment]
> マージしましたので改めてお試しいただければと思います

.env の設定は問題なく反映されました．
ただ，静的コンテンツはデプロイ時にファイルが戻ってしまいました．

この辺りの対応が必要そうに思えました．

- デプロイせずコンテナを再起動する処理（backend/server_restart.sh みたいなの）
- デプロイしても上書きされないよう本番用の静的コンテンツは分ける（リポジトリは ～.sample のように）

**Comment by yoshinobu-etou-id** [comment]
public/images なのでは？

**Comment by ties-makimura** [comment]
> 静的コンテンツと指しているものがなにかもう少し教えていただきたいです。

config.yaml などこの辺り．

https://github.com/npocccties/chiloportal/tree/develop/frontend#%E9%9D%99%E7%9A%84%E3%82%B3%E3%83%B3%E3%83%86%E3%83%B3%E3%83%84

**Comment by knokmki612** [comment]
> config.yaml などこの辺り．

git で管理する想定なので以下の行でおそらくリセットされているかと思います。

https://github.com/npocccties/chiloportal/blob/5ffe6fcb7b22aa4f2c51ad0187ce9d350b4d402f/deploy.sh#L3

もし git で管理しないということであれば gitignore に指定することはできますが、 config.yaml やマークダウンファイルは GitHub でバージョン管理しなくてよろしいのでしょうかね

**Comment by knokmki612** [comment]
> public/images なのでは？

public/images 配下が消えるのは意図していないです。.gitignore に指定されておりデプロイやローカルリポジトリの更新に関わらず保持される想定です。もし消えるとしたら別途課題に挙げた方が良さそうです。

**Comment by yoshinobu-etou-id** [comment]
public/images は .gitignore に入ってますね。見当違いでした。失礼いたしました。

**Comment by knokmki612** [comment]
いえ、問題なさそうでよかったです :pray:

**Comment by ties-makimura** [comment]
> config.yaml やマークダウンファイルは GitHub でバージョン管理しなくてよろしいのでしょうかね

デフォルトとしてはあっていいと思います．(.env.test や .env.development のように）
下地があった方が更新しやすいですし．

**Comment by knokmki612** [comment]
> デフォルトとしてはあっていいと思います．(.env.test や .env.development のように）
> 下地があった方が更新しやすいですし．

デプロイ先の環境で直接 config.yaml やマークダウンを編集し更新し続ける想定でしょうか？
だとすればやはりむしろ git で管理しないように変更したほうがいいですね（更新が何らかの拍子でリセットされてしまうので）

**Comment by knokmki612** [comment]
そうでないなら都度 GitHub リポジトリ条で更新して GitHub Actions 経由で本番デプロイするなどのほうがよさそうではあります（このあたり @dynamis さんからもなにか意見あればうかがいたいところです）

**Comment by ties-makimura** [comment]
> デプロイ先の環境で直接 config.yaml やマークダウンを編集し更新し続ける想定でしょうか？
だとすればやはりむしろ git で管理しないように変更したほうがいいですね（更新が何らかの拍子でリセットされてしまうので）

はい．

バックエンド・フロントエンドの構築確認をしていて，今の所，全体の運用イメージはこんな感じになればと妄想しました．意見欲しいです．

## 新規構築時

1. git clone https://github.com/npocccties/chiloportal.git
2. chiloportal/backend/.env 用意 (本番用)
3. chiloportal/frontend/.env や 静的コンテンツを用意 (本番用)
4. sudo chmod 755 chiloportal/deploy.sh
5. chiloportal/deploy.sh ( ← フロントエンドのdocker ビルドも実行）
※ 各 env  や 静的コンテンツがない場合は，停止 or デフォルト設定で実行

## バックエンド設定更新時

1. /backend/.env 更新
2. chiloportal/backend/server_restart.sh

## フロントエンド設定更新時

1. /frontend/.env や 静的コンテンツを更新
2. docker build -t frontend .
3. chiloportal/frontend/server_restart.sh

## システム更新時

1. chiloportal/deploy.sh

## バッジ追加

1. docker-compose exec app python /workspace/manage.py createsuperuser
2. Django ログイン
3. portal category 追加
4. docker-compose exec app python /workspace/manage.py import_badge --url={能力バッジを取得するURL} --pcid={ポータル独自カテゴリの主キー}

**Comment by yoshinobu-etou-id** [comment]
OKだと思います。

**Comment by knokmki612** [comment]
> > デプロイ先の環境で直接 config.yaml やマークダウンを編集し更新し続ける想定でしょうか？
> > だとすればやはりむしろ git で管理しないように変更したほうがいいですね（更新が何らかの拍子でリセットされてしまうので）
> 
> はい．

私からは改めての意見はないので、想定に合わせた対応として `posts/*.md` と `config.yaml` を git 管理対象外にする変更をおこなおうと思います

**Comment by knokmki612** [comment]
共有いただいた運用手順は本リポジトリにドキュメントとして配置されていると良さそうに思いました

**Comment by ties-makimura** [comment]
@knokmki612 元になるデータは消さずに残すようお願いします．
.env.development を .env に複製して利用するように，本番時は複製して利用したいです．

> chiloportal/frontend/.env や 静的コンテンツを用意 (本番用)

の詳細は，以下を行うイメージです．もし対象がなければ .development でビルドします．
*.development の方に，今用意進めている［静的ページ］などが入り，これらは git で管理します．

```
cp .env.development .env
cp config.yaml.development config.yaml
cp -r posts.development posts
cp -r contents.development contents
```

> chiloportal/deploy.sh ( ← フロントエンドのdocker ビルドも実行）
> chiloportal/frontend/server_restart.sh

運用イメージ通りでよければ，この辺りの準備もお願いすることになると思います．( @yoshinobu-etou-id さんの作業範囲もかかりますか？必要なら分担お願いします．）

**Comment by knokmki612** [comment]
> 元になるデータ

なくとも正常に動作するようにしましたが必要でしょうか？

**Comment by knokmki612** [comment]
> `cp -r contents.development contents`

contents/*.md についてはグローバルメニューに動線を組み込んでいる関係上、Git 管理対象外にせずそのままにしています。また、 `public/` ディレクトリに配置して contents/*.md から参照している画像もあります。

**Comment by knokmki612** [comment]
> もし対象がなければ .development でビルドします．
> *.development の方に，今用意進めている［静的ページ］などが入り，これらは git で管理します．

分かりました、Git 管理対象ディレクトリは通常別ファイル別ディレクトリに待避しており、ビルド時 `contents/*.md` `posts/*.md` `config.yaml` がなければ複製するようなnpmスクリプトを実装します

**Comment by ties-makimura** [comment]
> 分かりました、静的コンテンツ群（config.yaml、mdファイル）は通常別ファイル別ディレクトリに待避しており、ビルド時 contents/*.md posts/*.md config.yaml がなければ複製するようなnpmスクリプトを実装します

了解です．諸々出来ましたら確認します．

**Comment by dynamis** [comment]
next なんかの .env だと .env が全環境、xxx.development と xxx.production はそれぞれのモードでのデフォルト値、デプロイ先の環境毎に変えるような所はそれらを書き換えても良いが .env.local でオーバライドする仕様になってて、デフォルト値は git 管理だが .env.local だけは git 管理外でデプロイ時に作る的な運用がやりやすくなってますね。

config.yaml がなかった場合勝手に config.yaml.development からコピーされるという挙動はちょっと違和感がありました。
git 管理のデフォルト値と管理外の override で統一できると自然な気がします。

また、.env (.は隠しファイルである事を表すもので env に拡張子はない) と違って .yaml は拡張子であるので、.yaml.development という語順に違和感を感じました。rails では config/settings.yml の代わりに環境毎のは config/settings/development.yml などを作ってることも参考にするとディレクトリ掘るのは過剰でやらないとしても `config.development.yaml`, `config.production.yaml` というファイル名の方が自然に思います

docker なんかは docker-compose.yml を docker-compose.override.yml でオーバーライドしますがそれと同じ気持ちで。
https://docs.docker.jp/compose/extends.html production/development の区分では無く単にオーバーライドするだけならここでも config.yaml がデフォルト値で config.local.yaml なり config.override.yaml をデプロイ先固有の上書き値とする形でもよいかもです。

有名所ではないがググると https://github.com/dexidp/dex で config.dev.yaml や config.docker.yaml のようなファイル名を使っているケースとかもあるようで。

色々書きましたが、コピーして使うというのも結構あるシステムではあるが、.env.development 的なものに揃えるという意味であればどちらかというとオーバーライド系にするのと .yaml 拡張子は維持する名前が良さそう。あとは気分次第かと。

**Comment by knokmki612** [comment]
> 自動でコピーして起動する的なのはうっかりミス防止に避けた方が良さそう

コメントありがとうございます、個人的にもdevelopmet /production で参照先を切り替えるような形式のほうがよさそうな気がしました

**Comment by knokmki612** [comment]
議論の経緯見返しますと、記事にせよconfig.yamlにせよデフォルトのデータが存在しそれを上書きすることができるようにしたい、というニーズな気がしたので、 development / production というよりも overrides のようなディレクトリを切って、その配下に対応するデータがあればそれを参照するようにするのがよさそうな気がしました。

**Comment by knokmki612** [comment]
https://github.com/npocccties/chiloportal/issues/428#issuecomment-1298310242 時点から方針変えつつ対応したので、これでよさそうかまたフィードバックをお願いしたいです。 @ties-makimura 

以下が静的コンテンツの上書きに関するドキュメンテーションになりますので、それを参照しながら試してもらえればと思います。
https://github.com/npocccties/chiloportal/tree/develop/frontend#%E4%B8%8A%E6%9B%B8%E3%81%8D

**Comment by knokmki612** [comment]
不親切だったかもしれません。 bash のブレース展開の気持ちで書いていました。

参考 https://qiita.com/ine1127/items/6e5fe80f4a9c64509558

例えば以下のように echo すると以下のように出力されます。

```shell
$ echo {,overrides/}config.yaml
config.yaml overrides/config.yaml
```

**Comment by knokmki612** [comment]
ブレース展開は用いないかたちで見出しに反映しようかと思いました。

**Comment by ties-makimura** [comment]
すみません，機能ではないのですが，説明が不足しているように感じて確認しにくいです．
丁寧でなくてもいいので，制限やルールがあれば記載していただきますと助かります．

> {,overrides/}contents/*.md

こちらに配置するファイルは決まっていませんか？
例えば，about_site2.md というファイルを配置してビルド・デプロイしても，フッターなどには変化がなく何も反映されていないように見えます．

about_site2.md 
```
---
title: このサイトについて2
slug: about_site2
---
```
一応，URLで直接 /about_site2 に移動したら表示されました．使い道あるのかな（隠しページとか？）
機能としてはそのままでもいいですが，ドキュメントとしては説明不足だと感じました．

> {,overrides/}posts/*.md

- お知らせの並び順は何できまりますか？公開日でしょうか？仮にそうだとしたら公開日が同じ場合は何を見ますか？
- 公開日があるということは NEW などの表記もあるのでしょうか？
-  掲載数に上限はあるのでしょうか．

他にも recommendedWisdomBadgesIds や learningContents: にも表示上限数あるのかな？など，ドキュメント見ただけでは判断がつかず確認しずらかった．

**Comment by knokmki612** [comment]
> こちらに配置するファイルは決まっていませんか？

https://github.com/npocccties/chiloportal/issues/119 に対応するためのページ群です。したがって overrides に対応するmdファイルが存在しない場合、グローバルメニューから「コンセプト」ページなどアクセスしますと404の表示になります。

posts/\*.md とちがって配置されている mdファイルをもとに生成されたページの一覧を表示するような機能はないです。自分で動線を実装する必要があります。

> お知らせの並び順は何できまりますか？公開日でしょうか？仮にそうだとしたら公開日が同じ場合は何を見ますか？

公開日の想定です。公開日が未設定の場合1970-01-01とみなします。公開日が同じ場合は readdir 関数で取得される順になるかとおもいます。 https://man7.org/linux/man-pages/man3/readdir.3.html

> 公開日があるということは NEW などの表記もあるのでしょうか？

想定していないです。

> 掲載数に上限はあるのでしょうか．

上限ないです。

> 他にも recommendedWisdomBadgesIds や learningContents: にも表示上限数あるのかな？

上限ないです。

**Comment by knokmki612** [comment]
質問いただいた内容をドキュメントに追加しますね。

**Comment by knokmki612** [comment]
@ties-makimura 他に質問、不具合ありますでしょうか。適当なところで別途随時 issue に起票いただくのがよろしいかと思います。

**Comment by ties-makimura** [comment]
フロントエンド設定は理解できましたので本件はクローズします．
質問などはあるので別issueに起票しますね．
