### ISSUE TITLE
docker build -t frontend . を実行すると途中で処理が終了する

### ISSUE THREAD

**Issue by ties-makimura** [npocccties/chiloportal#435]
docker build -t frontend . を実行すると途中で The command '/bin/sh -c corepack yarn install --immutable' returned a non-zero
 が出て処理が終了します．

環境は，deploy.sh を実行してコンテナは立ち上がる状態．
deploy.sh 実行後，frontend ディレクトリに移動して `docker build -t frontend . `を実行すると以下ログが出て終了する．

```
➤ YN0013: │ emoji-regex@npm:9.2.2 can't be found in the cache and will be fetched from the remote registry
Killed
The command '/bin/sh -c corepack yarn install --immutable' returned a non-zero code: 137
```

**Comment by knokmki612** [comment]
> YN0013: │ emoji-regex@npm:9.2.2 can't be found in the cache and will be fetched from the remote registry

この行自体はパッケージのキャッシュが存在しないので取得しにいく旨のメッセージかと思います。（ローカル環境で `yarn install` していなければキャッシュが存在しないはずなのですべてのパッケージについて同様のメッセージが流れているはずです。）
プロセスがキルされている直接の原因のメッセージは別にある（もっと手前？）ような気がするのですがどうなんでしょう。

**Comment by ties-makimura** [comment]
メモリ不足していたのかもしれません．スワップ追加したら解消したのでとりあえずクローズしておきます．
（メモリ１GBの環境，2GBスワップ追加した）
