### ISSUE TITLE
環境変数のデバッグ機能の説明

### ISSUE THREAD

**Issue by ties-makimura** [npocccties/chiloportal#436]
バックエンドの[環境変数](https://github.com/npocccties/chiloportal/tree/develop/backend#%E7%92%B0%E5%A2%83%E5%A4%89%E6%95%B0) 説明で，

> DEBUG	デバッグ機能	デバッグ用で例外発生時のエラー内容が参照できるようになる
True: 有効 ※本番リリース用
False: 無効 ※動作確認用

とありますが，本番リリース用がTrueであっていますか？
後，LETS_ENCRYPT と比べて，True,False と true,false となっていますが問題なければそろえた方がよさそう．

**Comment by yoshinobu-etou-id** [comment]
逆になってましたので、修正しました。

バックエンドの[環境変数](https://github.com/npocccties/chiloportal/tree/develop/backend#%E7%92%B0%E5%A2%83%E5%A4%89%E6%95%B0) 説明で，

DEBUG デバッグ機能 デバッグ用で例外発生時のエラー内容が参照できるようになる
True: 有効 ※本番リリース用
False: 無効 ※動作確認用


> とありますが，本番リリース用がTrueであっていますか？
> 後，LETS_ENCRYPT と比べて，True,False と true,false となっていますが問題なければそろえた方がよさそう．

DEBUG は Python なのでTrue/False
LETS_ENCRYPT は bash sh なのでtrue/false

言語の違いで先頭一文字が大文字だったり小文字だったりするので、
そのようになっております。

差異吸収するとなると、冗長性のあふれるコードになりますが、
保守の観点から避けたいところです。

**Comment by yoshinobu-etou-id** [comment]
もしくは 0 とか 1 とかに置き換えるとかですかね。。

**Comment by yoshinobu-etou-id** [comment]
ただ、frontend はどうするの？という問題も出てくるので、
そのままにしておきたいところです。

**Comment by ties-makimura** [comment]
True/False にしないと駄目なのですね．了解です．
状況は分かりましたので本issueはクローズしておきます．
