### ISSUE TITLE
環境変数にあるSTAGE=production

### ISSUE THREAD

**Issue by ties-makimura** [npocccties/chiloportal#438]
バックエンドの envに STAGE=production がありますが，[環境変数の説明](https://github.com/npocccties/chiloportal/tree/develop/backend#%E7%92%B0%E5%A2%83%E5%A4%89%E6%95%B0)にはありません．こちらは必要でしょうか？
必要があれば説明を，なければ削除お願いします．

**Comment by yoshinobu-etou-id** [comment]
https-portalを各環境で使用していたときの名残りですね。
削除しておきました。
