### ISSUE TITLE
バックエンドAPIの認証について

### ISSUE THREAD

**Issue by yoshinobu-etou** [npocccties/chiloportal#45]
バックエンドAPIは公開サーバーに置く想定でしょうか？
もしそうであるならば、認証情報が必要ですが、何か想定されておりますでしょうか？
特になければ、djangoの管理機能でAPIキーを発行できるので、それを認証情報としてヘッダーに付与して頂こうと思います。

- キー名：Authorization
- 値：Api-Key {APIキーの値} ※Api-Keyの後ろは半角スペースを入れる

**Comment by knokmki612** [comment]
私はAPI認証をもうけること自体に異論ありませんが、当初の想定、ご意見など伺いたいです @dynamis @ties-makimura

**Comment by dynamis** [comment]
特定のフロントエンドサーバからのアクセスであれば Authorization HTTP リクエストヘッダによる Bearer 認証を予め発行したトークンでするだけでも事足りると思いますが、フロントエンドはクライアントブラウザで実行されブラウザからの直接 API リクエストになるので、API キー認証はそれを隠蔽できないので解決策にはなりません。LMS からの LTI ログインとかこちらでアカウント発行してログインとかを前提とできる場合は別ですが基本ログイン無しでポータルにアクセスしてくるので。

勿論書き込み系 API とかはシークレットキー/トークンによる認証をいれる＆間違ってもブラウザから呼び出さない対応が必要でしょうが、読み込み系 API については一応書き込みとは別の read 専用キーによる認証も一応入れるがそれは漏洩する前提 (あるいはそこはあまり本質的に意味はないと認証無しにする) として、アクセス元クライアント IP と時間あたりのアクセス制限での対応ではないでしょうか (github public api 等と同じ)。

もう少し本気でやるなら LMS 側のアカウントを持っており認証が出来るユーザだけアクセス制限を緩和しそれ以外の制限を強めにするといった対応 (これも github 等と同じ) もあり得ますが、今回そこまでする話じゃ無いと思います。

ユーザが増えてきたりしてサーバ負荷が高くなる場合も、どうせ殆どは同じ API 繰り返し呼んでるからリバースプロキシ挟んでみましょうという緩和策とかありますし、初期実装としてはシンプルな IP&回数制限を入れるだけで良いのではないかと。

**Comment by knokmki612** [comment]
https://github.com/npocccties/chiloportal/pull/163 にてバッグエンドAPI認証が取り除かれているように思うので
方針について整理できたとみなして完了
なにか他に議論したいことあれば別途issue立ててもらえればと思います
