### ISSUE TITLE
トップのカテゴリ文言の文字数をもとに文言を作成する

### ISSUE THREAD

**Issue by Hidetaro7** [npocccties/chiloportal#450]
<img width="596" alt="image" src="https://user-images.githubusercontent.com/281424/199414214-f1971a81-22c5-41a9-861b-edb29bc51982.png">

ここにあたる文字数は何文字がよいかについて、
厳密ではないが各項 60 文字程度でお願いします。

**Comment by knokmki612** [comment]
現状 30 文字で確認中

**Comment by horimasumi** [comment]
https://github.com/npocccties/oku-private/wiki/カテゴリの説明
 につくったので，クローズする．
