### ISSUE TITLE
インポートコマンドとフロントエンドのビルドを行うスクリプトを作成する

### ISSUE THREAD

**Issue by yoshinobu-etou-id** [npocccties/chiloportal#454]
* スクリプトには能力バッジの取得URL（バッジID含む）とポータル独自カテゴリIDを記載したCSVファイルを渡し、一括で登録してもらい、インポートコマンドに受け渡す。
* インポートコマンドで全てインポート後、画像をフロントエンドに反映するため、フロントエンドのビルドを合わせて行う。（引数でビルドの要否を指定したいが、デフォルトはビルドするようにしたい）

**Comment by yoshinobu-etou-id** [comment]
@ties-makimura 
`chiloportal/import.sh` を作成しておきました。
詳細は、下記の「8. 能力バッジのインポート」を参照願います。
https://github.com/npocccties/chiloportal/blob/develop/backend/README.md#%E7%92%B0%E5%A2%83%E6%A7%8B%E7%AF%89%E6%89%8B%E9%A0%86-1

**Comment by ties-makimura** [comment]
最初にURLを指定してしまうと，他のMoodleからもまとめて取得したい時にできないので，そこはCSVにまかせてはどうでしょうか．

以下イメージ．

コマンド例
`./import.sh /opt/test.csv`

インポートCSVファイル凡例
```
https://dev1-lms.oku.cccties.org/badges/badge_json.php?id=19,101
https://dev2-lms.oku.cccties.org/badges/badge_json.php?id=20,101
https://dev3-lms.oku.cccties.org/badges/badge_json.php?id=21,101
```

後，{フロントエンドのビルド指定} は何を指定すればいいでしょうか．例にある1のことでしょうか？
指定なしや 0 や 2だとどうなりますか．もう少し情報をください．

**Comment by ties-makimura** [comment]
frontend/build.sh ですが，例えばフロントエンドでconfig.yaml 等の設定を変更した後，直接 build.sh を実行するような，バッジインポート以外での利用をしても問題ない理解で大丈夫でしょうか．

**Comment by yoshinobu-etou-id** [comment]
> 最初にURLを指定してしまうと，他のMoodleからもまとめて取得したい時にできないので，そこはCSVにまかせてはどうでしょうか．

了解いたしました。修正しておきます。

> 後，{フロントエンドのビルド指定} は何を指定すればいいでしょうか．例にある1のことでしょうか？
> 指定なしや 0 や 2だとどうなりますか．もう少し情報をください．

すみません。記載漏れてましたので、追記しておきます。

> frontend/build.sh ですが，例えばフロントエンドでconfig.yaml 等の設定を変更した後，直接 build.sh を実行するような，バッジインポート以外での利用をしても問題ない理解で大丈夫でしょうか．

はい。ビルドしたいときに叩いてください。

**Comment by yoshinobu-etou-id** [comment]
@ties-makimura 
上記対応しましたので、ご確認をお願いいたします。

**Comment by ties-makimura** [comment]
> （引数でビルドの要否を指定したいが、デフォルトはビルドするようにしたい）

と決めたかと思いますので，` {フロントエンドのビルド指定（1: ビルドする, 1以外: ビルドしない）} `は意図にそっていないと思います．

- 指定なし：ビルドする
- 指定する：ビルドしない
でお願いします．

ビルドしない時の引数は，ビルドしないと明確にした値の方が分かるやすそうに思えます． `--no-build` とか
引数の値が間違えている時は，そのような引数はないとエラーメッセージ出して処理止めた方が，よくわからないまま処理すすめるより親切かも．

**Comment by yoshinobu-etou-id** [comment]
> と決めたかと思いますので，{フロントエンドのビルド指定（1: ビルドする, 1以外: ビルドしない）}は意図にそっていないと思います．

すみません。失念しておりました。

> ビルドしない時の引数は，ビルドしないと明確にした値の方が分かるやすそうに思えます． --no-build とか
> 引数の値が間違えている時は，そのような引数はないとエラーメッセージ出して処理止めた方が，よくわからないまま処理すすめるより親切かも．
> 

アドバイスいただき、ありがとうございます。
`--no-build` があればビルドしないようにいたします。

**Comment by yoshinobu-etou-id** [comment]
@ties-makimura 
以下をビルド有無の第2引数の値としました。（省略可）

- `--build`：ビルドする（デフォルト）
- `--no-build`：ビルドしない

**Comment by ties-makimura** [comment]
まだ作業中でしたらすみません．

1.  echo "${CSV_PATH} が存在しないため、処理継続できません。
というメッセージはでなかった．

```
$ ./import_badge.sh
使用方法
第1引数：CSVファイルのパス（絶対/相対）

CSVファイル書式：
能力バッジの取得URL,能力バッジの取得URLに引き渡すID,ポータル独自カテゴリID

CSVファイル凡例
https://dev-lms.oku.cccties.org/badges/badge_json.php,19,101
https://dev-lms.oku.cccties.org/badges/badge_json.php,20,101
https://dev-lms.oku.cccties.org/badges/badge_json.php,21,101

本スクリプトの使用例：
./import_badge.sh test.csv
```

2. CSVファイルですが，[↑で書いた例](https://github.com/npocccties/chiloportal/issues/454#issuecomment-1303049717)のように，取得するバッジのURLとidは分けないでください．これ以外の形式が出た場合に融通きかなくなります．

`https://dev-lms.oku.cccties.org/badges/badge_json.php,19,101`　
ではなく
`https://dev1-lms.oku.cccties.org/badges/badge_json.php?id=19,101`
とする

**Comment by yoshinobu-etou-id** [comment]
> echo "${CSV_PATH} が存在しないため、処理継続できません。
> というメッセージはでなかった．

相対パスだと、import_badge.sh のいるディレクトリからの相対パスとなりますので、
そこはご留意ください。（RAEDMEに注記を追記しておきます）
なお、絶対パスに適当なパスを与えると、上記のメッセージが表示されます。

> CSVファイルですが，https://github.com/npocccties/chiloportal/issues/454#issuecomment-1303049717のように，取得するバッジのURLとidは分けないでください．これ以外の形式が出た場合に融通きかなくなります．

確かに仰る通りですので、クエリパラメータを含んだURLとして修正しておきます。

> https://github.com/npocccties/chiloportal/blob/develop/backend/README.md#%E7%92%B0%E5%A2%83%E6%A7%8B%E7%AF%89%E6%89%8B%E9%A0%86-1
> の説明，import.sh でなく，import_badge.sh のミス

backend ディレクトリには import_badge.sh がいるので、
その説明を行うのが筋ですよね。
import.sh の説明ですが、とりあえず上位ディレクトリのREADMEに追記しておきますね。

**Comment by yoshinobu-etou-id** [comment]
@ties-makimura 
上記対応しておきましたので、ご確認をお願いいたします。
あと、以前、makimura さんが環境構築の手順をまとめてくださっていたので、
それを chiloportal のREADMEに転記しておきました。

**Comment by ties-makimura** [comment]
CSV２行指定しても，１行目しか処理されませんでした．

test.csv
```
https://dev-lms.oku.cccties.org/badges/badge_json.php?id=22,1
https://dev-lms.oku.cccties.org/badges/badge_json.php?id=23,1
```

import_result.csv
```
OK/NG,url,badge_json.php?id,portal_category.id,wisdom_badges.id
OK,https://dev-lms.oku.cccties.org/badges/badge_json.php?id=22,1,4
```

処理時のログ見ると １行目の値を繰り返し読み込んでいるように見えます

```
$ ./import.sh ../test.csv
./import.sh
/home/portal/chiloportal
../test.csv

./import_badge.sh
/home/portal/chiloportal/backend
CSV_PATH: /home/portal/chiloportal/../test.csv
https://dev-lms.oku.cccties.org/badges/badge_json.php?id=22,1
https://dev-lms.oku.cccties.org/badges/badge_json.php?id=22,1
------- Import start -------
```

後，import.sh があるということは，import_badge.shは不要になりますか？

**Comment by yoshinobu-etou-id** [comment]
CSVファイルのEOFが最終行にあると読み込めない不具合を修正しましたので、
ご確認をお願いいたします。

**Comment by ties-makimura** [comment]
#525 も確認．動作確認含め，気になる点は全て解消したと思います．
