### ISSUE TITLE
カテゴリの画像を表示する方法

### ISSUE THREAD

**Issue by ties-makimura** [npocccties/chiloportal#455]
以下方法だと，サイトを表示した時にカテゴリの画像が表示できません．どのようにするのが正しいのでしょうか．
ちなみに，Image url path に，登録済みのバッジ画像などを指定すると正しく表示されます．

1. portal category の  Image url path に test.png と入力
2. frontend/public/images/test.png を配置
3. フロントエンドを再ビルドする

**Comment by knokmki612** [comment]
想定としては `frontend/public/images` に配置されたのちビルドされた画像が参照されます

https://github.com/npocccties/chiloportal/blob/df52c28138830a65add234d36d96698b518aff63/frontend/components/PortalCategoryCard.tsx#L22

書いていただいた手順で問題ないように思うので今のところ原因が分からないです。

バックエンド開発サーバーにデータを入力されているということであれば、画像をいただければ私の方でも試せそうなのですがいかがでしょうか。

**Comment by ties-makimura** [comment]
すみません，解決しました．docker build -t frontend .　後，deploy.sh するの抜けていました．
deploy.sh したら反映されました．

#454 の時といい，どうもビルド後にコンテナ入れ替える作業が抜けてしまいますね．
基本1セットのはずなのでセットで動いて欲しい．．

**Comment by knokmki612** [comment]
解決したということでよかったです :+1:
