### ISSUE TITLE
その他のコンテンツの見た目の実装

### ISSUE THREAD

**Issue by knokmki612** [npocccties/chiloportal#468]
表示は見た目の検討から必要に思うので別途起票します。

_Originally posted by @knokmki612 in https://github.com/npocccties/chiloportal/issues/464#issuecomment-1302969578_

現状

- その他のコンテンツの名称
- その他のコンテンツの URL

は Figma にて考慮されているが

- その他のコンテンツの公開範囲
- その他のコンテンツの説明

は考慮されていないのでそれが確定したのち実装できたら完了

**Comment by horimasumi** [comment]
https://github.com/npocccties/chiloportal/issues/505
https://github.com/npocccties/chiloportal/issues/504
で，公開範囲，説明を定義した．
