### ISSUE TITLE
マークダウンファイルで利用できるマークダウンの種類

### ISSUE THREAD

**Issue by ties-makimura** [npocccties/chiloportal#472]
[フロントエンドで利用できるマークダウンファイル](https://github.com/npocccties/chiloportal/tree/develop/frontend#%E3%83%9E%E3%83%BC%E3%82%AF%E3%83%80%E3%82%A6%E3%83%B3%E3%83%95%E3%82%A1%E3%82%A4%E3%83%AB)で，段落や表，強調の指定は使えましたが，例えば画像を指定するとビルド時にエラーが出ます．利用できるマークダウンの種類は何ですか？

`![テスト](test2.png)`

```
Error occurred prerendering page "/posts/20221104-02". Read more: https://nextjs.org/docs/messages/prerender-error
Error: [next-mdx-remote] error compiling MDX:
ENOENT: no such file or directory, open '/app/publictest2.png'


More information: https://mdxjs.com/docs/troubleshooting-mdx
info  - Generating static pages (14/14)

> Build error occurred
Error: Export encountered errors on following paths:
        /posts/[slug]: /posts/20221104-02
    at /app/node_modules/next/dist/export/index.js:405:19
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async Span.traceAsyncFn (/app/node_modules/next/dist/trace/trace.js:79:20)
    at async /app/node_modules/next/dist/build/index.js:1263:21
    at async Span.traceAsyncFn (/app/node_modules/next/dist/trace/trace.js:79:20)
    at async /app/node_modules/next/dist/build/index.js:1123:17
    at async Span.traceAsyncFn (/app/node_modules/next/dist/trace/trace.js:79:20)
    at async Object.build [as default] (/app/node_modules/next/dist/build/index.js:64:29)
ERROR: "build:app" exited with 1.

```

なお，[静的ページの検討で画像貼り付けているページもあった](https://github.com/npocccties/oku-private/wiki/%EF%BC%BB%E9%9D%99%E7%9A%84%E3%83%9A%E3%83%BC%E3%82%B8%EF%BC%BD%E6%95%99%E6%9D%90%E3%81%AE%E8%91%97%E4%BD%9C%E6%A8%A9%E3%81%AB%E3%81%A4%E3%81%84%E3%81%A6)ので，画像は利用できないと問題ありそうです．

**Comment by ties-makimura** [comment]
追記

`![テスト](/top.png)` だと public ディレクトリにある画像が表示できた

`![テスト](https://www.cccties.org/wp/wp-content/themes/cccties/images/h_logo1.png)` のように外部URL指定するとビルド字にエラーがでた．

**Comment by knokmki612** [comment]
画像の参照そのものには対応しているかと思います。下記例:

https://github.com/npocccties/chiloportal/blob/develop/frontend/contents/concept.md?plain=1#L10

現状マークダウンファイルで使用する画像は必ず `/public/` 配下から参照する想定です（外部 URL は想定外）

> 利用できるマークダウンの種類

GitHub Flavored Markdown の remark 実装です。

https://github.com/npocccties/chiloportal/blob/49f0ef969e7b5af6cebdff247043c15a02ed88b9/frontend/pages/%5Bslug%5D.tsx#L35-L40

**Comment by ties-makimura** [comment]
> （外部 URL は想定外）
> GitHub Flavored Markdown の remark 実装です。

了解です．画像について，もし外部URLが必要なら別途起票します．
