### ISSUE TITLE
クライテリアの種類の画像のグラフィック作成

### ISSUE THREAD

**Issue by knokmki612** [npocccties/chiloportal#483]
Figma https://www.figma.com/file/dCE06JShf29eqnvZ4vcE8U?node-id=26:84#298097322

![image](https://user-images.githubusercontent.com/9744580/199925912-e2c1a0f4-0d44-4011-8d4d-db1e71325f90.png)

> こちらでアイコンのトーンを揃えて、お渡し、moodleをこちらのアイコンにあわせてもらう。

**Comment by knokmki612** [comment]
ベクターグラフィックとして作成するとよりよい件については #482

**Comment by Hidetaro7** [comment]
<img width="653" alt="image" src="https://user-images.githubusercontent.com/281424/201844954-70cef3dc-0e4d-487a-95c0-103d9272fd3d.png">

https://www.figma.com/file/dCE06JShf29eqnvZ4vcE8U/OKUTEP?node-id=26%3A83&t=g5CYL0YbaIDVgHir-1

それぞれのグラフィックを作成しました。
https://github.com/npocccties/chiloportal/issues/452 のやりとりをもとに、
Material Design Icons による SVG 画像を Figma上に保存しています。
@horimasumi  @knokmki612

**Comment by horimasumi** [comment]
一度，このアイコンをMoodleにも入れて，確認したいです．
＞ @ties-makimura くん，よろしく．

**Comment by ties-makimura** [comment]
Moodle にも適応，問題があれば別途起票します．
