### ISSUE TITLE
知識バッジのイラレデータ作成

### ISSUE THREAD

**Issue by knokmki612** [npocccties/chiloportal#484]
Figma https://www.figma.com/file/dCE06JShf29eqnvZ4vcE8U?node-id=26:84#298102379

![image](https://user-images.githubusercontent.com/9744580/199928177-8fa865a5-cd19-41b0-8411-190a109f4b2c.png)

> イラレデータとして用意する
> - ルール
> - サンプル
> （例）
> [https://opedu.lib.osaka-kyoiku.ac.jp/course/view.php?id=62&section=](https://www.figma.com/exit?url=https%3A%2F%2Fopedu.lib.osaka-kyoiku.ac.jp%2Fcourse%2Fview.php%3Fid%3D62%26section%3D4)

**Comment by Hidetaro7** [comment]
使える書体も指定したいと思います。
オープンソースで提供されているフォントを検討しています。 @ties-makimura

**Comment by Hidetaro7** [comment]
@ties-makimura 大阪教育大学のロゴなどが入った状態のイメージを作ったほうが作業しやすいと思うので、
大阪教育大学のロゴのイラレ版があったら提供していただけますか？

**Comment by knokmki612** [comment]
> Material Design Icons も同様の認識 https://materialdesignicons.com/
> 
> Material Design Icons は Iconify でも使用可能ですね。 https://icon-sets.iconify.design/mdi/
> 

_Originally posted by @knokmki612 in https://github.com/npocccties/chiloportal/issues/452#issuecomment-1300209718_

こういった背景から Material Design Icons をグラフィックに使用する

**Comment by ties-makimura** [comment]
> @ties-makimura 大阪教育大学のロゴなどが入った状態のイメージを作ったほうが作業しやすいと思うので、
大阪教育大学のロゴのイラレ版があったら提供していただけますか？

@Hidetaro7 ロゴの透過PNGと利用マニュアルを頂きました．イラレ版も必要であれば確認します．
https://github.com/npocccties/oku-private/tree/main/docs/%E3%83%87%E3%82%B6%E3%82%A4%E3%83%B3/%E5%A4%A7%E9%98%AA%E6%95%99%E8%82%B2%E5%A4%A7%E5%AD%A6%E3%83%AD%E3%82%B4

**Comment by Hidetaro7** [comment]
次回の対応として別途契約のなかで進めさせていただくことになりました。
一旦現状のイラストレーターデータをお渡しする。

**Comment by Hidetaro7** [comment]
お渡し済みとなります。
https://github.com/npocccties/oku-private/blob/main/docs/%E3%83%87%E3%82%B6%E3%82%A4%E3%83%B3/OKUTEP_badge_design_format.ai

**Comment by knokmki612** [comment]
> 次回の対応として別途契約のなかで進めさせていただく

残課題として Backlog に残しておくとのことだったので Reopen しておきます。認識異なっていればあらためてクローズしてください。 @horimasumi

**Comment by horimasumi** [comment]
あってます！

**Comment by knokmki612** [comment]
@Hidetaro7 現在の状況としてはいかがでしょうか。仮ではなく正式なガイドラインに沿って作成したグラフィックデータを共有済みであるとしたら、完了にできるかと思いました。

**Comment by Hidetaro7** [comment]
バッジのグラフィックに関してはfixしたと相互認識しています。
Adobe Illustrator 形式のデータで、サンプルとガイドラインの作成を行って提供したので本件はクローズとします。
