### ISSUE TITLE
その他のコンテンツに入力する URL

### ISSUE THREAD

**Issue by knokmki612** [npocccties/chiloportal#488]
Figma https://www.figma.com/file/dCE06JShf29eqnvZ4vcE8U?node-id=121:1583#264637324

![image](https://user-images.githubusercontent.com/9744580/199930308-ca681795-7055-4262-b1fe-b9dd4daad6a0.png)

> https://opedu.lib.osaka-kyoiku.ac.jp/course/index.php?categoryid=18
> 
> ---
> 
> https://opedu.lib.osaka-kyoiku.ac.jp/?redirect=0
> 
> 社会教育主事講習
> 
> 教材

**Comment by ties-makimura** [comment]
その他のコンテンツに入力する URLは， config.yaml で自由に決めれる状態なのでクローズ
