### ISSUE TITLE
グローバルメニューにおける コンセプト→OKUTEPについて

### ISSUE THREAD

**Issue by knokmki612** [npocccties/chiloportal#489]
Figma https://www.figma.com/file/dCE06JShf29eqnvZ4vcE8U?node-id=121:1583#299067122

![image](https://user-images.githubusercontent.com/9744580/199931078-de31de5d-3da9-4df2-8de4-6d6a1c667625.png)

> OKUTEPについて　に変更 Hideki Akiba
> 
> ---
> 
> この場合、このサイトについてというページは廃止という認識であってますでしょうか？

**Comment by knokmki612** [comment]
秋葉さんによる見た目の検討が必要に思うのでアサインします

**Comment by knokmki612** [comment]
実装への反映が必要に思うので自身をアサインします

**Comment by Hidetaro7** [comment]
Figmaにて反映
