### ISSUE TITLE
グローバルメニューにおける 教材の著作権について の追加

### ISSUE THREAD

**Issue by knokmki612** [npocccties/chiloportal#490]
Figma https://www.figma.com/file/dCE06JShf29eqnvZ4vcE8U?node-id=121:1583#299067501

![image](https://user-images.githubusercontent.com/9744580/199931441-f2bf3ba6-78f3-4632-8632-1210478cacaa.png)

> 教材の著作権について
> の追加 Hideki Akiba

**Comment by knokmki612** [comment]
秋葉さんによる見た目の検討が必要に思うのでアサインします

**Comment by knokmki612** [comment]
実装への反映が必要に思うので自身をアサインします

**Comment by Hidetaro7** [comment]
コンポーネントで用意

![Image](https://user-images.githubusercontent.com/281424/200775642-de4a890f-350a-43e7-9e0d-f8440e520f22.png)


ヘッダにも追加が必要だと思う

![Image](https://user-images.githubusercontent.com/281424/200775714-e92c77c1-154a-4065-a494-df425e81ab57.png)


@knokmki612
