### ISSUE TITLE
運営元情報とお問合せの違い

### ISSUE THREAD

**Issue by knokmki612** [npocccties/chiloportal#491]
Figma https://www.figma.com/file/dCE06JShf29eqnvZ4vcE8U?node-id=121:1583#299066973

![image](https://user-images.githubusercontent.com/9744580/199931834-06cccd5d-0749-4ef5-b5c1-2ad35215fab9.png)

> 運営元情報とお問合せの違いはなにでしょうか
> Hideki Akiba

**Comment by ties-makimura** [comment]
違いは以下の通り．

- 運営元情報：このポータルサイトの運営元が誰であるかに関する説明 #129 で対応する 
- お問い合わせ：メールでのお問い合わせ #514 で対応する
