### ISSUE TITLE
バッジを選択し，獲得し，活用するということが主体的な学びであることの反映

### ISSUE THREAD

**Issue by knokmki612** [npocccties/chiloportal#493]
Figma https://www.figma.com/file/dCE06JShf29eqnvZ4vcE8U?node-id=737:6502#299032803

![image](https://user-images.githubusercontent.com/9744580/199932606-6e60578d-623a-4bf6-8e60-ca807f63ef92.png)

> バッジを選択し，獲得し，活用するということが主体的な学びであることがもう少しわかるようにしてほしい．Hideki Akiba

**Comment by knokmki612** [comment]
秋葉さんによる見た目の検討が必要に思うのでアサインします

**Comment by knokmki612** [comment]
実装への反映が必要に思うので自身をアサインします

**Comment by Hidetaro7** [comment]
主体的、という言葉はむしろ全体に関わる考えになるので、図でそれをどう示すかを考えて作成してみる

**Comment by Hidetaro7** [comment]
![image](https://user-images.githubusercontent.com/281424/201834546-fffbc45c-b2b4-4311-913c-0e72eb08e8c6.png)

全体を通じて伝えたい「主体的な学び」「学習成果」を同じような重要度にすると、こう分けることになるのかとも考えましたが、ただ、分けて書くより「主体的な学びによる学習成果」とまとめてしまったほうがいいのか、思案中です。
少しご意見などいただけたらと思います。 @horimasumi

**Comment by horimasumi** [comment]
上の図のほうが，「主体的」が強調されて，よいと思いました．ただ，そうなるとウェルビーイングの丸い矢印とぶつかる（流れない）ので，主体的の矢印が逆向にしても，よいのかなあ．
下の矢印の「学習成果」を「学習成果の活用」にして，ウェルビーイングが主体的な学びになって，学習者にもどってくる，というのはいかがでしょうか．

**Comment by Hidetaro7** [comment]
サイクルが生まれる、という意味でよいかもしれませんね、もう少し練ってみます。 @horimasumi

**Comment by Hidetaro7** [comment]
<img width="1272" alt="image" src="https://user-images.githubusercontent.com/281424/202962625-7452d604-a93d-48a1-a402-d2eac04eb231.png">

以前の右側にあった丸い矢印は、ウェルビーイングが循環していくようにしたいという思いがあったのですが、
これを形成するのは学習成果の活用と主体的な学びによって循環される、という図に示してみました。

図が混雑しそうだったので、余分な装飾（丸囲みの線やフキダシ）は取り除いて、伝えたい内容を絞って少しシンプルにしています。

ご意見などお聞かせいただけたらと思います。 @horimasumi

**Comment by Hidetaro7** [comment]
こちら、Figmaにて提出しているので、一度 @horimasumi さんにボールをお渡ししますね。

**Comment by horimasumi** [comment]
以下で実装をお願いします．

![](https://user-images.githubusercontent.com/281424/202962625-7452d604-a93d-48a1-a402-d2eac04eb231.png)

**Comment by Hidetaro7** [comment]
@horimasumi @knokmki612 モバイルだともう少し横を詰めないと全体が小さくなるので、モバイル用の画像を作成しました。
双方の観点からご指摘あればください。なければそのまま実装に進んでいただこうと思います。

<img width="1321" alt="image" src="https://user-images.githubusercontent.com/281424/203758074-5e040937-76b9-4ee8-bf0d-18df15028d42.png">

Figma で用意しています。
https://www.figma.com/file/dCE06JShf29eqnvZ4vcE8U/OKUTEP?node-id=731%3A6806&t=NkxsZGgKlRprKVbI-1

**Comment by horimasumi** [comment]
デザインとしては，これで進めていただいて，結構です．よろしくお願いします．
