### ISSUE TITLE
トップビジュアルの検討

### ISSUE THREAD

**Issue by knokmki612** [npocccties/chiloportal#494]
Figma https://www.figma.com/file/dCE06JShf29eqnvZ4vcE8U?node-id=737:6502#295289819

![image](https://user-images.githubusercontent.com/9744580/199932970-b5e653b1-e973-4f7d-bb39-4798c25d244c.png)

> トップビジュアルを作成しました。
> あまり濃くない臙脂色を採用してメッセージが伝わりやすいように、あまりイラストが強すぎないようなトーンにしてみました。ご確認ください。 Masumi Hori
> 
> ---
> 
> 「選ぶ」→科目を選ぶ
> にしてみて下さい．
> 「自身の実感，周りの承認」
> 学習成果に対して，
> 自身が実感し，周りが承認するのですが，「学習成果」に対してというのが図かなにかで，わかるようにならないですかねえ・・・
> 
> ---
> 
> 図はドラフトですが
> 
> （上） 学習成果に実感と承認が得られる
> （下） 実感と承認を得られるプロセスに学習成果が身につく
> 
> このあたりで議論できたらと思います。細かい見せ方はもっと詰めます。 Masumi Hori
>

**Comment by ties-makimura** [comment]
検討段階は終了済み．
#493 で次の話をしている．
