### ISSUE TITLE
おすすめのバッジ周辺のライティング

### ISSUE THREAD

**Issue by knokmki612** [npocccties/chiloportal#496]
Figma https://www.figma.com/file/dCE06JShf29eqnvZ4vcE8U?node-id=737:6502#299019399

![image](https://user-images.githubusercontent.com/9744580/199934636-b094cd18-bbb4-4dd0-9a19-8a5af6ce2115.png)

> このトピックの前に，
> マイクロコンテンツ
> →知識バッジ
> →能力バッジ　←←活用できるのはこれ
> の説明があり，じゃあ，試しに受講してみる．
> みたいにできないでしょうか．Hideki Akiba

**Comment by horimasumi** [comment]
これが，実現したら，
https://github.com/npocccties/chiloportal/issues/125
が解決する

**Comment by knokmki612** [comment]
秋葉さんによる見た目の検討が必要に思うのでアサインします

**Comment by knokmki612** [comment]
実装への反映が必要に思うので自身をアサインします

**Comment by Hidetaro7** [comment]
「能力バッジとは？」という静的ページを作成して、そのテキストリンクが必要になる。
Figma上でテキストリンクがどこに配置されるかが明示される必要がある。

**Comment by Hidetaro7** [comment]
![Image](https://user-images.githubusercontent.com/281424/200769143-b7a55cb8-a47f-4216-a78e-bde3844881bf.png)



![Image](https://user-images.githubusercontent.com/281424/200769157-5ea82d5b-15f0-4d2b-9c50-6244e1284cd5.png)



![Image](https://user-images.githubusercontent.com/281424/200769197-ae093761-e35c-4d56-a13f-6c82d9d2c37c.png)


トップページに3箇所配置でお願いします。
 @knokmki612

**Comment by Hidetaro7** [comment]
テキストにhoverしたときに下線があったほうがいいです。

**Comment by knokmki612** [comment]
> 「能力バッジとは？」という静的ページを作成して、そのテキストリンクが必要になる。 Figma上でテキストリンクがどこに配置されるかが明示される必要がある。

この件は https://github.com/npocccties/chiloportal/issues/503 https://github.com/npocccties/chiloportal/issues/497 など多岐にわたり影響ある変更なように思いました。このissueの変更に合わせてそれらの箇所に「能力バッジとは？」のリンクを追加する作業をおこないます。
