### ISSUE TITLE
カテゴリの順番

### ISSUE THREAD

**Issue by knokmki612** [npocccties/chiloportal#500]
Figma https://www.figma.com/file/dCE06JShf29eqnvZ4vcE8U?node-id=737:6502#299020734

![image](https://user-images.githubusercontent.com/9744580/199935646-33bb4430-3a21-41ad-b9d4-9f1032e04e9c.png)

> カテゴリの順番を以下の通りに変更する．
> ・授業づくり​
> ・教科等指導力​
> ・子ども・人理解　​
> ・教員としての​基本的資質​
> ・協働​
> ・人材の育成​
> ・現代的課題​ Hideki Akiba
> 
> ---
> 
> おそらく実装としてはDBに登録された順番に依存します。
> 
> ---
> 
> 並びは変更しましたが、教科等指導力​については画像の差し替えが必要なためそのままにしています。

**Comment by knokmki612** [comment]
@ties-makimura @horimasumi こちらのissueについて実装に関してはバックエンドの確認が必要という認識です

**Comment by knokmki612** [comment]
Figmaの変更について対応が必要に思うので秋葉さんをアサインします

**Comment by yoshinobu-etou-id** [comment]
@knokmki612 
対応が決まりましたら、江藤までご一報くださいませ。

**Comment by knokmki612** [comment]
ありがとうございます、経緯を補足いたします @yoshinobu-etou-id 
ポータルカテゴリーの順序をコントロールしたいというニーズがあることが判明したので、

1. 現状で順序をコントロールすることは可能か否か
2. 可能な場合はその方法

についてまずは確認が必要、という話になりました（ @ties-makimura @horimasumi 認識に相違あれば指摘いただければと ）

**Comment by yoshinobu-etou-id** [comment]
> カテゴリの順番を以下の通りに変更する．
> ・授業づくり​
> ・教科等指導力​
> ・子ども・人理解　​
> ・教員としての​基本的資質​
> ・協働​
> ・人材の育成​
> ・現代的課題​ Hideki Akiba

ポータルカテゴリの順序を上記に変更するとなると、
フロントかバックエンドかのどちらかで行うしかないのですが、
バックエンドとしてはクエリ結果に対して上記の順で並べ替える処理を入れるくらいであり、
作業量としては軽微なものなのでバックエンドとしては問題ありませんが、いかがでしょうか。
上記の並び順は環境変数で持たせておきたいところです。

**Comment by knokmki612** [comment]
> バックエンドとしてはクエリ結果に対して上記の順で並べ替える処理を入れるくらい

フロントエンドで対応する場合も、クエリ結果→APIレスポンスと読み替えていただければよろしいかと思います
しいていえば並べ替えの処理は現状フロントエンドで管理しているマークダウンファイルぐらいでしかおこなっていないので、引き続きしないですむのであればシンプルだなという印象ではあります

**Comment by yoshinobu-etou-id** [comment]
確かにフロントエンドでも並べ替えは可能ですね。

両者のコストが変わらない＆大したコストでもないのであれば、
フロントエンドがシンプルになる利点をとりあげて、
バックエンドに並べ替えを入れた方が良さそうです。

ということで対応しておきます。

**Comment by yoshinobu-etou-id** [comment]
#536 にて対応しておきました。

**Comment by yoshinobu-etou-id** [comment]
環境変数の定義例：
`PORTAL_CATEGORY_SORT_ORDER=授業づくり,教科等指導力,子ども・人理解,教員としての基本的資質,協働,人材の育成,現代的課題
`

**Comment by ties-makimura** [comment]
> PORTAL_CATEGORY_SORT_ORDER=授業づくり,教科等指導力,子ども・人理解,教員としての基本的資質,協働,人材の育成,現代的課題

気になったのですが，カテゴリIDではなく名前を指定する方がいいのでしょうか？
DBで名前を変更すると，環境変数も更新が必要になるように思えたので．（じゃあカテゴリIDなら分かりやすいかはおいておいて）

**Comment by yoshinobu-etou-id** [comment]
運用しやすい方に傾けますが、いかがでしょうか？

**Comment by yoshinobu-etou-id** [comment]
DBの更新頻度が高いようであればIDを指定すべきでしょうが、
既に固まっているならば名前指定の方が可読性が良いと思います。
とはいえ、予定は未定なので、無難にIDで指定しておいた方がいいかもしれません。

**Comment by yoshinobu-etou-id** [comment]
ただ、portal_category にデータを登録してから、
そのIDを調べて、環境変数に転記するという手間があるので、
初期のコストが結構かかりそうな気がしました。

**Comment by yoshinobu-etou-id** [comment]
環境変数をIDとした場合、説明欄に上記の手順やコンテナの再起動を忘れないでね、
という記載が必要となるので、冗長な感じがしてきました。

**Comment by ties-makimura** [comment]
portal_category には sort key があると思うのですが，これは用途としては違うのでしょうか？
https://github.com/npocccties/chiloportal/blob/develop/backend/sql/create_table.sql#L18

**Comment by yoshinobu-etou-id** [comment]
今のところ sort_key は特に制御では使用していないです。
それを使用するということでしょうか？

**Comment by yoshinobu-etou-id** [comment]
他にも sort_key が存在するテーブルがありますが、これらの扱いはいかがしましょうか？
* criteria
* framework
* stage
* field

**Comment by ties-makimura** [comment]
portal_category 含め，その辺りの sort_key は何か必要になった際に使おうということで残していたかと思います．
カテゴリについては，まさに今必要になったので，この sort_key  を利用してみてはと思いました．

**Comment by yoshinobu-etou-id** [comment]
了解しました。
portal_category は sort_key を使用したほうがシンプルに実装できると思いますし、
確実に並び順を指定できるので、sort_key で実装すべきかと思いました。

**Comment by yoshinobu-etou-id** [comment]
@ties-makimura 
#539 で sort_key に対応しましたので、ご確認をお願いいたします。

**Comment by Hidetaro7** [comment]
今見て気づいたのですが、`教科等指導力` が新しく追加になっているように見えます。
バッジのグラフィックがないので必要なら作成する必要があります。これは必要になりますか？ @horimasumi

**Comment by horimasumi** [comment]
あ，そうですね．7個です．
バッジのカテゴリは初期のころから変更してないはずで，
　https://github.com/npocccties/oku-private/blob/main/docs/バッジマップの整理/バッジマップの整理V3.xlsx
Figmaと多少誤差があるのは，サンプルだからかなあ，ぐらい思って，ちゃんとチェックしておりませんでした．すいません．

なお，最新版は
https://github.com/npocccties/oku-private/blob/main/docs/バッジマップの整理/バッジマップの整理V4.xlsx
ですが，カテゴリは変更されていません．

**Comment by Hidetaro7** [comment]
Figma上では反映済みで、「教科書指導力」のグラフィックも新規作成できたので、担当から外れます。
起票した @knokmki612 をアサインします。

**Comment by knokmki612** [comment]
このissueについて残件ないという認識です
あれば別途起票もしくはリオープンしてください
