### ISSUE TITLE
教員育成指標の説明の追加

### ISSUE THREAD

**Issue by knokmki612** [npocccties/chiloportal#503]
Figma https://www.figma.com/file/dCE06JShf29eqnvZ4vcE8U?node-id=737:6502#299027430

![image](https://user-images.githubusercontent.com/9744580/199936447-381d9983-0c08-4b50-a41e-d724d689fedd.png)

> 教員育成指標の説明として以下の文章を追加して下さい．
> 
> 教員育成指標とは
> 地域の教育委員会が，教員に求められる資質や能力を，キャリア（経験年数）毎に明確にしたものです．Hideki Akiba

**Comment by knokmki612** [comment]
秋葉さんによる見た目の検討が必要に思うのでアサインします

**Comment by knokmki612** [comment]
実装への反映が必要に思うので自身をアサインします

**Comment by Hidetaro7** [comment]
@knokmki612 Figma反映済み

![Image](https://user-images.githubusercontent.com/281424/200771804-30b45a51-b21d-432a-8b37-7626a7f8daf3.png)
