### ISSUE TITLE
その他のコンテンツ「オープン教材」の説明の追加

### ISSUE THREAD

**Issue by knokmki612** [npocccties/chiloportal#504]
Figma https://www.figma.com/file/dCE06JShf29eqnvZ4vcE8U?node-id=737:6502#299029773

![image](https://user-images.githubusercontent.com/9744580/199936876-b10de3ea-503b-4e56-a8ee-18097733f165.png)

> 「オープン教材」に以下の説明を追加して下さい．
> Hideki Akiba
> 大人から子どもまで，誰でも学習できる学習教材です．学校の授業教材としても，ご利用頂けます．

**Comment by knokmki612** [comment]
見た目の検討が必要に思うので秋葉さんアサインします

**Comment by knokmki612** [comment]
実装への反映が必要に思うので自身をアサインします

**Comment by Hidetaro7** [comment]
2つのボタンは高さも揃えてほしい @knokmki612 

![Image](https://user-images.githubusercontent.com/281424/200771196-27b9fb56-a944-4672-b1cc-f870bab01151.png)

**Comment by horimasumi** [comment]
デザインはこれでOKですが，
「社会主導主事講習」について，
タイトル，文中とも「社会教育主事講習」に変更お願いします．　
@Hidetaro7
