### ISSUE TITLE
その他のコンテンツ「社会教育主事講習」の説明の追加

### ISSUE THREAD

**Issue by knokmki612** [npocccties/chiloportal#505]
Figma https://www.figma.com/file/dCE06JShf29eqnvZ4vcE8U?node-id=737:6502#299030747

![image](https://user-images.githubusercontent.com/9744580/199937457-11e7c9c9-ae49-4210-9798-7dccd59f6aae.png)

> ・社会主導主事講習
> 　→社会教育主事講習
> 
> ・オープンではない事を示す鍵のようなアイコンをつけて下さい．
> 
> ・以下の説明を加えて下さい．
> 大阪教育大学が令和4年度に開講した社会主事講習のオンデマンド教材です．受講者限定教材となっています．Hideki Akiba

**Comment by knokmki612** [comment]
見た目の検討が必要に思うので秋葉さんアサインします

**Comment by knokmki612** [comment]
実装への反映が必要に思うので自身をアサインします

**Comment by Hidetaro7** [comment]
> オープンではない事を示す鍵のようなアイコンをつけて下さい

--- 

教育主導主事講習
（受講者限定教材）

大阪教育大学が令和4年度に開講した社会主事講習のオンデマンド教材です。

**Comment by Hidetaro7** [comment]
Figma反映済み @knokmki612 

![Image](https://user-images.githubusercontent.com/281424/200770609-37653180-c5fb-4ce0-b0a8-85ef870a2cdc.png)
