### ISSUE TITLE
認定している教育委員会が存在しない場合の認定している教育委員会一覧ダイアログの見た目

### ISSUE THREAD

**Issue by knokmki612** [npocccties/chiloportal#511]
参考 https://dev-portal.oku.cccties.org/wisdom_badges/202

現状ローディングサークルが出続ける状態になっているので見た目を考慮する必要があるように思う

**Comment by knokmki612** [comment]
見た目の検討が必要に思うので秋葉さんアサインします

**Comment by knokmki612** [comment]
実装への反映が必要に思うので自身をアサインします

**Comment by Hidetaro7** [comment]
認定している教育委員会は今のところありません。

**Comment by Hidetaro7** [comment]
Figma 反映済み、原則スタイルは現在実装中のスタイルを応用してもらえたらOK @knokmki612 

![Image](https://user-images.githubusercontent.com/281424/200773309-eaa44632-cf2c-4eb0-8c63-3c313ff88132.png)
