### ISSUE TITLE
［静的ページ］お問い合わせ

### ISSUE THREAD

**Issue by ties-makimura** [npocccties/chiloportal#514]
#131 より 静的ページを用意する

**Comment by knokmki612** [comment]
https://github.com/npocccties/oku-private/wiki/%EF%BC%BB%E9%9D%99%E7%9A%84%E3%83%9A%E3%83%BC%E3%82%B8%EF%BC%BD%E3%81%93%E3%81%AE%E3%82%B5%E3%82%A4%E3%83%88%E3%81%AB%E3%81%A4%E3%81%84%E3%81%A6 にて、このサイトについてページでお問い合わせ情報を記載するのでページとしては不要になった
