### ISSUE TITLE
環境ファイルの実ドメインは example.jp といった実在しないものにしておく

### ISSUE THREAD

**Issue by yoshinobu-etou-id** [npocccties/chiloportal#528]
契機：開発終了時（開発終了後も実ドメインが残るのが違和感があるので）
今すぐでない理由：開発サーバーにデプロイ時にリポジトリの .env.dev-server を使用しているので
備考：横展開しておく（READMEとかのも変える）

**Comment by yoshinobu-etou-id** [comment]
現状の開発サーバーへのデプロイ時に使用している環境変数ファイルを確認したところ、
開発サーバーにのみある「/opt/.env.manual-ssl-certs」を使用していました。
従いまして、リポジトリの環境変数ファイル「.env.dev-server」の実ドメインは、
example.jp に置き換えても特に問題はありませんので、置き換えておきます。

**Comment by ties-makimura** [comment]
oku など，見ても意味がよく分からない箇所は取っ払いましょう．

- portal.example.org
- lms.example.org

でお願いします．
後は，フロントエンドも問題なければ portal.example.org か lms.example.org に揃える．

この辺りなど
https://github.com/npocccties/chiloportal/blob/develop/frontend/.env.test
https://github.com/npocccties/chiloportal/blob/develop/frontend/.env.development

**Comment by yoshinobu-etou-id** [comment]
> portal.example.org
> lms.example.org

フロントエンドも含め、上記対応しておきました。

**Comment by ties-makimura** [comment]
以下の通りお願いします．opedu.lib.osaka-kyoiku.ac.jp は lms.example.org が入る想定です．

1. dev-portal.example.org → portal.example.org
2. dev-lms.example.org → lms.example.org
3. https://opedu.lib.osaka-kyoiku.ac.jp/my/ → https://lms.example.org/my/

**Comment by yoshinobu-etou-id** [comment]
> dev-portal.example.org → portal.example.org
> dev-lms.example.org → lms.example.org

すみません。devも除去の対象だったのですね。見落としてました。

> https://opedu.lib.osaka-kyoiku.ac.jp/my/ → https://lms.example.org/my/

開発サーバーのほうは変更前の .env.test を退避させているので問題ないですね。
.env.development について、恐らく影響ないと思いますが、変更しても大丈夫でしょうか？
@knokmki612

**Comment by ties-makimura** [comment]
見つけてしまった対応漏れは以下です．他は何も影響なければクローズでOKです
https://github.com/npocccties/chiloportal/blob/develop/backend/README.md?plain=1#L163
`https://opedu.lib.osaka-kyoiku.ac.jp/badges/badge_json.php?id=41` →  `https://lms.example.org/badges/badge_json.php?id=41`

**Comment by yoshinobu-etou-id** [comment]
> 見つけてしまった対応漏れは以下です．他は何も影響なければクローズでOKです
> https://github.com/npocccties/chiloportal/blob/develop/backend/README.md?plain=1#L163
> https://opedu.lib.osaka-kyoiku.ac.jp/badges/badge_json.php?id=41 → https://lms.example.org/badges/badge_json.php?id=41

下記理由からREADMEだけの変更となりますが、よろしいでしょうか？
* README（変更可）
* インポートコマンドの単体テストコード（変更不可：テストが実施できなくなるため）
* インポートコマンドのデバッグ（変更不可：デバッグできなくなるため）

**Comment by ties-makimura** [comment]
> 下記理由からREADMEだけの変更となりますが、よろしいでしょうか？

はい

**Comment by yoshinobu-etou-id** [comment]
README、更新しましたので一旦クローズいたします。
