### ISSUE TITLE
下層ページのスタイルと、記事本文のスタイルの不整合がある

### ISSUE THREAD

**Issue by knokmki612** [npocccties/chiloportal#529]
記事本文のスタイル（見出しh1～h6など）について下層ページのスタイルのトーンに合わせるような対応ができたら完了

**Comment by knokmki612** [comment]
見た目の検討が必要に思うので秋葉さんアサインします

**Comment by knokmki612** [comment]
実装への反映が必要に思うので自身をアサインします

**Comment by Hidetaro7** [comment]
もちろんスタイルを定義することは大事だが、h5以降って使用するくらいであれば構造の見直しをしたほうがよいと思ったこともあり、h6に至ってはもう本文と変わらないくらいで、見出しとして見れるのだろうかと思う。

h4までが妥当だろうとして Tailwind Typography の通り、下層ページは大きめの h1 スタイルにしたほうが、h4までの差を見分けられやすくなるという意味でそのまま使ってしまったほうがいい気がしている。

<img width="1117" alt="image" src="https://user-images.githubusercontent.com/281424/201863600-7a238b3a-449c-405a-82da-86f797c0730d.png">

**Comment by knokmki612** [comment]
情報構造としては、例えばアプリケーション側で組んでいるh1と、マークダウン本文におけるh1では、後者が下位ではないかと考えます。したがって、
そもそもマークダウン本文における見出しとそれ以外の（アプリケーション側で組んでいる部分）の見出しは見た目として区別されていたほうがいい気がします

提案いただいた内容は下層ページについてマークダウンで採用されている見出しの見た目（大きさ）に揃えるという方針かと思いますが、上記の視点からだと情報構造的にどこが上位でどこが下位の見出しなのか分かりにくい気がします。

見出しとアウトラインの関係が次のドキュメントの例など見ると参考になるかと思います
https://html.spec.whatwg.org/multipage/sections.html#headings-and-outlines-2

---

> アプリケーション側で組んでいるh1と、マークダウン本文におけるh1では、後者が下位ではないか

現状以下のマークアップだと引用部の説明は適切ではなく、アウトラインの階層としては同じだが順序としては先にくるということまでしか言えない気がするので、asideでラップしているのを止めた方がいい気がしました

https://github.com/npocccties/chiloportal/blob/6f756dd76e42be5855131d49dd11dbe769c447fc/frontend/templates/Post.tsx#L35-L40

---

> 上記の視点からだと情報構造的にどこが上位でどこが下位の見出しなのか分かりにくい

どちらかというとマークダウン本文か下層ページの見出しの大きさを調節するというより、マークダウン本文部分を、そうではない部分の区別がされるような見た目への変更が必要ということなのかもしれません

**Comment by knokmki612** [comment]
> h4までが妥当だろうとして Tailwind Typography の通り、下層ページは大きめの h1 スタイルにしたほうが、h4までの差を見分けられやすくなるという意味でそのまま使ってしまったほうがいい気がしている。

いや、一旦この方針で反映して後日改めて問題あれば別途起票してもらうという形ですすめられればと思いました
