### ISSUE TITLE
運営元情報のグローバルメニューへ追加する実装

### ISSUE THREAD

**Issue by knokmki612** [npocccties/chiloportal#530]
関連 https://github.com/npocccties/chiloportal/issues/129

- [x] どの順番に挿入するか確認する
- [x] 実装する

ができたら完了

**Comment by knokmki612** [comment]
> どの順番に挿入するか確認する

見た目の検討が必要に思うので秋葉さんアサインします

**Comment by Hidetaro7** [comment]
ラベリングは他とトーンをあわせ「運営元について」としたい。

![Image](https://user-images.githubusercontent.com/281424/200774165-5d5c72eb-08ae-40c3-b938-57b762f57871.png)
