### ISSUE TITLE
文字が多すぎる

### ISSUE THREAD

**Issue by horimasumi** [npocccties/chiloportal#533]
文字が多すぎて，わかりにくいかも．
このままでいくか，何らかの工夫をするか決定したらクローズにする．

**Comment by horimasumi** [comment]
https://www.apple.com/jp/store

は文字は多いけど，何が重要かわかるような気がします．
素人考えではあるのですが，

- 「数少ないバッジで・・・」のバッジの説明は掲載しない
- カテゴリは，カテゴリ名やその説明をバッジ画像の上に記載する

と言う風にすると，文字数が多くても，あまり，それを感じさせないような気もするのですが，いかがでしょうか．

**Comment by knokmki612** [comment]
実装に関する変更

- [ ] 能力バッジ（WisdomBadgesCard）について説明文を取り除く

他にあるようであれば指摘いただければここに追加します。

**Comment by Hidetaro7** [comment]
- トップのイメージ下の文字についてはもう少し構造的になった見せ方をする
- カテゴリバッジの見せ方はtitle, descを上に上げ、ちゃんと言葉が目につくようにデザインされている

**Comment by Hidetaro7** [comment]
> カテゴリバッジの見せ方はtitle, descを上に上げ、ちゃんと言葉が目につくようにデザインされている

@horimasumi まずは確認お願いします！

![Image](https://user-images.githubusercontent.com/281424/200779006-f4fc0e30-bcf3-4083-927e-c5e50aa76cbf.png)

**Comment by Hidetaro7** [comment]
モバイル版は未着手＆「主体的」を強調するタスクは未着手です

なぜ文字が多すぎる印象を受けたのか？というと、同じ横幅をもった情報が連なったからという原因が考えられます。
このマンネリな流れをあえて崩すことで、見た目の違いに気づき区別して単調でマンネリ感がなくなるので、多く感じないのかもしれません。 @horimasumi 

![Image](https://user-images.githubusercontent.com/281424/200780572-349043a9-63f5-4039-b8b4-8399c07865de.png)

**Comment by horimasumi** [comment]
@Hidetaro7 
> カテゴリバッジの見せ方はtitle, descを上に上げ、ちゃんと言葉が目につくようにデザインされている~

良いと思いましたが，こんどは

- OKUTEPからのおしらせ
- 試しに受講してみる
- カテゴリから探せる能力バッジ
- 教員育成指標から探せる能力バッジ
- その他のコンテンツ

の意味のまとまりというか，タイトルが埋もれてしまったように思います．
修正かのうでしょうか．

**Comment by horimasumi** [comment]
> 見た目の違いに気づき区別して単調でマンネリ感がなくなるので、多く感じないのかもしれません。

一旦，これで，全体を見ていきたいと思います．時間切れなら，これはこれでOKです．
@Hidetaro7

**Comment by Hidetaro7** [comment]
@horimasumi いつまでに再提出しますか？

**Comment by Hidetaro7** [comment]
11月21日を目処に、ということなので 11/15 にちまでに作業を行って @horimasumi さんに見ていただく。

**Comment by Hidetaro7** [comment]
> 11月21日を目処に、ということなので 11/15 にちまでに作業を行って @horimasumi さんに見ていただく。

こちらでやりとりしているので本 issue では取り扱わないことにします
https://github.com/npocccties/chiloportal/issues/493#issuecomment-1314801687

**Comment by Hidetaro7** [comment]
> > カテゴリバッジの見せ方はtitle, descを上に上げ、ちゃんと言葉が目につくようにデザインされている~
> 
> 良いと思いましたが，こんどは
> 
> * OKUTEPからのおしらせ
> * 試しに受講してみる
> * カテゴリから探せる能力バッジ
> * 教員育成指標から探せる能力バッジ
> * その他のコンテンツ
> 
> の意味のまとまりというか，タイトルが埋もれてしまったように思います． 修正かのうでしょうか．

こちら、現状では見出し、もしくはリンクに対して説明が付いているので解決されているように思えるのですがいかがでしょうか？ @horimasumi

**Comment by knokmki612** [comment]
@Hidetaro7 実装での変更点が把握できていないのですが、何らかの方法（該当する箇所のスクリーンショット、FigmaのURLの添付など）で変更点を整理いただけますでしょうか。

**Comment by Hidetaro7** [comment]
こちらです。 https://www.figma.com/file/dCE06JShf29eqnvZ4vcE8U/OKUTEP?node-id=731%3A6806&t=9RfyA8G9ikDvecFV-1

@knokmki612 

![image](https://user-images.githubusercontent.com/281424/201892384-1aceb7d0-77bb-44cb-9769-ea70df025663.png)

**Comment by knokmki612** [comment]
範囲が広すぎてよく分からないです。他のissue取り組んで残った変更箇所を目視で確認して取り組みます。その後変更漏れがあれば指摘してください。

**Comment by knokmki612** [comment]
> こんどは
> 
> - OKUTEPからのおしらせ
> - 試しに受講してみる
> - カテゴリから探せる能力バッジ
> - 教員育成指標から探せる能力バッジ
> - その他のコンテンツ
> 
> の意味のまとまりというか，タイトルが埋もれてしまったように思います．

ポータルカテゴリーのカードのタイトルの文字の太さが、他の見出しと同様に太くなり、識別しやすさに影響あるのが一因かもしれませんね

ひとまず現状のまま反映しますので改めて違和感あるようであれば別途起票してもらえればと思います
