### ISSUE TITLE
ブラウザの戻るボタンを押すと，スクロール位置がクリックした位置に戻るようにする

### ISSUE THREAD

**Issue by ties-makimura** [npocccties/chiloportal#541]
ブラウザの戻るボタンを押すと，スクロール位置がクリックした位置に戻るようになってほしい．
現在は，例えば以下のような動きになります．何か意図があったりしますか？

1. カテゴリから探せる能力バッジの中から選択してクリック
2. ブラウザで戻るボタン押す
3. スクロール位置が一番上でトップページが表示される

**Comment by knokmki612** [comment]
next/link コンポーネントの scroll プロパティがデフォルトでは有効になっているため、画面遷移時ページ上部にスクロール位置がリセットされます。

> [scroll](https://nextjs.org/docs/api-reference/next/link#disable-scrolling-to-the-top-of-the-page) - Scroll to the top of the page after a navigation. Defaults to true

https://nextjs.org/docs/api-reference/next/link

scroll プロパティを無効にした場合、スクロール位置が復元される想定です。

参考 https://nextjs.org/docs/migrating/from-react-router#scroll-restoration

> 何か意図があったりしますか？

意図はありません。

**Comment by ties-makimura** [comment]
> scroll プロパティを無効にした場合、スクロール位置が復元される想定です。
> 意図はありません。

特に意図がなければ，無効でお願いします．

**Comment by horimasumi** [comment]
解決していないので，再開します．

**Comment by ties-makimura** [comment]
無効にするだけでは解決できなかったので，処理は戻している

> scroll: false にすべきではないということだったのでしょうか．
> 遷移時はトップへスクロールするが戻る時は復元されるようなオプションがあるといいのですが、残念ながらscrollオプションについてはそのような挙動ではないようです。
> 私もドキュメントは目を通していますが挙動として今回のケースで期待されるものかは把握していなかったので、指摘いただいて初めて結果があきらかになった所でしょうか。

**Comment by knokmki612** [comment]
ref https://github.com/npocccties/chiloportal/pull/612

**Comment by knokmki612** [comment]
実験的機能として scroll restoration が提供されているので、どちらかというとこちらを試すべきだったかもしれません（いずれにせよ有効化した場合今後同じ挙動であることは保証されないという点では注意が必要かと思います）
https://github.com/vercel/next.js/commit/38bd1a024cb25923d8ea15f269a7294d073684d8
