### ISSUE TITLE
トップ-カテゴリの説明を追加する

### ISSUE THREAD

**Issue by Hidetaro7** [npocccties/chiloportal#542]
「カテゴリから探せる能力バッジ」の下に以下の内容の説明を追加する

https://github.com/npocccties/oku-private/wiki/%E3%82%AB%E3%83%86%E3%82%B4%E3%83%AA%E3%81%AE%E8%AA%AC%E6%98%8E

**Comment by knokmki612** [comment]
見た目の検討が必要かと思うので秋葉さんをアサインします。Figmaにて検討確定したのちアサイン外れてもらえればと思います。

**Comment by Hidetaro7** [comment]
https://www.figma.com/file/dCE06JShf29eqnvZ4vcE8U/OKUTEP?node-id=731%3A6806

作業済みです @knokmki612

**Comment by Hidetaro7** [comment]
https://webdino-butterfly.slack.com/archives/C032GK7KLUA/p1668037675308029

修正が入ったので Figma のほうでも修正済み
