### ISSUE TITLE
「教科等指導力」のバッジグラフィックを作成

### ISSUE THREAD

**Issue by Hidetaro7** [npocccties/chiloportal#556]
カテゴリが一つ増えたのでそのグラフィックを作成する必要があるので作成した。

<img width="456" alt="image" src="https://user-images.githubusercontent.com/281424/201285640-32aa1bfd-52f2-4693-9949-a26f9ee2f4ab.png">

**Comment by Hidetaro7** [comment]
@horimasumi さん、こちらのグラフィックでよろしければ @ties-makimura さんにお渡ししますので、ジャッジお願いします。

**Comment by horimasumi** [comment]
これでOKです．お願いします．

**Comment by Hidetaro7** [comment]
![教科等指導力](https://user-images.githubusercontent.com/281424/201298501-40eeaea3-0ab0-4f55-bc71-ccd0719a187c.png)

@ties-makimura pngファイルをお渡しします。 よろしくお願いします。

**Comment by Hidetaro7** [comment]
作成したのでクローズ
