### ISSUE TITLE
バッジインポート時のバッジ画像ファイル名が被る

### ISSUE THREAD

**Issue by ties-makimura** [npocccties/chiloportal#557]
現在，バッジインポートをすると，取得する画像ファイルは `pluginfile.php.1.badges.badgeimage.19.f3.png` のようになりますが，これだと異なるMoodleからインポートした時に，ファイルが被りそうに思えますが大丈夫でしょうか？

**Comment by yoshinobu-etou-id** [comment]
かぶらないようにしています。
画像URLを参照するとわかると思いますが、パスの部分の`/`をドットに変換しており、
画像URLが一意とすると、かぶりようがないためです。

画像URL： `https://opedu.lib.osaka-kyoiku.ac.jp/pluginfile.php/1/badges/badgeimage/41/f1`
↓
変換後： `pluginfile.php.1.badges.badgeimage.41.f1.png`

**Comment by ties-makimura** [comment]
異なるMoodleからの場合，以下のようになる可能性はありますがそれも大丈夫でしょうか？

画像URL：`https://hoge.lib.osaka-kyoiku.ac.jp/pluginfile.php/1/badges/badgeimage/41/f1`
↓
変換後： ？？？

**Comment by yoshinobu-etou-id** [comment]
そういえば異なるMoodleというパターンがありましたね。。。
ドメインから含めて画像ファイル名に変換しておきます。

**Comment by yoshinobu-etou-id** [comment]
#559 にて以下のようにドメインを含めて変換するように対応しておきました。

画像URL： `https://opedu.lib.osaka-kyoiku.ac.jp/pluginfile.php/1/badges/badgeimage/41/f1`
↓
変換後： `opedu.lib.osaka-kyoiku.ac.jp.pluginfile.php.1.badges.badgeimage.41.f1.png`

**Comment by ties-makimura** [comment]
ドメイン部分含めて画像が登録されることを確認できました．
