### ISSUE TITLE
バッジがDBから削除できない

### ISSUE THREAD

**Issue by ties-makimura** [npocccties/chiloportal#558]
Django ページから， wisdom badges や nowledge badges を削除しようとすると Server Error (500) になり削除できません．
不要な能力バッジや知識バッジの削除手順があるのでしょうか？

ちなみに，Criteria は削除できました．

**Comment by yoshinobu-etou-id** [comment]
外部キー制約があるからだと思います。
wisdom_badges を参照しているテーブルは categorised_badge がありますし、
categorised_badge は 以下同文というように、端のテーブルから削除していかないとダメですね。

**Comment by yoshinobu-etou-id** [comment]
categorised_badges を参照しているテーブルはなかったですね。
なので、cateogrised_badges から該当の wisdom_badgs_id を削除すればよいと思います。

**Comment by ties-makimura** [comment]
> 外部キー制約があるからだと思います。

なるほど．

> なので、cateogrised_badges から該当の wisdom_badgs_id を削除すればよいと思います。

cateogrised_badges から wisdom_badgs_id を削除してもServer Error (500)になりました．．

```
wisdom badges "WisdomBadges object (1)"を削除しますか？ 関連づけられている以下のオブジェクトも全て削除されます:
「はい大丈夫です」
↓
Server Error (500)
```

**Comment by yoshinobu-etou** [comment]
knowledge_badges からも wisdom_badgs_id を削除する必要があります。
他にはないようですが、データを削除するときは sqlファイルの「REFERENCES」という箇所に着目し、
該当箇所のテーブルからもデータを削除する必要があることをご留意ください。

**Comment by ties-makimura** [comment]
以下の順で削除していけば，wisdom badges を削除できることを確認．
また，場合によっては2番からでも大丈夫な場合もある（削除したい wisdom badges と紐づいている categorised_badges が，他の wisdom badges とも紐づいている場合ならいける）

1. categorised_badges 
2. criteria
3. knowledge_badges 
4. wisdom_badges
