### ISSUE TITLE
チャットの見た目の実装

### ISSUE THREAD

**Issue by knokmki612** [npocccties/chiloportal#58]
関連 #52

**Comment by knokmki612** [comment]
- [ ] 振る舞いに関する実装の方針を明らかにする

**Comment by dynamis** [comment]
note: 詳細な振る舞いはまだ未定義なところがあるが、UI デザイン案は Figma 上に用意されており、機能的には基本的には検索機能のインターフェイスとなる事が決まっている。

https://www.figma.com/file/dCE06JShf29eqnvZ4vcE8U/OKUTEP?node-id=258%3A3512

**Comment by knokmki612** [comment]
シーケンス図を書きました

```mermaid
sequenceDiagram
    critical ボットとの会話
        画面-->ボット: メッセージ送信
        ボット-->バックエンドサーバー: API問い合わせ
        バックエンドサーバー-->ボット: API返答
        ボット-->画面: メッセージ返信
    option API返答待ち
        ボット-->画面: 待機メッセージ返信
    option API取得エラー
        ボット-->画面: 異常メッセージ返信
    end
```

使用するAPI

https://github.com/npocccties/chiloportal/blob/5960d9b97d72b24d9037d429bdfb3a2572f1a742/backend/doc/openapi.yaml#L327-L331

**Comment by Hidetaro7** [comment]
ランチャーの見た目をこのようにしたいと考えています。
理由はモバイルで扱いやすいようにしたいこと。

![Oct-25-0004 16-31-53](https://user-images.githubusercontent.com/281424/197711552-850fd10a-cc63-47d8-8b32-af68bb316d9c.gif)

動きのイメージは
https://www.figma.com/proto/dCE06JShf29eqnvZ4vcE8U/OKUTEP?page-id=731%3A6806&node-id=737%3A6502&viewport=1504%2C-423%2C0.78&scaling=min-zoom&starting-point-node-id=737%3A6502&show-proto-sidebar=1

Figma component

https://www.figma.com/file/dCE06JShf29eqnvZ4vcE8U/OKUTEP?node-id=265%3A2280

**Comment by Hidetaro7** [comment]
チャットの検索結果についての見せ方について、一点、検討しておきたいことがあるので issue を再オープンします。
検索結果にはこのように、先日お見せしたときに一度方針が決まったバッジタイトルのテキストだけでなく、バッジ画像、できたら発行元まで記載するコンポーネントを設計してみた提案です @horimasumi 
またこのような見せ方が実現可能かもここで話せたらと思います。 @knokmki612 

バッジの権威付け、という方針が主な動機です。

<img width="767" alt="image" src="https://user-images.githubusercontent.com/281424/198194844-01b4d1e7-9ff1-4751-bfe1-85f35024f46a.png">

**Comment by knokmki612** [comment]
別途issueとして起票してもらえると助かります。

**Comment by knokmki612** [comment]
別途起票しましたので、続きはそちらでできればと思います。
