### ISSUE TITLE
サイトのタイトルとファビコン更新方法

### ISSUE THREAD

**Issue by ties-makimura** [npocccties/chiloportal#584]
- サイトのタイトルはどこで更新すればいいでしょうか．
- ファビコンは public/favicon.ico 入れ替える対応で問題ないでしょうか．

**Comment by knokmki612** [comment]
> ファビコンは public/favicon.ico 入れ替える対応で問題ないでしょうか．

問題ないかと思います。

> サイトのタイトルはどこで更新すればいいでしょうか．

Next.js としては以下のコンポーネントを使用して設定することになります。
そういえば、全体あるいは個別のページにどのようなタイトルを設定するのか未検討な気がしますね…

https://nextjs.org/docs/api-reference/next/head

**Comment by knokmki612** [comment]
> 全体あるいは個別のページにどのようなタイトルを設定するのか未検討な気がしますね…

以下のような内容でいかがでしょう @ties-makimura 

- 全体
  - OKUTEP
    - 該当ページ https://dev-portal.oku.cccties.org/
- 個別
  - `${ポータルカテゴリ} - OKUTEP`
    - 該当ページ https://dev-portal.oku.cccties.org/portal_categories/102
  - `${能力バッジ} - OKUTEP`
    - 該当ページ https://dev-portal.oku.cccties.org/wisdom_badges/103
  - `${コンシューマ}の教員育成指標 - OKUTEP`
    - 該当ページ https://dev-portal.oku.cccties.org/consumers/101
  - `${教員育成指標} - ${成長段階} - OKUTEP`
    - 該当ページ https://dev-portal.oku.cccties.org/consumers/101/frameworks/101/stages/101
  -  `${記事タイトル} - OKUTEP`
    - 該当ページ
      - https://dev-portal.oku.cccties.org/concept
      - https://dev-portal.oku.cccties.org/posts/example-1
  - `OKUTEPからのおしらせ - OKUTEP`
    - 該当ページ https://dev-portal.oku.cccties.org/posts
  -   `検索結果「${検索キーワード}」 - OKUTEP`
    - 該当ページ https://dev-portal.oku.cccties.org/search?q=%E8%82%B2%E6%88%90

**Comment by knokmki612** [comment]
https://github.com/npocccties/chiloportal/issues/584#issuecomment-1321472883 の内容で反映しましたので、何か変更点あればコメントいただければと思います。
疑問点について解消できたようであれば完了をお願いします :pray:

**Comment by ties-mitsuhashi** [comment]
全体・個別のページのタイトルの動作を確認いたしました．
問題ありませんので終了とします．
