### ISSUE TITLE
ウェブアプリケーションフレームワークの選定

### ISSUE THREAD

**Issue by knokmki612** [npocccties/chiloportal#6]
UIライブラリ、ルーティング等ウェブアプリケーション開発のためのフレームワークが選定導入できたら完了

https://github.com/npocccties/chibichilo でも採用しておりメンテナンス性を考慮すると [Next.js](https://nextjs.org/) になるのかなと思った

**Comment by dynamis** [comment]
普通のウェブサイトっぽい所もあるけどコンテンツ数も少ないし Gatsby とかに行くほどでも無くシンプルに Next.js で良いのだと思います。
