### ISSUE TITLE
能力バッジの画面のレスポンシブ対応の検討

### ISSUE THREAD

**Issue by knokmki612** [npocccties/chiloportal#607]
モバイル、タブレット、デスクトップといった可変幅でのビューポートでの適切な見た目を検討できたら完了

**Comment by Hidetaro7** [comment]
経緯として
元々のデザインはすでにモバイル・PCで実現可能な1カラムレイアウトだったが、
デザインミーティングにおいて改善を重ねた結果、レスポンシブであることを検討する必要が出てきた。

**Comment by Hidetaro7** [comment]
[こちら](https://www.figma.com/file/dCE06JShf29eqnvZ4vcE8U?node-id=731:6806#312372089)にも書きましたが

```
正直、どの横幅から2カラムに切り替えたほうが見た目が良いかは運用してみないとわからないです。
現時点では

[https://tailwindcss.com/docs/responsive-design#using-custom-breakpoints](https://www.figma.com/exit?url=https%3A%2F%2Ftailwindcss.com%2Fdocs%2Fresponsive-design%23using-custom-breakpoints)

における"md（min-width: 768px）" を境目に2カラムに切り替えることでアタリを付けておき、運用後に文字の量などを見つつアップデートしていくことを想定していきたいと思います。
```

なので、運用によってはブレイクポイントを変更する提案は将来あるかもしれない、という前提で決めて進めたいと思います。

**Comment by knokmki612** [comment]
ひとまずmdをブレークポイントとして想定するということで了解しました。実装については #606 で取り組みますので、検討できたということでこちらのissue完了しておきます。
