### ISSUE TITLE
ファビコンの差し替え

### ISSUE THREAD

**Issue by Hidetaro7** [npocccties/chiloportal#609]
Figma でファビコン用に配置しておき、 ico ファイルのみ用意、
リポジトリのファビコンファイルを差し替えたら完了。

**Comment by knokmki612** [comment]
> > オリジナル（Figma）は https://www.figma.com/file/dCE06JShf29eqnvZ4vcE8U/OKUTEP?node-id=1204%3A10279&t=TLgADdVdNOG9S3lQ-0 でしょうか。オリジナルを元に私の方で作業することもできるかと思いますがいかがしましょう。
> 
> そうしていただけたら助かります。

_Originally posted by @Hidetaro7 in https://github.com/npocccties/chiloportal/issues/610#issuecomment-1326175201_

以上の経緯により改めて作業する
