### ISSUE TITLE
マウスオーバー時に見た目が変わらないリンクエリアの検討

### ISSUE THREAD

**Issue by ties-makimura** [npocccties/chiloportal#614]
たとえば，トップページにある「試しに受講してみる」エリアだとマウスオーバー時に枠線が強調されるが，「カテゴリから探せる能力バッジ」エリアだと特に見た目が変わらず，一見すると不具合のようにも見える．

そのような気になる箇所を整理して，それぞれ対応するか，現状でも納得できるか検討する．
![image](https://user-images.githubusercontent.com/8957521/203671868-4a0008b9-20a1-4829-bb77-f57f945837d8.png)

**Comment by knokmki612** [comment]
単純な対応としては、マウスホバー時primary-50の背景色になるようなスタイルの追加をおこなうことが考えられるかと思いました

**Comment by ties-makimura** [comment]
@knokmki612 
その他リンク関係で気になる箇所を整理しました．案は参考まで．

- 共通
  - [ ] リンク付き文字に黒色と赤色が混在している
    案：本文とパンクズのリンクについては全て赤色に統一する．フッターのリンクについては黒色に統一する
  - [ ] リンク付き文字に，アンカーがあるものとないものが混在している
    案：全てアンカーなしにして，マウスオーバー時にアンカーを表示する．
- トップページ
  - [ ] カテゴリから探せる能力バッジのエリアは，マウスオーバー時に枠線が強調されない
    案：マウスオーバー時に枠線を出す
- カテゴリ別ページ，検索ページ  
  - [ ] 能力バッジのタイトルや説明箇所もクリックできる範囲なのになにも強調されない
    案：マウスオーバー時に背景色を付ける or  マウスオーバー時に枠線をつける

**Comment by knokmki612** [comment]
> その他リンク関係で気になる箇所を整理しました．案は参考まで．

リンクなど画面遷移の作用がある部品、あるいは押せそうな見た目の部品をどのような見た目で運用するかは部分的に方針が定められていますが、厳密に適用されていない状態ではあります。そのような話題については https://github.com/npocccties/chiloportal/issues/507 で議論させてください。

このissueとしてはあくまで画面遷移する部品について、マウスオーバー時見た目の変化がないものについての対応をスコープとさせてください。

**Comment by ties-makimura** [comment]
了解です．ではこちらはこの辺りですね．

- トップページ
  - [ ] カテゴリから探せる能力バッジのエリアは，マウスオーバー時に枠線が強調されない
    案：マウスオーバー時に枠線を出す
- カテゴリ別ページ，検索ページ  
  - [ ] 能力バッジのタイトルや説明箇所もクリックできる範囲なのになにも強調されない
    案：マウスオーバー時に背景色を付ける or  マウスオーバー時に枠線をつける

**Comment by knokmki612** [comment]
@Hidetaro7 こちらの現在はどのような状況でしょうか。整理いただけると状況把握しやすくなり助かります。

**Comment by knokmki612** [comment]
改修にあわせてリンクの見た目に関するガイドラインが策定 https://github.com/npocccties/oku-private/issues/171 されたことと、既存の見た目（少なくとも https://github.com/npocccties/chiloportal/issues/614#issue-1462617933 のスクリーンショット）については廃止済みですのでクローズします。
