### ISSUE TITLE
ページネーションの番号が現在開いているページもクリックできてしまう

### ISSUE THREAD

**Issue by ties-makimura** [npocccties/chiloportal#616]
カテゴリ別ページで確認．
たとえば，1ページ目開いている状態で1ページ目がクリックできる状態になっています．

![image](https://user-images.githubusercontent.com/8957521/203720461-0bc83f68-7b00-4f1a-9c0f-46d963d34d29.png)

**Comment by knokmki612** [comment]
はい。現状考慮していないです。開いているページであればリンク要素にしないような変更が必要です

https://github.com/npocccties/chiloportal/blob/4c9cc449353f13a8a33d25627dd30a8d3e232acf/frontend/components/Pagination.tsx#L36-L55

**Comment by Hidetaro7** [comment]
このような細かい挙動については、今後も挙げれば出てくる可能性はあると思いますが、
致命的なバグでない限り、今後の改善issueという方針で認識とらせていただけたら幸いです。 @ties-makimura

**Comment by ties-makimura** [comment]
@Hidetaro7 
はい，前回の打合せ通り，既存の残件を完了させることに専念お願いします．
結合テストしていますのでissueは追加していきますので，とりあえず future ラベル付けておきます．

**Comment by knokmki612** [comment]
現状の実装が最善とは思っていませんが、一方で https://github.com/npocccties/chiloportal/issues のページネーションなどご確認いただくと、現在のページも押せそうなポインター表示になる（ただしリンクではない模様）など押せそうな例は探せばあるかと思います（それが間違いかどうかは考え方次第という印象です）

![image](https://user-images.githubusercontent.com/9744580/203924979-ca1cff51-e88b-4b9f-8a3d-bf1f7f96e481.png)

**Comment by Hidetaro7** [comment]
> 現状の実装が最善とは思っていませんが、一方で https://github.com/npocccties/chiloportal/issues のページネーションなどご確認いただくと、

`.pagination a, .pagination span, .pagination em` に対してまとめて `cursor: pointer;` が指定されていて、指ボタンになるようにしてますね、なにか意図があるんでしょうかね。
おそらくボタンの見た目をまとめて同じにする目的なんだろうと思いますが。。

違和感と感じる方もいると思いますが、致命的な問題とまでは考えにくいので、「currentはa要素ではなくspanまたはem要素などにする」という具体的なissueに積んで残しておいてもよいかと思います。（futureでやるということで）

**Comment by knokmki612** [comment]
@Hidetaro7 https://github.com/npocccties/chiloportal/commit/d59d52fa18ff2d29f1b2d488ba663d82abdc9751 にて対応したということであれば完了にできるかと思ったのですがいかがですか

**Comment by Hidetaro7** [comment]
はい、具体的には
https://github.com/npocccties/chiloportal/commit/d59d52fa18ff2d29f1b2d488ba663d82abdc9751#diff-ec8073fde03e82e15ddef11028ee2be73a9b5d28adb6eca3a3c7db26c08a5f32R42
でポインタイベントを無効にしていることで完了とします。
