### ISSUE TITLE
トップページにあるサイト説明文の内容を修正する

### ISSUE THREAD

**Issue by ties-makimura** [npocccties/chiloportal#617]
修正内容が出揃ってから対応する

![image](https://user-images.githubusercontent.com/8957521/203726158-5880c123-1c21-4f22-bc5b-b5ec8b66b909.png)

メモ
 - こちらのリンク先は，コンセプトページではなく問い合わせページに飛ばす内容にする
   >（※）デジタルバッジの取得は、提携する教育委員会に所属する教員のみとなります。詳しくは[こちら](https://test-portal.oku.cccties.org/concept)をご覧下さい。

**Comment by ties-makimura** [comment]
@knokmki612 
- 以下は途中で改行しない
  > デジタルバッジ（※）は，あなたの自己実現のために活用できるデジタル証明書となります。
OKUTEPで学び続けることで、あなたのウェルビーイングを高め、子ども達が夢や希望を持てる社会の実現を目指します。
- 「OKUTEPとは →」 は削除
![image](https://user-images.githubusercontent.com/8957521/206940304-d711f6b0-d33b-4def-84f6-728150ef6417.png)

**Comment by knokmki612** [comment]
https://github.com/npocccties/chiloportal/issues/617#issuecomment-1345726228 にて共有いただいた変更点が一通りという認識であっていますでしょうか @ties-makimura

**Comment by knokmki612** [comment]
> [#617 (comment)](https://github.com/npocccties/chiloportal/issues/617#issuecomment-1345726228) にて共有いただいた変更点がひと通りの変更点という認識であっていますでしょうか @ties-makimura

認識あっているとのことなので着手可能の状態になった。Figmaと実装について反映しようかと思う
