### ISSUE TITLE
ポータルの上部メニューをクリックすると表示されるリストが隠れている

### ISSUE THREAD

**Issue by ties-mitsuhashi** [npocccties/chiloportal#630]
ポータルの各上部メニューをクリックすると表示されるリストが，隠れて見えない状態になっています．
右側に，スクロールバーが表示されているようです．

![image](https://user-images.githubusercontent.com/8965947/206058273-1fdeee85-2cdc-413c-ad71-ca72cf5b6824.png)

**Comment by knokmki612** [comment]
https://github.com/npocccties/chiloportal/pull/627/commits/96fd8d5e349df54490b502de3999ea1e4b9862e9 の変更が原因ですね
変更を取り消すような形で対応したいと思います
