### ISSUE TITLE
ポータルサイトのロゴを黒いものに変更する

### ISSUE THREAD

**Issue by ties-mitsuhashi** [npocccties/chiloportal#634]
ポータルサイトのロゴについて，現在の赤のものから，黒のもの（添付画像）に変更していただけますでしょうか．
よろしくお願いいたします．

![image](https://user-images.githubusercontent.com/8965947/206369597-8c60ea04-5002-4475-bda7-8a318116e2df.png)

**Comment by ties-makimura** [comment]
> 黒のもの

対応時は，faviconもあわせて変更になると思います．
