### ISSUE TITLE
能力バッジを認定している教育委員会の育成指標の動線の見た目の差異

### ISSUE THREAD

**Issue by knokmki612** [npocccties/chiloportal#635]
スクリーンショット
![image](https://user-images.githubusercontent.com/9744580/206371243-474eee7f-574d-4e82-987a-3cf517f5017f.png)

> Kimiaki Kuno
> 横並びにするのは、必然的に折り返す場合を想定する必要がでてきます（その分複雑になる）ので避けることが可能であれば避けたいと思っています
> 現状異なる行にjumpu-text-buttonで配置しています。
> もしそれがダメということであれば改めて現状の見た目で実装する必要がある旨のフィードバックを出してもらえればと思います。
> 現状の実装でいいということであればFigmaのほう更新できれば差異が解消されコメント解決できるかと思います。

https://www.figma.com/file/dCE06JShf29eqnvZ4vcE8U?node-id=1165:7147#324177593

何らかの形でFigmaと実装の差異を解消したら完了

**Comment by Hidetaro7** [comment]
どの部分が横並びなのかの主題が書かれていなかったので確認ですが
「全 4バッジ／計10研修」と「このバッジを認定している教育委員会教員育成指標」
の情報が1行になっている、という課題？

確かに情報構造的に違った内容になるので同じ文字の大きさや見た目が近いため判別が難しいかと思いますので2行に分けるほうが良いかと思います。
ただ、今回のリリースが現状の Figma の通りにする必要があるので、このあたりまで改善として今回の実装してよいかはTIESさんに確認が必要かと思います。（私の判断であれば取り入れたい案です）

**Comment by knokmki612** [comment]
> 今回の実装してよいかはTIESさんに確認が必要

TIESさんに確認することとしてはその前に、この差異を直近で解消するか否かじゃないでしょうか

**Comment by ties-makimura** [comment]
> 認定している教育委員会を見る

文言だけ直近で変更する

**Comment by knokmki612** [comment]
#839 にて見た目変更され実装とFigmaの差異についても解消されたのでクローズします
