### ISSUE TITLE
field の sort_key を field1_name/field2_name にも適用したい

### ISSUE THREAD

**Issue by yoshinobu-etou-id** [npocccties/chiloportal#643]
field1keys を set で作成しているが、dict（連想配列）で作成し、
sort_keyをキーにしてみる。（field2keysも同様）

**Comment by yoshinobu-etou-id** [comment]
@ties-makimura 
本番環境で問題ないことが確認できましたら、こちらの issue をクローズ願います。

**Comment by m-takay** [comment]
@ties-makimura こちら確認されたらCloseをお願いします。

**Comment by ties-makimura** [comment]
field2_nameもソートされているの確認できました．クローズします．
