### ISSUE TITLE
Djangoの管理画面で sub_name の空白が許容できないので、それを可能にしたい。

### ISSUE THREAD

**Issue by yoshinobu-etou-id** [npocccties/chiloportal#647]
sql の not null が原因。
sql の 下記項目の not null を外す。（モデルにも適用する）
- categorised badges
  - Description
- framework
  - Description
  - Supplementary
- stage
  - Sub name
  - Description

**Comment by yoshinobu-etou-id** [comment]
stage. password に null 許可にしたが、なぜか必須項目扱いになるので、調査が必要。

**Comment by yoshinobu-etou-id** [comment]
上記修正済み。

**Comment by m-takay** [comment]
@ties-makimura こちら確認されたらCloseをお願いします。

**Comment by ties-makimura** [comment]
確認できました．クローズします．
（Djangoの管理画面でstage.sub_name を空白にして保存できた）
