### ISSUE TITLE
知識バッジのリストの並び替え

### ISSUE THREAD

**Issue by kou029w** [npocccties/chiloportal#663]
順序リストを実現する

参照: https://github.com/npocccties/oku-private/wiki/chiloportal-API%E4%B8%80%E8%A6%A7

運用者によって知識バッジのリストの順序を指定できるようになればクローズ

**Comment by YouheiNozaki** [comment]
関連：[#664](https://github.com/npocccties/chiloportal/issues/664)

**Comment by kou029w** [comment]
> - (主に CHiLO-Portal #663 解決に向けて) フロントエンドでの知識バッジの使用、対応するAPIエンドポイント
>   - /wisdom_badges/{id} 画面
>     - 使用しているAPIに関してはソースコードを確認

確認してみました。

https://github.com/npocccties/chiloportal/blob/770b854d50a2d53fc4d70b29eb46c9d09f4009a8/frontend/pages/wisdom_badges/[wisdomBadgesId].tsx

client.badges を利用しており GET /api/v1/badges を利用していると考える。

まず、badges_type: "wisdom" を指定して wisdomBadges を得る。knowledge_badges_list を得る。
次に、badges_type: "knowledge" を指定して knowledgeBadgesList を得る。このとき badges_ids は `wisdomBadges.detail.knowledge_badges_list.join(",")`。

> knowledge_badge.idでソートしているここがknowledge_badges_listプロパティに含まれる知識バッジの並び順を決めていると思われる
> 
> https://github.com/npocccties/chiloportal/blob/770b854d50a2d53fc4d70b29eb46c9d09f4009a8/backend/chiloportal/responses.py#L83

> /badgesエンドポイントでbadges_type=knowledgeを与えたとき得られる並び順はこのクエリで宣言していると思われる
> .order_by("pk") とあるように現在主キーによって決まっている
> 
> https://github.com/npocccties/chiloportal/blob/770b854d50a2d53fc4d70b29eb46c9d09f4009a8/backend/chiloportal/views/badges_detail.py#L47

現状は knowledge_badges_list の時点の並び順は関係なく (badges_ids の順序によらず)、これは `KnowledgeBadges.objects.filter(pk__in=id_array).order_by("pk")` で決まっている様子。

**Comment by kou029w** [comment]
> (backend) sort_keyフィールドを使用した並びでAPIによってリストを得られるように実装

案1
: backend/chiloportal/views/badges_detail.py への修正。

案2
: sort_keyフィールドをレスポンスに含める & フロントエンド側でのsort_keyフィールドに応じた並び替え。

別案
: (あれば) (実装方針に関しては @YouheiNozaki さんのやりやすい方針でよいと思います。)

**Comment by kou029w** [comment]
@YouheiNozaki さん、私の確認不足で申し訳ないです。運用 @ties-makimura さんに相談したところ、そもそもpkを書き換えて並び替えできるかどうかまず実験するとのことでした。もし仮にpkを書き換えて並び替えできることが実証できれば本件クローズするという想定になります。
したがって @ties-makimura さんに本件渡します。

**Comment by ties-makimura** [comment]
まず，バッジのアライメント順とポータルで表示される知識バッジの並び順が一致するのを確認した．
バッジのアライメントを設定する時に，きちんとコースと同じ順で設定するように気を付ければ，最初は問題なさそう．

| 順番 | バッジのアライメント | ポータル           | コース             | 
| ---- | -------------------- | ------------------ | ------------------ | 
| 1    | 授業研究の可能性     | 授業研究の可能性   | 日本の教育政策動向 | 
| 2    | 特別活動の可能性     | 特別活動の可能性   | 教育実践の課題     | 
| 3    | 教育実践の課題       | 教育実践の課題     | 特別活動の可能性   | 
| 4    | 日本の教育政策動向   | 日本の教育政策動向 | 授業研究の可能性   | 

後から変更したい場合，criteriaにあるknowledge_badges_idも変更されないといけない．
https://github.com/npocccties/chiloportal/blob/main/backend/sql/create_table.sql#L59

今のままだとpkだけ変更できない．
`ERROR:  update or delete on table "knowledge_badges" violates foreign key constraint "criteria_knowledge_badges_id_fkey" on table "criteria"`

**Comment by kou029w** [comment]
@ties-makimura さん

確認ありがとうございます。外部キー制約によって更新できないということですね。下記のSQLのようにして、カスケードするように変更するというのはどうでしょうか?

```sql
ALTER TABLE criteria DROP CONSTRAINT criteria_knowledge_badges_id_fkey, ADD CONSTRAINT criteria_knowledge_badges_id_fkey FOREIGN KEY (knowledge_badges_id) REFERENCES knowledge_badges(id) ON UPDATE CASCADE;
```

**Comment by ties-makimura** [comment]
@kou029w 
変更してサイト見て回りましたが，知識バッジの並び順以外は影響なさそうです．
今は↑のSQL設定に直しておくだけで問題ないかと思います．

![image](https://user-images.githubusercontent.com/8957521/227127976-e7fd8c6f-80eb-430d-bf36-9aa6922e8d0b.png)

**Comment by kou029w** [comment]
pkを書き換えて並び替えできることが実証できているので本件クローズします。
