### ISSUE TITLE
Onboarding @YouheiNozaki @kou029w

### ISSUE THREAD

**Issue by kou029w** [npocccties/chiloportal#664]
新しく加わる開発者を着手可能な状態にする
本システムがなぜ開発されているのか、また何なのか、どのように開発されているのか理解し、開発に着手可能な状態になり新しく加わる開発者 @YouheiNozaki @kou029w がこれでイケると判断すれば完了。

(実施方法日時未定)

**Comment by kou029w** [comment]
このあたりのコードなど参照しつつ、ある程度の理解深めた:

テーブル定義 https://github.com/npocccties/chiloportal/blob/main/backend/sql/create_table.sql
テーブル設計 https://github.com/npocccties/chiloportal/issues/23
Figma https://www.figma.com/file/dCE06JShf29eqnvZ4vcE8U/OKUTEP?node-id=731:6806&t=aG8pqjc0wJdLmpsr-0
教員育成指標の具体例 https://github.com/npocccties/oku-private/issues/34

**Comment by knokmki612** [comment]
@YouheiNozaki @kou029w @dynamis Onboarding について Google Meets のカレンダー招待をひとまずしてもよろしいでしょうか（都合のよい日時ありましたらカレンダーで提案いただければと）

**Comment by kou029w** [comment]
3月 16日 (木曜日) · 17:00～19:00 ビデオ会議にて実施:
https://meet.google.com/asq-zjif-nfo

**Comment by YouheiNozaki** [comment]
お世話になります。野崎と申します。明後日はよろしくお願い致します。

経過報告なのですが、

開発環境を動かしてみたいのですが、クライアントは動かすところまでは、問題なさそうだったのですが、
![Image](https://user-images.githubusercontent.com/47715432/225040515-744485ee-2abc-45c9-9f64-884c4e4e6757.png)

ログイン画面や実際の受講画面にはアクセスできず、、、サーバーの建て方があまりわかっていないです。
このあたりのReadMEを読んで作業しています。
https://github.com/npocccties/chiloportal/tree/main/backend

**Comment by YouheiNozaki** [comment]
具体的には
https://github.com/npocccties/chiloportal/tree/main/backend#%E7%92%B0%E5%A2%83%E6%A7%8B%E7%AF%89%E6%89%8B%E9%A0%86-1
の手順「8.デプロイ」で以下のようなログが出ています。

```
./server_start.sh
/Users/youheinozaki/chiloportal/backend
no configuration file provided: not found
no configuration file provided: not found
no configuration file provided: not found
no configuration file provided: not found
no configuration file provided: not found
no configuration file provided: not found
no configuration file provided: not found
no configuration file provided: not found
no configuration file provided: not found
./server_db_restore.sh
/Users/youheinozaki/chiloportal/backend
/var/chiloportal.dump が存在しないためDBのリストアは行いません。
```

お手数ですが、当日このあたりの環境構築などもご相談させていただきたいです🙏よろしくお願いします🙏

**Comment by knokmki612** [comment]
> no configuration file provided: not found

これ自体はおそらくdocker-compose.yml が存在しないかつ存在する compose 設定ファイルを未指定のため生じているエラーメッセージかと思います。

**Comment by knokmki612** [comment]
歴史的な経緯としては、限られた開発期間で実装することを念頭にフロントエンドとバックエンドは並列で開発したため、フロントエンドは主にバックエンドの代わりにモックアップサーバーを使用して開発していました。
バックエンドの動作方法についても開発期間中に何度かドラスティックに変更されているため、メンテされていない動作手順などが存在している状態かと思います。

- フロントエンドとバックエンドでビルドコンテキストを共有する
- 開発サーバーの起動、デプロイについて管理者権限不要にする
- オープンバッジが存在するMoodleをローカルでも用意しバッジのインポート、画像の出力の動作確認が出来るようにする
- OpenAPI が手書き管理されているものと Django から生成されるもので重複している

など開発環境周りの課題が（起票していませんが）いくつか存在しているかと思います。

**Comment by YouheiNozaki** [comment]
なるほど、詳しくありがとうございます！

**Comment by kou029w** [comment]
# CHiLO-Portalメモ

主にバックエンドサーバー周りを中心に予習しました。気になりポイントをまとめました。

- これまでの開発フロー、ブランチ運用
- テストの実施方法
- (主に CHiLO-Portal #663 解決に向けて) フロントエンドでの知識バッジの使用、対応するAPIエンドポイント
  - /wisdom_badges/{id} 画面
    - /api/v1/badges

---

開発

develop ブランチがある
git-flow のようなブランチ運用の様子

---

ローカル環境でのバックエンドサーバーの起動

```
ln -s .env.localhost .env
ln -s docker-compose.localhost.yml compoes.yml
bash server_start.sh
```

このほかの手段として、Visual Studio Code Dev Containersで開発環境を構築できるようではあった
その場合はserver_start.shのDocker Composeコマンドを参考にしてコンテナ内でpythonコマンドを実行し起動できる

---

テスト

チェックできていないがREADMEにあることを確認

---

バッジのインポート

```
bash import_badge.sh ...
```

test.csv (例)

```csv
https://lms.okutep.osaka-kyoiku.ac.jp/badges/badge_json.php?id=41,1
```

↓

```
docker compose exec -T app python /workspace/manage.py import_badge --url="https://lms.okutep.osaka-kyoiku.ac.jp/badges/badge_json.php?id=41" --pcid=1
```

このようなDocker Composeコマンドが実行されることでバッジがインポートされる

https://okutep.osaka-kyoiku.ac.jp/api/v1/portalCategory/list/ を参考にして、あらかじめportal_categoryテーブルにカテゴリーを追加しておくことでOKとなり`NEXT_PUBLIC_API_MOCKING=false yarn dev` で実際にアクセスできる雰囲気になった

---

コードを読んでみる
主に CHiLO-Portal #663 解決に向けたメモ

---

Django

- [Djangoってなに？ · HonKit](https://tutorial.djangogirls.org/ja/django/)
- [Django admin](https://tutorial.djangogirls.org/ja/django_admin/)

---

知識バッジのテーブルスキーマ

https://github.com/npocccties/chiloportal/blob/770b854d50a2d53fc4d70b29eb46c9d09f4009a8/backend/sql/create_table.sql#L43
BadgesDetail view
KnowledgeBadges model の並び順を決めていると思われる場所1
/badges エンドポイントのレスポンスで使われているのかな

https://github.com/npocccties/chiloportal/blob/770b854d50a2d53fc4d70b29eb46c9d09f4009a8/backend/chiloportal/views/badges_detail.py#L47
OpenAPIドキュメント
いずれかにknowledgeを持っているのでKnowledgeBadges modelに相当するオブジェクトと考える
BadgeDetail1とBadgeDetail2がある
BadgeDetail1は/badgesエンドポイントのみ
BadgeDetail2はknowledge_badges_listプロパティをもっている

https://github.com/npocccties/chiloportal/blob/770b854d50a2d53fc4d70b29eb46c9d09f4009a8/backend/doc/openapi.yaml#L514
BadgeDetail2を含むレスポンスを返すエンドポイント1

https://github.com/npocccties/chiloportal/blob/770b854d50a2d53fc4d70b29eb46c9d09f4009a8/backend/doc/openapi.yaml#L106
BadgeDetail2を含むレスポンスを返すエンドポイント2

https://github.com/npocccties/chiloportal/blob/770b854d50a2d53fc4d70b29eb46c9d09f4009a8/backend/doc/openapi.yaml#L205
BadgeDetail2を含むレスポンスを返すエンドポイント3

https://github.com/npocccties/chiloportal/blob/770b854d50a2d53fc4d70b29eb46c9d09f4009a8/backend/doc/openapi.yaml#L237
BadgeDetail2を含むレスポンスを返すエンドポイント4

https://github.com/npocccties/chiloportal/blob/770b854d50a2d53fc4d70b29eb46c9d09f4009a8/backend/doc/openapi.yaml#L106
knowledge_badge.idでソートしているここがknowledge_badges_id_listプロパティに含まれる知識バッジの並び順を決めていると思われる

https://github.com/npocccties/chiloportal/blob/770b854d50a2d53fc4d70b29eb46c9d09f4009a8/backend/chiloportal/responses.py#L83
/badgesエンドポイントでbadges_type=knowledgeを与えたとき得られる並び順はこのクエリで宣言していると思われる
.order_by("pk") とあるように現在主キーによって決まっている

https://github.com/npocccties/chiloportal/blob/770b854d50a2d53fc4d70b29eb46c9d09f4009a8/backend/chiloportal/views/badges_detail.py#L47
viewのテストコード
影響ありそうなのでチェックしたいところではある
実行方法はわからない

https://github.com/npocccties/chiloportal/blob/770b854d50a2d53fc4d70b29eb46c9d09f4009a8/backend/chiloportal/tests/views/localhost/test_badges.py#L6
KnowledgeBadgesの変更の影響を受けそうなテストコード
チェックしたいところではあるが実行方法はわからない

https://github.com/npocccties/chiloportal/blob/770b854d50a2d53fc4d70b29eb46c9d09f4009a8/backend/chiloportal/tests/views/localhost/base_api_view_tests.py#L530
KnowledgeBadges.objects.create()はKnowledgeBadgesの作成
もし仮にデータベーススキーマを変更した場合このあたりのメソッドはすべて影響あるような

https://github.com/npocccties/chiloportal/blob/770b854d50a2d53fc4d70b29eb46c9d09f4009a8/backend/chiloportal/management/commands/import_badge.py#L271
インポート処理のテスト
影響あると思われる

https://github.com/npocccties/chiloportal/blob/770b854d50a2d53fc4d70b29eb46c9d09f4009a8/backend/chiloportal/tests/commands/test_import_badge.py#L431
知識バッジのインポート時の処理
リストalignmentsをもとに順次処理する
このとき作られる順番でRDBレコードは挿入されているのではないかと考えるが、どうなのだろう…?
alignmentsはOpen Badges Specification Candidate Final Public Spec Version 3.0由来と考える
https://1edtech.github.io/openbadges-specification/ob_v3p0.html

JSONとしてはarrayとして得られるが必ずしも期待した並び順で得られないということだろうか

https://github.com/npocccties/chiloportal/blob/770b854d50a2d53fc4d70b29eb46c9d09f4009a8/backend/chiloportal/management/commands/import_badge.py#L236

**Comment by knokmki612** [comment]
> テストの実施方法

下記の手順はおそらく VSCode Remote Containerを想定したものになっているかと思います。

https://github.com/npocccties/chiloportal/blob/770b854d50a2d53fc4d70b29eb46c9d09f4009a8/backend/README.md?plain=1#L28-L32

他には GitHub Actions でテストカバレッジを算出するセットアップがされています。

https://github.com/npocccties/chiloportal/blob/770b854d50a2d53fc4d70b29eb46c9d09f4009a8/.github/workflows/backend.yml#L28

例 https://github.com/npocccties/chiloportal/pull/649#issuecomment-1358799807

**Comment by knokmki612** [comment]
> これまでの開発フロー、ブランチ運用

ブランチ運用については https://github.com/npocccties/chiloportal/issues/18 、コードレビューについては https://github.com/npocccties/chiloportal/issues/10 にて検討、合意した規約にもとづいて開発運用しています。

**Comment by knokmki612** [comment]
未使用のAPIを削除した件は

> 現状他のAPIのレスポンスで得られており使用していないAPIが3点あります（ので動作確認にチェックが入っていない）が、こちらどう取扱いましょうか？（最初から必要十分のAPIが検討されていれば未使用のAPIはででこなかったと思います、すみません & ひととおりAPI用意いただいたおかげでスムーズにフロントエンド実装できました :pray:）

_Originally posted by @knokmki612 in https://github.com/npocccties/chiloportal/issues/132#issuecomment-1294430932_

にて依頼、 https://github.com/npocccties/chiloportal/pull/382 にて実施いただきました

**Comment by knokmki612** [comment]
@kou029w @YouheiNozaki 引き続き質問あれば随時回答しますので、気兼ねなくお声がけください
イケそうでしたらイケそうな旨コメントいただいたのちissue完了してもらえればと

**Comment by kou029w** [comment]
NOTE: カテゴリーの追加方法:

```sh
docker compose exec db psql -U postgres develop
```

```sql
insert into portal_category(name,description,image_url_path,sort_key) values ('授業づくり','特定の教科によらない，一般的な教育方法や授業実施について学びます','creating_lessons.png',1);
```

**Comment by kou029w** [comment]
NOTE: test.csv (例)

```csv
https://lms.okutep.osaka-kyoiku.ac.jp/badges/badge_json.php?id=41,1
```

**Comment by kou029w** [comment]
@knokmki612 
詳細説明してくださりありがとうございました :bow: 
引き続きご相談させてもらうかもですが、おかげさまでひとまず開発着手して進められそうです! :+1:

**Comment by kou029w** [comment]
@YouheiNozaki 本件そのほか何か障壁や気になる点などはありますか?

**Comment by YouheiNozaki** [comment]
@kou029w 一旦このissueとしては完了で大丈夫です。ご確認ありがとうございます！

@knokmki612 説明いただきありがとうございました🙏

**Comment by kou029w** [comment]
ありがとうございます。本件完了ということなのでクローズします。
