### ISSUE TITLE
SVGバッジが運用可能か検討する

### ISSUE THREAD

**Issue by Hidetaro7** [npocccties/chiloportal#666]
画像が眠く品質に問題を感じるため、画像をどのように扱うかの議論となり、SVGとしてバッジを提供する案が出た。

ミーティングアジェンダ
https://github.com/npocccties/oku-private/issues/144#issuecomment-1461201495

関連: https://github.com/npocccties/chiloportal/issues/621

**Comment by Hidetaro7** [comment]
- [ ] Next での影響を確認する（tuqulore）
- [ ] 実運用が可能か検討する（TIES）

**Comment by Hidetaro7** [comment]
> Next で画像をビルドしているかを確認する

Moodleではシステム上、512px四方の画像を出力するのみとなっているため、それ以外の画像バリエーションに関しては出力していない。ただ、現状を確認するとカテゴリ一覧に掲載されているバッジ画像は256px四方のものが使われている。つまりMoodleシステム以外のどこかで別のサイズの画像が書き出されていると考えられる。という話になった。
考えられることは Next 内部で書き出されているのかの確認がしたい。
@knokmki612 に確認する。

**Comment by Hidetaro7** [comment]
> 画像最適化の処理をNext.jsの方で行っているということでした。 @ties-makimura @horimasumi @yabuki @seishiono

とはいえ、SVGにすることができたらこの問題は考慮しなくて良くなる気がしています。

> 実運用が可能か検討する（TIES）

が可能となれば画像最適化のロジックも不要となりそこの部分を少し手を入れる必要がありそうですが、ブラウザ上できれいに見せられるメリットは大きいですね。
あとはTIESさんにご検討いただきたく、よろしくおねがいします。

**Comment by ties-makimura** [comment]
以下より，当面はMoodleのバッジ画像はPNGで登録し，Portalにインポート後，SVG画像に置き換える運用で進めることにする．

- 現時点ではMoodleのバッジ画像でSVGが利用できない
https://tracker.moodle.org/browse/MDL-72018
- Portalは，DBのimage_idを変更＋SVGの画像に差し替え後ビルドすれば問題なく表示され，また，品質もあがった（試しにSociety5.0の画像を差し替えた図）
![image](https://user-images.githubusercontent.com/8957521/224285935-fffbac08-e2ca-41ef-a806-294c5822c7b1.png)
