### ISSUE TITLE
クライテリアの表示順を sort_key 順にする

### ISSUE THREAD

**Issue by ties-makimura** [npocccties/chiloportal#669]
関連：https://github.com/npocccties/chiloportal/issues/500#issuecomment-1306787029

### どのような問題を解決する機能追加でしょうか?

クライテリア名に通し番号を加えることもあり，並び順を指定したい．
https://github.com/npocccties/chiloportal/issues/663 の時は，idを入れ替えるだけで知識バッジの並び順は入れ替わったが，クライアントはidを入れ替えただけでは並び順が変わらなかった．

### あなたが望む解決方法について書いてください

criteria の sort_key 順に表示されるようにする．

### スクリーンショット

![image](https://github.com/npocccties/chiloportal/assets/8957521/a8bcb8c3-49ec-491e-84fb-2cd36f5881d2)

**Comment by yoshinobu-etou-id** [comment]
現状、criteria. sort_key を ORDER BY に指定していないので、criteria. sort_key を ORDER BY に指定すれば解決できると思います。

**Comment by UenishiKeita** [comment]
本件、対応いたしました。
ご確認をお願いいたします。

**Comment by ties-makimura** [comment]
criteriaテーブルのsort_keyと連動しているのを確認できました。問題ありません。
