### ISSUE TITLE
教員育成指標の各指標別の所にバッジ数を表示させる

### ISSUE THREAD

**Issue by ties-makimura** [npocccties/chiloportal#672]
### どのような問題を解決する機能追加でしょうか?

教員育成指標にバッジがどれくらいあるかひとめで分かるようにしたい．

### あなたが望む解決方法について書いてください

・教員育成指標の各指標別の所にバッジ数を表示させる

### あなたが考えた別解について書いてください

・バッジがどれくらいあるか分かりやすいデザインにする

### スクリーンショット

![image](https://github.com/npocccties/chiloportal/assets/8957521/05a2f637-a412-4cf0-b589-304e0685cf2b)

**Comment by Hidetaro7** [comment]
ドラフトissueとして見積もっています。
https://github.com/orgs/npocccties/projects/23/views/2?pane=issue&itemId=41446337

**Comment by ties-makimura** [comment]
最新のデザインでは不要なのでひとまず閉じる
