### ISSUE TITLE
研修内容テーブルの「種類」と「名称」の登録方法

### ISSUE THREAD

**Issue by m-takay** [npocccties/chiloportal#69]
「ポータルサブシステムのDB入出力.xlsx」資料には

> DBに登録する場合は、説明を解析して登録する

とありますが、説明(description)をどのようにパースしたらよいか詳しい仕様を教えてください。

**Comment by m-takay** [comment]
関連する話題？
https://github.com/npocccties/chiloportal/issues/25#issuecomment-1225496652

descriptionではなくcriteria.narrative？

**Comment by ties-makimura** [comment]
> descriptionではなくcriteria.narrative？

はい，criteria.narrative のことです．混乱させてすみません．

**Comment by m-takay** [comment]
`"narrative": "次の必要条件を完了した場合、ユーザにこのバッジが授与されます:\n* 「 すべて 」の次の活動が完了しました:\n\"ビデオ - 1.はじめに\"\n\"ビデオ - 2.日本の教育課題を知る\"\n\"ビデオ - 3.教師の働き方を省察する\"\n\"ビデオ - 4.まとめ\"\n\"レッスン - 5.振り返り\"\n\n"`

上記の場合は
[種類] | [名称]
ビデオ | 1.はじめに
ビデオ | 2.日本の教育課題を知る
ビデオ | 3.教師の働き方を省察する
ビデオ | 4.まとめ
レッスン | 5.振り返り
として研修内容テーブルに登録すると理解しました。
種類と名称のセパレータは「半角空白＋半角マイナス＋半角空白」でよいでしょうか。

**Comment by ties-makimura** [comment]
> 種類と名称のセパレータは「半角空白＋半角マイナス＋半角空白」でよいでしょうか。

そうするしかなさそうですが，以下のように，種類や名称に「半角空白＋半角マイナス＋半角空白」を入れられた場合の考慮が必要そうに見えます．

` narrative	"この条件でバッジ授与\n* 「 すべて 」の次の活動が完了しました:\n\"クイ - ズ - 確認テ - スト\"\n\"ビデオ - 動画です\"\n\n"`

種類の方の名前は，管理側が設定しますが，名称の方の名前は利用者が好きに決めるのでコントロールが難しそうです．

**Comment by knokmki612** [comment]
オフトピックになってしまいますが
criteria.narrativeに含まれる各種類と名称の他に、それらに対応するurlというのは含まれていないですよね（現状見た目としてはリンクのような見た目で検討されているので、それを調整する必要があるか知りたい）

**Comment by ties-makimura** [comment]
> それらに対応するurlというのは含まれていないですよね

はい，urlは含まれないです．
気持ちとしては，直接飛べば嬉しいですが，現状の仕様では不可能なので諦めています．

**Comment by m-takay** [comment]
> 種類の方の名前は，管理側が設定しますが，名称の方の名前は利用者が好きに決めるのでコントロールが難しそうです．

実装としては、"～"間の左から1つ目の「半角空白＋半角マイナス＋半角空白」のみをセパレーターとする（それ以降にあっても名称の一部として扱う）仕様としておきます。
