### ISSUE TITLE
成長段階を横移動するUI

### ISSUE THREAD

**Issue by Hidetaro7** [npocccties/chiloportal#70]
- [x] 現段階の位置の可視化
- [x] 全体像を把握できる

これらが実現できるUIが問題なくデザインされている必要がある

**Comment by Hidetaro7** [comment]
<img width="460" alt="image" src="https://user-images.githubusercontent.com/281424/189587030-d462afd4-a7df-4de8-ac0b-a79355158114.png">

https://www.figma.com/file/dCE06JShf29eqnvZ4vcE8U/OKUTEP?node-id=26%3A83

**Comment by knokmki612** [comment]
ひとまず見た目として要件を満たす形で検討できているように思います
