### ISSUE TITLE
/consumer/goal/list, /consumer/badges/list 追加とフロントエンド改修の関係

### ISSUE THREAD

**Issue by knokmki612** [npocccties/chiloportal#715]
以下について @ties-makimura @foundationforce さんあたりに確認したら完了

- これらのAPIはフロントエンド改修で使用する想定なのか
- これらのAPIのパスワード認証機能はフロントエンド改修で使用する想定なのか

https://github.com/npocccties/chiloportal/blob/54fb2193c19da710afd31a89190e9695945fd1ec/backend/doc/openapi.yaml#L342-L399

**Comment by foundationforce** [comment]
バッジウォレット・バッジキャビネットシステム内のe-ポートフォリオサブシステム用の新規APIになります。

先日バッジウォレット・バッジキャビネットシステムのプロジェクト側で、e-ポートフォリオサブシステムの能力バッジ獲得状況などを見るレーダーチャート用データの話の中で、OKUTEPポータルDBの実データの中にはcategorised_badgesテーブルでバッジ情報と教員育成指標情報が紐づけされていないものがあるということが説明されました。

教員育成指標情報に紐づかない（指標が無い）獲得済みバッジも漏れなくレーダーチャート用データとして出力させたいということから、以下の新APIが必要になったそうです。

- /consumer/goal/list: コンシューマー（教育委員会）に紐づく教員育成指標情報の一覧取得
- /consumer/badges/list: コンシューマー（教育委員会）に紐づく教員育成指標情報とバッジ情報の一覧取得

**Comment by foundationforce** [comment]
もう一点、既存APIの修正が入ります。
- /portalCategory/badges/list: ポータルカテゴリに紐づく全てのバッジを取得する
  - 必須パラメータに portal_category_id があるが、これを任意に変更し、未指定時に全てのバッジを取得するように変更する

**Comment by knokmki612** [comment]
ご回答ありがとうございます :pray:

> バッジウォレット・バッジキャビネットシステム内のe-ポートフォリオサブシステム用の新規API

つまり私の作業範囲（主にチロポータルフロントエンドの改修）とは直接は関係ないということですね。

https://github.com/npocccties/chiloportal/issues/715#issuecomment-1831004487 を除けば、既存APIの変更はないものと思われることも分かりました。

以下は両方とも使用しない想定ということで確認できましたので、完了します。

> - これらのAPIはフロントエンド改修で使用する想定なのか
> - これらのAPIのパスワード認証機能はフロントエンド改修で使用する想定なのか
