### ISSUE TITLE
開発の課題整理をおこなう

### ISSUE THREAD

**Issue by knokmki612** [npocccties/chiloportal#729]
バッジを探す画面の仕様が変わったことにあわせて、あらためて課題の分割や起票が必要な状態。実施したら完了

課題整理時点で完了可能なものは完了し、実施しない課題についてはクローズする。
あたらしく実施が必要な課題についてはあたらしく起票する。

**Comment by knokmki612** [comment]
現在draft issueになっているものは一通りissueにしてしまおうと思う（でなければ完了か否か表現不可のため）

**Comment by knokmki612** [comment]
> 課題整理時点で完了可能なものは完了し、実施しない課題についてはクローズする。

これらは今のイテレーションに移動し、残タスクのみ次回以降のイテレーションに割り当てられている状態にします。

**Comment by knokmki612** [comment]
実施した。現在は以下のロードマップになっている

![image](https://github.com/npocccties/chiloportal/assets/9744580/bcbe946f-bc35-4f87-a23e-6a0e47368f53)

https://github.com/orgs/npocccties/projects/23/views/1

特定のイテレーションが現実的でない作業量になっているので見直しが必要。  https://github.com/npocccties/oku-private/issues/194 https://github.com/npocccties/oku-private/issues/195 https://github.com/npocccties/oku-private/issues/196 にておこなう。 

- 予想していたベロシティ（現在イテレーションごとに算出しているベロシティとはことなる）: 5
- Iteration 7 のストーリーポイント: 12
- Iteration 8 のストーリーポイント: 13

**Comment by knokmki612** [comment]
未完了で抽出するビューを追加しました。 https://github.com/orgs/npocccties/projects/23/views/4

こちらだと未完了のストーリーポイントが54で、残りの7イテレーションで7.7ポイントのベロシティが必要な計算になります

![image](https://github.com/npocccties/chiloportal/assets/9744580/9168c543-ceb4-4420-8d0c-4de42a348f38)

**Comment by foundationforce** [comment]
この上の[コメント](https://github.com/npocccties/chiloportal/issues/729#issuecomment-1831799719)ですが、
1. Iteration 7,8 は 6, 7に見えます。
2. でIteration番号を入れ換えて集計してみると、Iteration 6のストーリーポイント:13, Iteration 7のストーリーポイント:13に見えます。
3. 単独で一番大きなストーリーポイント8になっているのが#755と分かります。
4. #755を実現するために以下のAPIは使えませんか。フロント側でレスポンスから集計する必要があるかもですが。
    - /portalCategory/list
    - /portalCategory/badges/list
5. 添付のPDFの画面は4.のAPIを使用していると思われます。
[e-ポートフォリオ_カテゴリ一覧_20231130.pdf](https://github.com/npocccties/chiloportal/files/13507898/e-._._20231130.pdf)

**Comment by knokmki612** [comment]
>

**Comment by knokmki612** [comment]
> Iteration 7,8 は 6, 7に見えます。

番号だと齟齬が生じそうなので、日付による期間を明示させてください。

以下のイテレーションです。

- 2024年1月8日～2024年1月21
- 2024年1月22日～2024年2月4日

> でIteration番号を入れ換えて集計してみると、Iteration 6のストーリーポイント:13, Iteration 7のストーリーポイント:13に見えます。

そちらが正しいようです。訂正します。

2024年1月8日～2024年1月21のイテレーション: ストーリーポイント13
![image](https://github.com/npocccties/chiloportal/assets/9744580/62c50fab-b7ff-4199-9581-7e6126ed5ecc)


2024年1月22日～2024年2月4日のイテレーション: ストーリーポイント13
![image](https://github.com/npocccties/chiloportal/assets/9744580/47b95ead-f87b-467c-9c45-f6040f933045)

> 単独で一番大きなストーリーポイント8になっているのが# 755 と分かります。

おっしゃる通りです。値の妥当性は本来複数の開発者でチェックすべきですが、8ポイントにした背景は https://github.com/npocccties/oku-private/issues/195 に書いた通りです。

> #755 を実現するために以下のAPIは使えませんか。フロント側でレスポンスから集計する必要があるかもですが。 

フロント側でレスポンスから集計することで期待するデータを得ることは可能かと思います。ただし、パフォーマンスの観点から問題あると思われます。

以下のステップをふむことで期待するデータが得られるかと思います。

1. /portalCategory/list からカテゴリー一覧を得る
2. 1\. で得た件数 * 各カテゴリーに属する全件の能力ページ数分 /portalCategory/badges/list を呼び カテゴリーに属する能力バッジを得る
3. 3\. で得た能力バッジを発行機関の識別子（issuerId）で抽出して各カテゴリ別に発行機関の能力バッジの件数を得る

> 添付のPDFの画面は4.のAPIを使用していると思われます。
> [e-ポートフォリオ_カテゴリ一覧_20231130.pdf](https://github.com/npocccties/chiloportal/files/13507898/e-._._20231130.pdf)

その画面の実装を知る立場にないので何とも言えませんが、

"教員育成指標選択" という文言が見受けられるので、 /consumer/badges/list に framework_id パラメータを渡したもので能力バッジの一覧を得て、カテゴリーでソートしているようにもみえますね。どうなんでしょう。

**Comment by foundationforce** [comment]
ちなみに、理解し辛いと思いますが、「教員育成指標」で「カテゴリ」を選択すると、「教員育成指標」からではなく、「カテゴリ」側から取得するように動きを変えているはずです。今週付いた機能なのでちゃんと見れてませんけど。

**Comment by knokmki612** [comment]
> ちなみに(https://github.com/npocccties/chiloportal/issues/755)のポータルでの使用箇所は、Figmaの図でいうと赤枠で囲んだところですか

おっしゃる通りです。その箇所は、 @Hidetaro7 さんが要約表示を検討した結果配置されているもので、現状この内容ですすめるかはとくに合意していない認識です（これからそのすり合わせが必要で、今している認識です）

**Comment by ties-makimura** [comment]
以下APIは集約できないのでしょうか？大学トップ以外でも使用する予定がある？

> https://github.com/npocccties/chiloportal/issues/754 発行機関が何件の能力バッジを発行したか分かるようになる
> https://github.com/npocccties/chiloportal/issues/755 発行機関が発行した能力バッジがそれぞれのカテゴリーに何件属しているのか分かるようになる
>

**Comment by knokmki612** [comment]
> https://github.com/npocccties/chiloportal/issues/754 発行機関が何件の能力バッジを発行したか分かるようになる

これについては既存のAPIとしては /portalCategory/badges/list や /portalCategory/list が参考になるのですが、カテゴリーに属する能力バッジの件数が含まれています。

対応としては、https://github.com/npocccties/chiloportal/pull/727 で実装したAPIに能力バッジの件数を含めれば良いかと思っています。

おっしゃるように #755 も /issuers/list に集約してもいいかもしれませんね。ただ、そのための実装が必要で（私がPythonやDjangoの経験に乏しいので）見通しが不透明であることには変わらないと思います。もしかしたら問題なく現実的な作業時間で実装可能かもしれませんし、そうでないかもしれません。

**Comment by knokmki612** [comment]
> 特定のイテレーションが現実的でない作業量になっているので見直しが必要。 https://github.com/npocccties/oku-private/issues/194 https://github.com/npocccties/oku-private/issues/195 https://github.com/npocccties/oku-private/issues/196 にておこなう。

にあるように、議論の対象とすべきものは以下のissueを用意しました。どこからか先は議論の経緯が残しやすいように、そちらのissueで議論をしたいと思っています。

- https://github.com/npocccties/oku-private/issues/194
- https://github.com/npocccties/oku-private/issues/195
- https://github.com/npocccties/oku-private/issues/196

本issueについては、課題整理した本人が実施完了したので完了とするか、課題分析にあやまりがないか、重大な未起票の課題がないかチェックいただき @foundationforce か @ties-makimura さんに完了いただくということにしたいのですが、いかがでしょう。

**Comment by foundationforce** [comment]
課題整理の結果がどうなったのかの確認は取れたので、個々の課題は専用Issueで行うに同意。
issueが閉じていたのに気づかず投稿してすみませんでした。

 @ties-makimura さんが良ければクローズしてください。

**Comment by knokmki612** [comment]
コメントいただけたことの方が重要で、ありがたいと思っております。今後もクローズ済みでも気にせず確認したい事項についてはコメントいただければと思います。

**Comment by knokmki612** [comment]
> 現在ですと，https://github.com/npocccties/chiloportal/issues/672 はもう不要ですよね？ であれば， not planned で閉じておきたいです．

そうですね。Roadmapにて管理しているissue以外にも現在検討しているUIなどでは対応不要なissueはあると思います。それは随時気づいたらNot Plannedとして閉じていいと思います。

#672 についてはおっしゃるように私も対応不要にみえます。なので、閉じていただければよいと思います。Not Planneか判断に迷うようであれば声かけていただければと思います。

**Comment by ties-makimura** [comment]
> https://github.com/npocccties/chiloportal/issues/672 についてはおっしゃるように私も対応不要にみえます。なので、閉じていただければよいと思います。Not Planneか判断に迷うようであれば声かけていただければと思います。

Not Planneしておきました．本issueも閉じておきます．

**Comment by knokmki612** [comment]
> 話全体見ていると，タグ付けするなりして，必要なAPI追加作業はまとめておいた方がいいと感じました．

これは、API実装に関するissueは昨日backendラベルをつけておきました。 https://github.com/npocccties/chiloportal/issues/756 だけUIの実装に関する作業と混ざっているので注意が必要です。
