### ISSUE TITLE
画面単位で必要なAPIの検討

### ISSUE THREAD

**Issue by knokmki612** [npocccties/chiloportal#75]
関連 https://github.com/npocccties/chiloportal/issues/39

https://github.com/npocccties/chiloportal/issues/52 で想定した画面単位で必要なデータ構造、APIについて書き出し、既存のAPIで対応可能なもの、対応不可能なものについて明確化することが目的

ひととおりの画面単位で明確化できたら完了

- [x] #76
- [x] #77
- [x] #78
- [x] #79
- [x] #80 
- [x] #81

**Comment by knokmki612** [comment]
画面上必要な情報とまとまりについて考えながら
スクラッチからER図とAPIエンドポイント、そのレスポンスなどを書いてみました

要件的に必要なもの等網羅できていない気がしますが参考になれば幸いです @dynamis @m-takay  @yoshinobu-etou-id 
https://gist.github.com/knokmki612/6d6d00aa5e84696124cc116df4c178bb

**Comment by m-takay** [comment]
APIの見直しを行いました。
（不要そうなAPIとかキーワード検索については一先ずそのままとしてます。）
https://github.com/npocccties/chiloportal/pull/83

**Comment by dynamis** [comment]
> スクラッチからER図とAPIエンドポイント、そのレスポンスの案などを書いてみました
> 要件的に必要なもの等網羅できていない気がしますが参考になれば幸いです

UI デザインを考えるアクターとしては trainers (学習者？閲覧者？) というのがあるが、実際には学習者に応じた表示の変更とか学習者の学習履歴の管理と言ったことは一切しないので、今の時点では tarainers はデータとしては扱わない気がします。

「能力/知識バッジの階層」と「教育委員会と職種の階層毎に策定する育成指標テーブル」との対応付けを行い、それを表示するポータルという位置づけなのでその辺りは実装する API とは相違がある形ですね。

**Comment by knokmki612** [comment]
> trainers (学習者？閲覧者？) 

これは育成指標（training index）を策定している育成実施者的な想定です（consumerと同じ）

**Comment by knokmki612** [comment]
wikiに #83 の0.9.2との対照表というかチェックリストを用意しました。
https://github.com/npocccties/oku-private/wiki/chiloportal-API%E4%B8%80%E8%A6%A7#%E3%83%9D%E3%83%BC%E3%82%BF%E3%83%AB%E3%82%B5%E3%82%A4%E3%83%88%E3%81%AEapi%E4%B8%80%E8%A6%A7-092-%E6%99%82%E7%82%B9%E3%81%A8%E3%81%AE%E5%AF%BE%E5%BF%9C

**Comment by knokmki612** [comment]
https://github.com/npocccties/oku-private/wiki/chiloportal-API%E4%B8%80%E8%A6%A7 にて必要なAPIに関する検討ができている状態
これをもとにOpenAPIの更新、画面の実装がすすんでいく状態になったという認識
@m-takay もしOpenAPIの更新に関してissueとして個別のタスクにする（例えば不要なAPIエンドポイントを取り除く、語彙の更新など）などあれば随時してもらえればとおもいます（作業の進めやすさという観点でご自身の裁量でおまかせしますという意）
