### ISSUE TITLE
発行機関が何件の能力バッジを発行したか分かるようになる

### ISSUE THREAD

**Issue by knokmki612** [npocccties/chiloportal#754]
現状バックエンドAPIから直接何件発行したか得られるレスポンスは存在しない認識なので、拡張が必要

**Comment by yoshinobu-etou-id** [comment]
@knokmki612 
以下の API で portal_category_id を未指定にすると、total_count に全バッジ数を返しますが、要望を満たせそうでしょうか？
`/portalCategory/badges/list/`

**Comment by knokmki612** [comment]
> 以下の API で portal_category_id を未指定にすると、total_count に全バッジ数を返しますが、要望を満たせそうでしょうか？

`/portalCategory/badges/list` はカテゴリーに所属する能力バッジの件数が得られますね。期待するものは、発行機関（大学、Issuer）別にカテゴリーに所属する能力バッジの件数を集計したものです。

フロント側で既存のAPIから集計した場合の説明を他のissueで書いていたので共有します

> フロント側でレスポンスから集計することで期待するデータを得ることは可能かと思います。ただし、パフォーマンスの観点から問題あると思われます。
> 
> 以下のステップをふむことで期待するデータが得られるかと思います。
> 
> 1. /portalCategory/list からカテゴリー一覧を得る
> 2. 1\. で得た件数 * 各カテゴリーに属する全件の能力バッジ取得のためのページ数分 /portalCategory/badges/list を呼び カテゴリーに属する能力バッジを得る
> 3. 2\. で得た能力バッジを発行機関の識別子（issuerId）で抽出して各カテゴリ別に発行機関の能力バッジの件数を得る

_Originally posted by @knokmki612 in https://github.com/npocccties/chiloportal/issues/729#issuecomment-1833057479_

**Comment by knokmki612** [comment]
https://github.com/npocccties/chiloportal/issues/754#issuecomment-1851292003 は #755 へのコメントになるかと思ったので取り下げておきます

**Comment by knokmki612** [comment]
> 以下の API で portal_category_id を未指定にすると、total_count に全バッジ数を返しますが、要望を満たせそうでしょうか？

全件のバッジを得てから、フロントエンド側でissuerで絞り込めば可能という話ですね？それはおっしゃる通り可能かもしれませんね

**Comment by knokmki612** [comment]
> > 以下の API で portal_category_id を未指定にすると、total_count に全バッジ数を返しますが、要望を満たせそうでしょうか？
> 
> それはおっしゃる通り可能かもしれませんね

一部訂正しますと、total_count はカテゴリーに所属するバッジの件数が得られますね。欲しいものは、発行機関（Issuer）が発行したバッジの件数です。

**Comment by yoshinobu-etou-id** [comment]
確かに issuer 起点ではないから違いますね。
ここに関しては /issuer/badges/list みたいな API が必要でしょうね。

**Comment by UenishiKeita** [comment]
@knokmki612 
/badge/list API作成の対応を行い、PRを作成しました
下記リンクよりご確認いただけますでしょうか。よろしくお願いいたします。
https://github.com/npocccties/chiloportal/pull/780

**Comment by UenishiKeita** [comment]
↑ @yoshinobu-etou-id さんに確認していただき、マージしてOKとのことだったのでhttps://github.com/npocccties/chiloportal/pull/780 はマージいたします

**Comment by knokmki612** [comment]
作業ありがとうございます
このissueのクローズ可能な状態であればクローズしていただいてよいかと存じますが、そのままのようであれば任意のタイミングで状況を私が確認してクローズしておきます。アサインしておきますが特になにか作業をリクエストするものではなく、タスク管理上のものですので気にしないでいただけたら幸いです。

**Comment by knokmki612** [comment]
> @knokmki612 /badge/list API作成の対応を行い、PRを作成しました 下記リンクよりご確認いただけますでしょうか。よろしくお願いいたします。 #780

差分の確認を実施しました。https://github.com/npocccties/chiloportal/issues/765#issuecomment-1855334636 に挙げたような実装になっているようには思いました。動作は未確認です

本件については `/badges/list` エンドポイントに issuer_id パラメーター指定を渡して得られるレスポンスに含まれるtotal_countプロパティを参照すればよい状態になりましたのでクローズします。
