### ISSUE TITLE
発行機関が発行した能力バッジがそれぞれのカテゴリーに何件属しているのか分かるようになる

### ISSUE THREAD

**Issue by knokmki612** [npocccties/chiloportal#755]
現状発行機関が発行した能力バッジがそれぞれのカテゴリーに何件属しているのか分かるAPIレスポンスは存在しないので、拡張が必要

**Comment by yoshinobu-etou-id** [comment]
@knokmki612 
以下の API に portal_category_id 未指定時に全バッジを返すのとバッジ個別に portal_category_id を返してますので、
クライアント側で portal_category_id で集計を取ればカテゴリ毎のバッジ数が分かるかと思いますが、要望を満たせそうでしょうか？
`/portalCategory/badges/list/`

**Comment by knokmki612** [comment]
> 以下の API に portal_category_id 未指定時に全バッジを返すのとバッジ個別に portal_category_id を返してます

これはページネーションされているかと思いますが、ページネーション対応（ページが分割されていれば、ページ数分フロントエンド側で取得して集計）が必要という認識であってますでしょうか。

> クライアント側で portal_category_id で集計を取ればカテゴリ毎のバッジ数が分かるかと思いますが、要望を満たせそうでしょうか？

ほしいものとしては、発行機関毎カテゴリ毎のバッジ数なのですが、いずれにせよ、フロントエンド側で集計することも可能という話には同意します

フロント側で既存のAPIから集計した場合の説明を他のissueで書いていたので共有します（portal_category_id 未指定で全件の能力バッジが返されるのであれば1\.は省略可能ですね）

> フロント側でレスポンスから集計することで期待するデータを得ることは可能かと思います。ただし、パフォーマンスの観点から問題あると思われます。
> 
> 以下のステップをふむことで期待するデータが得られるかと思います。
> 
> 1. /portalCategory/list からカテゴリー一覧を得る
> 2. 1\. で得た件数 * 各カテゴリーに属する全件の能力バッジ取得のためのページ数分 /portalCategory/badges/list を呼び カテゴリーに属する能力バッジを得る
> 3. 2\. で得た能力バッジを発行機関の識別子（issuerId）で抽出して各カテゴリ別に発行機関の能力バッジの件数を得る

_Originally posted by @knokmki612 in https://github.com/npocccties/chiloportal/issues/729#issuecomment-1833057479_

**Comment by yoshinobu-etou-id** [comment]
@knokmki612 

> これはページネーションされているかと思いますが、ページネーション対応（ページが分割されていれば、ページ数分フロントエンド側で取得して集計）が必要という認識であってますでしょうか。

はい。ページネーション対応済みの API ですので、問題ないかと思ってます。

**Comment by knokmki612** [comment]
> ページネーション対応（ページが分割されていれば、ページ数分フロントエンド側で取得して集計）が必要

UIとしてはページネーション表示が必要な箇所ではなく、集計の手間が生じますので、その点で言えばページネーションではなく1度に該当件数すべて返された方が（もっといえばフロントエンド側での集計処理不要であった方が）うれしくはあります。

**Comment by knokmki612** [comment]
`/issuer/portalCategory/badges/list` のようなAPIを用意して、それにあるissuerに属するあるカテゴリーの能力バッジの一覧と件数が返される
ようなものがあるのもアリかとおもいました @ties-makimura さんからのご提案

**Comment by m-takay** [comment]
@knokmki612 ページネーション機能のあるAPIでpage_numberを省略すると全件返す仕様になっているそうなのですが、確認されたら本件Close願います。

**Comment by knokmki612** [comment]
動作確認は未実施です。

ソースコードを確認しました。以下の実装であることを確認しました。

- https://github.com/npocccties/chiloportal/commit/1472f6a6354372309315c415e0e91c76b00782dd にて to_pager_wisdom_badges_all（全件返す関数）とto_pager_wisdom_badges（ページネーション件数分返す関数）が実装されている
- https://github.com/npocccties/chiloportal/commit/91f3da6f5c93e9c19a3ab0572d1bcfad24b42043 にて `portalCategories/badges/list/` 実装時上記関数が使用されている。また、page_numberクエリパラメーター未使用時全件返される
- https://github.com/npocccties/chiloportal/commit/e76133ab9096358a54df7f6862c9cae286d64769 にて `wisdomBadges/list/keyword/` 実装時上記関数が使用されている。また、page_numberクエリパラメーター未使用時全件返される

この実装だとむしろ現在のフロントエンド実装が意図しない実装になっている（検索結果画面やポータルカテゴリー別バッジ一覧画面でページネーション対応しているにもかかわらず1ページ目で全件バッジが表示される）ので、この点修正する必要があると思いましたので起票しておきます

また、これらのクエリパラメーター未指定時の振る舞いはドキュメンテーションされていることが望ましいように思えますので、OpenAPIドキュメントを更新するためのissueについても起票しておきます

**Comment by m-takay** [comment]
> @knokmki612 ページネーション機能のあるAPIでpage_numberを省略すると全件返す仕様になっているそうなのですが、確認されたら本件Close願います。

上記ですが、#765のコメントを見る前に書いてしまったので取り下げます。
本issueは、/badges/list APIの新規実装で対応される認識です。失礼しました。

**Comment by knokmki612** [comment]
> 本issueは、/badges/list APIの新規実装で対応される認識です。失礼しました。

コメントの確認ありがとうございます。いくつかのissueに分散してやりとりしているので、ご負担お掛けしております。

一応、以下コメント書いてしまったので、これはこれで残して共有いたします。

---

> 確認されたら本件Close願います。

`/portalCategory/badges/list/` に portal_category_id 未指定時全ポータルカテゴリーに所属する能力バッジが返される、かつ、page_number 未指定時全件の能力バッジが返されるということは分かりました。
これが意味するところは「あらゆる能力バッジを全件返す」ということなので、言ってしまえば能力バッジに関する部分集合が欲しければフロントエンド側で取得できるレスポンスの範囲で任意の部分集合が得られるということだと思います。
その意味でいえば、本件以外にも #755 #774 も解決可能でしょう。

しかしそれでAPI設計として妥当なのかは私には判断しかねます。「現状のAPI実装としてはそのようになっているので、それに合わせてフロントエンドの実装をおこなってください」という決定をTIESさん @ties-makimura  がされるならそれに従おうと思います。
あるいは今以上のバックエンド実装が必要であれば @knokmki612 がやる、それが無理であれば現状のAPI実装に合わせてフロントエンドの実装をおこなうことを最低限の対応にする、などの幅を持たせる方針でもよいです。

**Comment by knokmki612** [comment]
https://github.com/npocccties/chiloportal/issues/755#issuecomment-1867308190 のコメントで方針に関して言及しましたが、
一応、本件への対応含めた方針は https://github.com/npocccties/oku-private/issues/197#issuecomment-1855387170 に記載した通りで、それについては現時点も変更なしというつもりではおります。

**Comment by m-takay** [comment]
@knokmki612 年明け1/8以降使えるように、今から実装に着手します。

**Comment by knokmki612** [comment]
ご対応ありがとうございます。色々関係者が絡んだり間接的にやりとりする形になりご不便お掛けしているかもしれませんが、助かっております。。

**Comment by knokmki612** [comment]
https://github.com/npocccties/chiloportal/pull/780 にて実装された `/badges/list` エンドポイントを使用し、issuer_id パラメーター、portal_category_id パラメーターを指定して得られるレスポンスに含まれるtotal_countプロパティをカテゴリー件数分集計すればよい状態になりましたのでクローズします。
