### ISSUE TITLE
能力バッジを探す画面で大学別に能力バッジをフィルタリングできる

### ISSUE THREAD

**Issue by knokmki612** [npocccties/chiloportal#756]
TODO

- [x] #774

スクリーンショット

![image](https://github.com/npocccties/chiloportal/assets/9744580/e2f94f7a-1abb-4f40-ba4e-60f1edcece2a)

**Comment by yoshinobu-etou-id** [comment]
@knokmki612 
以下の バッジ一覧取得 API がありますが、framework_id / stage_id を指定する形になってます。
`/consumer/badges/list/?framework_id=1&stage_id=1`

要望を満たせそうかご確認をお願い致します。

**Comment by knokmki612** [comment]
> 要望を満たせそうかご確認をお願い致します。

回答ありがとうございます。ここでいう「大学」は、ConsumerではなくIssuerのことを指しておりまして、 `/issuer/badges/list` のようなものが必要と考えています。

**Comment by knokmki612** [comment]
タスク管理の観点で、API実装に関するタスクは #774 に分割しました。ストーリーポイントも分割し、合計値は変わらないようにします。
