### ISSUE TITLE
全件の能力バッジの一覧が得られるようになる

### ISSUE THREAD

**Issue by knokmki612** [npocccties/chiloportal#757]
現状全件の能力バッジの一覧が（ページネートされて）得られるAPIレスポンスは存在しない。拡張が必要。

**Comment by ties-makimura** [comment]
@yoshinobu-etou-id 

portal_category_id を入力が必須のようですが未指定可能なのでしょうか
![image](https://github.com/npocccties/chiloportal/assets/8957521/60abea3a-7f72-4c90-a425-e3f7b19368c2)

**Comment by knokmki612** [comment]
https://github.com/npocccties/chiloportal/pull/714 の変更で可能になった様です。OpenAPIドキュメントの更新は必要かと思いました。

**Comment by yoshinobu-etou-id** [comment]
@knokmki612 
そういえば更新できてなかったと思いますので、更新しておきます。

**Comment by yoshinobu-etou-id** [comment]
更新しておきました。

**Comment by knokmki612** [comment]
39c23596f00888577f167470ad733edcb5a3ad34 ですね。ありがとうございます

**Comment by knokmki612** [comment]
#714 #770 の対応をもって完了とみなそうと思います。一応etouさんにアサインをつけておきますが完了しますので気になさらず。

**Comment by knokmki612** [comment]
動作確認実際のバックエンドサーバー（開発環境or本番環境）での動作確認が必要なら再オープンをお願いします。
