### ISSUE TITLE
ポータルトップ画面に必要なAPIの明確化

### ISSUE THREAD

**Issue by knokmki612** [npocccties/chiloportal#76]
Figma https://www.figma.com/file/dCE06JShf29eqnvZ4vcE8U/OKUTEP?node-id=121%3A1583

### 教育委員会から探す

![image](https://user-images.githubusercontent.com/9744580/189095823-376fec4a-7dd3-4f2b-a833-81972bc382fa.png)

コンシューマーの一覧を取得し遷移先の画面のurl等を生成できればよさそうに思う

以下のAPIで対応可能そう

https://github.com/npocccties/chiloportal/blob/0111c22aa756e9396f1e51461d0a39bf87b576a1/backend/doc/openapi.yaml#L66-L70

### カテゴリから能力バッジを探しましょう

![image](https://user-images.githubusercontent.com/9744580/189099598-5f96fbb9-a365-4264-af41-6afd83ec6636.png)

能力バッジの属性として付与されるカテゴリーの一覧をここに表示したい

- カテゴリのタイトル
- カテゴリのイラスト
- カテゴリの説明
- カテゴリに所属する能力バッジの件数（本当に必要？）
- ~~サブカテゴリの件数（サブカテゴリは存在する？）~~

あたりの情報が必要で、現状のカテゴリのモデルでは不足しているようにおもう

ただしこれは現状のテーブルにおけるcellとひもづいたカテゴリとは別途管理されるカテゴリになるかもしれない
いちおう以下が前者のカテゴリ一覧を取得するAPI

https://github.com/npocccties/chiloportal/blob/0111c22aa756e9396f1e51461d0a39bf87b576a1/backend/doc/openapi.yaml#L83-L87

---

<details>
<summary>バックエンドでの処理が不要になったので省略</summary>

### 記事

スクリーンショットなし

チロポータルに関するアナウンス等を記事として公開してその動線を用意したい

記事については現状のテーブルに存在しないのでチロポータルのDBに記事データを管理したいのであればそのモデリングが必要
記事はチロポータルシステム外で作成して記事一覧を取得して表示するなど検討していい気がする

### おすすめのバッジ

スクリーンショットなし

現状以下2種類検討されている

- Moodleでの受講者数が多いコースにひもづいた能力バッジ
- Moodleでのコース完了？（能力バッジを獲得できたとみなされる）者数が多いコースにひもづいた能力バッジ

また件数については上位3件でよいのではという話になっている

対応するAPIはない認識

### 少ない回数で能力バッジを獲得しましょう

少ない回数（少ない知識バッジ）で獲得できるの能力バッジの上位3件を取得したい

個人的には少ない回数だからといって獲得しやすいかとは別の話だとおもう（知識バッジのボリュームや取り扱う内容そのものの難しさなどに依存する）ので、獲得しやすさのために表示するのは不適とおもった
というのはともかくこの辺のおすすめのバッジはいずれか1種類が用意できていればひとまずいいという気がする

![image](https://user-images.githubusercontent.com/9744580/189098142-25ef6ead-3c6c-454c-81b5-64e2bf651c6e.png)

対応するAPIはない認識

### 能力バッジがない学習コンテンツもあります

能力バッジが発行されていないコースへの動線が必要という話がでている。ひとまず画面上にハードコーディングされているのでいいという気がする

</details>

**Comment by dynamis** [comment]
> ### 記事
> スクリーンショットなし
> 
> チロポータルに関するアナウンス等を記事として公開してその動線を用意したい
> 
> 記事については現状のテーブルに存在しないのでチロポータルのDBに記事データを管理したいのであればそのモデリングが必要 記事はチロポータルシステム外で作成して記事一覧を取得して表示するなど検討していい気がする

こちらは JAMStack のブログなどの実装で良くある md ファイル置いたらページが出来る、ページのリストが表示されるもの、DB には一切入れずに生成する想定で良いかと思います。

DB に入れ始めると CMS の再発明になってしまうので。

> ### おすすめのバッジ
> スクリーンショットなし
> 
> 現状以下2種類検討されている
> 
> * Moodleでの受講者数が多いコースにひもづいた能力バッジ
> * Moodleでのコース完了？（能力バッジを獲得できたとみなされる）者数が多いコースにひもづいた能力バッジ
> 
> また件数については上位3件でよいのではという話になっている
> 
> 対応するAPIはない認識

知識バッジ数とか、受講者が多いとか、獲得数が多いとか、何らかの基準で「おすすめ」バッジをリスト表示する機能についてはフロントエンド側だけで対応することにする。

具体的には yml か json で例えば次のような項目を定義しそれを表示するようにする

- featuredBadges
  - title: 「簡単に取れるバッジ」「今月のオススメ」などのラベル
  - description: 「まずは短時間でバッジが取得できる教材で学んでみましょう」とか「チロポータルからオススメするバッジです！」などの説明ラベル (実際にはもう少し長い 1-2 行テキスト？
  - badgeIds: オススメするバッジの id リスト

バッジの名前その他はバッジリストの API で取得して表示する。追加 API は不要。

https://github.com/npocccties/chiloportal/blob/0111c22aa756e9396f1e51461d0a39bf87b576a1/backend/doc/openapi.yaml#L353-L369

見せ方や表示上限についてはいくつかのバリエーションがあるがいずれにしてもそれはフロント側で解決する。

汎用的な形に将来していくには featuredBadges を DB 上に入れて...とかしても良いが、結局 featured badge の選択が手動管理になるのであれば、取りあえずはフロント側の対応で済ませて良さそう。もしそれを JSON 編集するのが嫌ならそこだけ別途 microCMS などで編集するといった手法もあり得るもので、CP 側で実装を頑張りすぎない方が良い。

> ### 少ない回数で能力バッジを獲得しましょう
> 少ない回数（少ない知識バッジ）で獲得できるの能力バッジの上位3件を取得したい
> 
> 個人的には少ない回数だからといって獲得しやすいかとは別の話だとおもう（知識バッジのボリュームや取り扱う内容そのものの難しさなどに依存する）ので、獲得しやすさのために表示するのは不適とおもった というのはともかくこの辺のおすすめのバッジはいずれか1種類が用意できていればひとまずいいという気がする
> 
> ![image](https://user-images.githubusercontent.com/9744580/189098142-25ef6ead-3c6c-454c-81b5-64e2bf651c6e.png)
> 
> 対応するAPIはない認識

上記「おすすめのバッジ」と同じようにフロントで手動管理したバッジリストを表示する実装にする。API は増やさない。

> ### カテゴリから能力バッジを探しましょう
> ![image](https://user-images.githubusercontent.com/9744580/189099598-5f96fbb9-a365-4264-af41-6afd83ec6636.png)
> 
> 能力バッジの属性として付与されるカテゴリーの一覧をここに表示したい
> 
> * カテゴリのタイトル
> * カテゴリのイラスト
> * カテゴリの説明
> * カテゴリに所属する能力バッジの件数（本当に必要？）
> * サブカテゴリの件数（サブカテゴリは存在する？）
> 
> あたりの情報が必要で、現状のカテゴリのモデルでは不足しているようにおもう

現状 name, description, sortKey しかないのでカテゴリのイラストは image か何かのフィールドを追加して登録可能にする必要がありそう。API としてはカテゴリリストを取得する API だけで追加は不要。

image フィールドに入れる値は画像ファイル名 (決まったパスのは以下にあるファイル名)、画像 URL、画像バイナリなどいくつかの選択肢があり、整合性が壊れにくいのはバイナリデータだが、画像の額台縮小・レスポンシブ対応の可能性を考えるならファイル名だけにしておく方が良いかも。

所属能力バッジ件数は portal_category テーブルを追加したばかりで API が実装されていない。必要であれば追加することになるが必要か？

サブカテゴリは現在のバッジマップ (バッジマップの整理V3.xlsx) では定義されていないのでサブカテゴリ数の表示は不要のハズ。

> ただしこれは現状のテーブルにおけるcellとひもづいたカテゴリとは別途管理されるカテゴリになるかもしれない いちおう以下が前者のカテゴリ一覧を取得するAPI
> 
> https://github.com/npocccties/chiloportal/blob/0111c22aa756e9396f1e51461d0a39bf87b576a1/backend/doc/openapi.yaml#L83-L87
> 
> ### 能力バッジがない学習コンテンツもあります
> 能力バッジが発行されていないコースへの動線が必要という話がでている。ひとまず画面上にハードコーディングされているのでいいという気がする

能力バッジが発行されていないコースは LMS 上にまとめられた 1 ページがありそこにリンクすることを想定しており、DB や API の追加は不要。

もし CP 上でも具体的な項目を列挙して紹介するような形にするのであれば、それは久野さんの言うとおりフロントエンドでハードコーディング (あるいはそれを定義する json/yml あたりに分離) 可能にすれば良い。

**Comment by knokmki612** [comment]
以降は https://github.com/npocccties/oku-private/wiki/chiloportal-API%E4%B8%80%E8%A6%A7#%E3%83%9D%E3%83%BC%E3%82%BF%E3%83%AB%E3%83%88%E3%83%83%E3%83%97 でAPIとして用意されているか等管理されるのでそちらを参照してください
