### ISSUE TITLE
ポータルサイト改修に必要なAPI整理

### ISSUE THREAD

**Issue by ties-makimura** [npocccties/chiloportal#765]
確認できたらクローズ

MUST（1月8日からの作業で使う）
- https://github.com/npocccties/chiloportal/issues/754
- https://github.com/npocccties/chiloportal/issues/755

MUST
- https://github.com/npocccties/chiloportal/issues/774
- https://github.com/npocccties/chiloportal/issues/757

SHOULD
- https://github.com/npocccties/chiloportal/issues/669

MAY
- https://github.com/npocccties/chiloportal/issues/663
  現状は力業で解決させているが，きちんとソート番号振る対応をする
- https://github.com/npocccties/chiloportal/issues/751

確認．対応済みならクローズにしておく
- https://github.com/npocccties/chiloportal/issues/643
- https://github.com/npocccties/chiloportal/issues/647

**Comment by knokmki612** [comment]
https://github.com/npocccties/chiloportal/issues/754 https://github.com/npocccties/chiloportal/issues/755 https://github.com/npocccties/chiloportal/issues/756 が解決可能なAPI案

- `/badges/list` エンドポイント：汎用的な能力バッジ一覧API。（`/portalCategory/badges/list` 廃止可能。互換性のため当面残すこともできる）
  - パラメーター
    - `issuer_id` 指定すると、指定した発行機関で絞り込む。未指定の場合、発行機関では絞り込まない
    -  `portal_category_id` 指定すると、指定したポータルカテゴリーで絞り込む。未指定の場合、ポータルカテゴリーでは絞り込まない
  - レスポンス
    - `total_count`: パラメーター指定して絞り込んだ結果に該当する能力バッジの件数
    - `badges`: ページネーションされたバッジ

_Originally posted by @knokmki612 in https://github.com/npocccties/oku-private/issues/197#issuecomment-1855212052_

**Comment by knokmki612** [comment]
https://github.com/npocccties/chiloportal/issues/765#issuecomment-1855238631 について `/portalCategory/bages/list` を参考に作成したOpenAPIドキュメント

```yaml
  /badges/list:
    get:
      tags:
        - badges list
      description: 能力バッジ一覧を返却します
      operationId: findBadgesList
      parameters:
        - name: issuer_id
          in: query
          description: issuer id
          required: false
          schema:
            type: integer
            format: int64
        - name: portal_category_id
          in: query
          description: portal category id
          required: false
          schema:
            type: integer
            format: int64
        - name: page_number
          in: query
          description: page number
          required: false
          schema:
            type: integer
            format: int64
      responses:
        '200':
          description: Successful operation
          content:
            application/json:
              schema:
                type: object
                properties:
                  badges:
                    type: array
                    items:
                      $ref: '#/components/schemas/BadgeDetail2'
                  total_count:
                    type: integer
                    format: int64
                    example: 101
                  start:
                    type: integer
                    format: int64
                    example: 1
                  end:
                    type: integer
                    format: int64
                    example: 30
                additionalProperties: false
                required:
                  - badges
                  - total_count
                  - start
                  - end
        '400':
          description: Invalid parameters supplied
```

@knokmki612 が想定する仕様に関する一問一答（正式なものは後日確定される認識）

- `issuer_id` パラメーターと `portal_cateogry_id` パラメーターの両方を指定したらどのような能力バッジが返される
    - 該当するissuerとportalCateogryの両方（AND）に属する能力バッジが返される
- `issuer_id` パラメーターと `portal_cateogry_id` パラメーターの両方を指定したらどのような `total_count` が返される
    - 該当するissuerとportalCateogryの両方（AND）に属する能力バッジの件数が返される

**Comment by knokmki612** [comment]
@ties-makimura クローズできそうでしたらクローズをお願いします :pray:

**Comment by ties-makimura** [comment]
今期の整理は終了
