### ISSUE TITLE
カテゴリトップ画面に必要なAPIの明確化

### ISSUE THREAD

**Issue by knokmki612** [npocccties/chiloportal#77]
Figma https://www.figma.com/file/dCE06JShf29eqnvZ4vcE8U/OKUTEP?node-id=196%3A1112

### 子ども・人理解

![image](https://user-images.githubusercontent.com/9744580/189102988-3533179e-cfe7-4ffd-9183-835a091243b3.png)

- タイトル
- 説明
- 能力バッジ件数
- イラスト

あたりの情報が必要で、現状のカテゴリのモデルでは不足しているようにおもう

ただしこれは現状のテーブルにおけるcellとひもづいたカテゴリとは別途管理されるカテゴリになるかもしれない
いちおう以下が前者のカテゴリ一覧を取得するAPI

https://github.com/npocccties/chiloportal/blob/0111c22aa756e9396f1e51461d0a39bf87b576a1/backend/doc/openapi.yaml#L111-L115

### 絞り込み

ポータルカテゴリでの絞り込みが必要

<details>
<summary>古いので省略</summary>

![image](https://user-images.githubusercontent.com/9744580/189103642-f5cf9b1b-894a-4b82-88ae-1b296a19cdd2.png)

正直個人的にはこの箇所で関連した教育指標の一覧が出てくるのは、この画面としては教育指標によらずバッジを探索する人が到達するはずなので不適という気がしている

必要な場合あるカテゴリに属する能力バッジ-カテゴライズドバッジ-セル-職業（育成指標）で職業を集計して職業の一覧を得る必要があるように思う

![image](https://user-images.githubusercontent.com/9744580/189103922-8b29aac1-01c5-433e-b297-4a534b0cb059.png)

絞りこみとしては

- コンシューマのセレクタ
- 選択したコンシューマに関連する育成指標（職業）のセレクタ
- 選択した育成指標に関連する成長段階（キャリアステージ）のセレクタ（単一セレクタでなく複数セレクタになっているけど成長段階の表示が定まらないのでは）
- 選択した成長段階に関連する指標項目（カテゴリ）のチェックボックスリスト（単一セレクタでなく複数セレクタになっているけど本当に複数選択必要？）

ができるAPIがそれぞれ必要

</details>

### 能力バッジのリスト

![image](https://user-images.githubusercontent.com/9744580/189106771-66d72fb1-019a-418a-90a5-43e22c9d7875.png)

それぞれの能力バッジについて

- 画像
- バッジの名称
- 発行者
- 発行者の画像
- ~~関連する育成指標（職業）の件数~~
  - ~~能力バッジ-カテゴライズバッジ-セル-育成指標（職業）の件数の集計が必要？~~
- 説明
- 知識バッジの件数

あたりの情報が必要

一覧の並びは何になる？登録順？複数の並びが考えられるならば並べ替えの見た目と並びの指定のためのAPIパラメータが必要だが今のところ存在しない

いちおう以下のAPIに対応する

https://github.com/npocccties/chiloportal/blob/0111c22aa756e9396f1e51461d0a39bf87b576a1/backend/doc/openapi.yaml#L353-L357

絞り込んだ結果が反映される必要があるので絞り込んだ場合はいちおう以下のAPIに対応する

ただしキーワード検索のみが想定されているので現状絞り込み的なパラメータは存在しない

https://github.com/npocccties/chiloportal/blob/0111c22aa756e9396f1e51461d0a39bf87b576a1/backend/doc/openapi.yaml#L215-L219

**Comment by dynamis** [comment]
> ### 絞り込み
> ![image](https://user-images.githubusercontent.com/9744580/189103642-f5cf9b1b-894a-4b82-88ae-1b296a19cdd2.png)
> 
> 正直個人的にはこの箇所で関連した教育指標の一覧が出てくるのは、この画面としては教育指標によらずバッジを探索する人が到達するはずなので不適という気がしている
> 
> 必要な場合あるカテゴリに属する能力バッジ-カテゴライズドバッジ-セル-職業（育成指標）で職業を集計して職業の一覧を得る必要があるように思う
> 
> ![image](https://user-images.githubusercontent.com/9744580/189103922-8b29aac1-01c5-433e-b297-4a534b0cb059.png)

Consumer, Training Index などでの絞り込みはサイトのトップ「育成指標から探す」を使う、横断した表示をすることはほぼない、のでここの検索は無くすことに。ひとまずはポータルカテゴリやキーワード (全文検索) の検索だけとする。

> ### 能力バッジのリスト
> ![image](https://user-images.githubusercontent.com/9744580/189106771-66d72fb1-019a-418a-90a5-43e22c9d7875.png)
> 
> それぞれの能力バッジについて
> 

> 一覧の並びは何になる？登録順？複数の並びが考えられるならば並べ替えの見た目と並びの指定のためのAPIパラメータが必要だが今のところ存在しない

バッジの並び順はどうするべきか決まっていない。今回の時点では DB 登録順 = Primary Key 順だけで良く、今後どのような順序で並べ替えをしたいのかというのが明確になってきたら実装をする。

**Comment by knokmki612** [comment]
以降は https://github.com/npocccties/oku-private/wiki/chiloportal-API%E4%B8%80%E8%A6%A7#%E3%82%AB%E3%83%86%E3%82%B4%E3%83%AA%E3%83%88%E3%83%83%E3%83%97 でAPIとして用意されているか等管理されるのでそちらを参照してください
