### ISSUE TITLE
最新のフロントエンドを確認可能な環境の整備

### ISSUE THREAD

**Issue by knokmki612** [npocccties/chiloportal#793]
現状のフロントエンド開発では、ローカルで開発サーバーを起動して確認している。
他のチームメンバーが容易に最新のフロントエンドの開発状況の確認や、動作確認をするための方法について、確認できたら完了。

前回の開発時に用意した環境がそのまま使えるか、使えるとしたらどのような方法か、などについて @ties-makimura さんとの確認が必要だと考えています。

**Comment by knokmki612** [comment]
https://dev-portal.oku.cccties.org/ は、おそらく最新のフロントエンドでデプロイされていない。

![image](https://github.com/npocccties/chiloportal/assets/9744580/a1673b13-abc8-4c3e-bf28-eefaac2528d2)

**Comment by knokmki612** [comment]
https://test-portal.oku.cccties.org/ は閉鎖済み？

**Comment by ties-makimura** [comment]
> https://test-portal.oku.cccties.org/ は閉鎖済み？

閉鎖済みです。こちらについては再びどこかで起動しておきます。

**Comment by ties-makimura** [comment]
> https://dev-portal.oku.cccties.org/ は、おそらく最新のフロントエンドでデプロイされていない。こちら https://github.com/npocccties/chiloportal/actions/workflows/cd.yml の GitHub Actions でデプロイされているものではなく、手動デプロイされている？（要確認）

- https://github.com/npocccties/chiloportal/issues/782
が原因で自動デプロイ失敗している可能性がある。
そのため，解消するまで現在dev-portalは手動デプロイしている。

**Comment by ties-makimura** [comment]
https://dev-portal.oku.cccties.org/ で今季の確認できる状態になったのでクローズ
