### ISSUE TITLE
「バッジを探す」→「学びを探す」

### ISSUE THREAD

**Issue by knokmki612** [npocccties/chiloportal#798]
https://github.com/npocccties/chiloportal/blob/7945474285fcbe44e693c658820b88de6b08672c/frontend/templates/Top.tsx#L27

https://github.com/npocccties/chiloportal/blob/7945474285fcbe44e693c658820b88de6b08672c/frontend/templates/Discover.tsx#L206-L208

デザインの検討を踏まえて実施するか決まる想定です

**Comment by Hidetaro7** [comment]
プロジェクト全体のメッセージ性、コンセプトワードに影響する内容です。

ref: https://github.com/npocccties/oku-private/issues/192

**Comment by knokmki612** [comment]
はい。コンセプトに照らし合わせて不適ということであれば対応せずクローズしましょう。

**Comment by knokmki612** [comment]
背景：バッジを探すという画面の用途のラベリングを見直したい

**Comment by Hidetaro7** [comment]
Figmaのブランチで作業しています、レビューをお願いします。 @knokmki612

**Comment by Hidetaro7** [comment]
Figmaでは反映された。開発のissueなので実装されたら完了するかどうか？
デザインで反映されたなら閉じてもいいと思うがお任せします。

**Comment by knokmki612** [comment]
> 開発のissueなので実装されたら完了するかどうか？

開発のissueなので実装されたら完了します。
