### ISSUE TITLE
育成指標から成長段階を選ぶ画面に必要なAPIの明確化

### ISSUE THREAD

**Issue by knokmki612** [npocccties/chiloportal#80]
Figma https://www.figma.com/file/dCE06JShf29eqnvZ4vcE8U/OKUTEP?node-id=250%3A2424

### 堺市教育委員会

![image](https://user-images.githubusercontent.com/9744580/189116226-ef0811df-5ec8-42f7-a96e-327e070f3615.png)

以下のAPIに対応する

https://github.com/npocccties/chiloportal/blob/0111c22aa756e9396f1e51461d0a39bf87b576a1/backend/doc/openapi.yaml#L40-L44

### 育成指標（職業）/成長段階（キャリアステージ）

![image](https://user-images.githubusercontent.com/9744580/189117873-2b3f92a5-a831-4a8e-8d19-c9bd29d3502e.png)

![image](https://user-images.githubusercontent.com/9744580/189117956-92a7baaf-02b6-4cd8-ab27-1bbd2d077557.png)

- コンシューマに関連する育成指標（職業）
- 育成指標（職業）に関連する成長段階（キャリアステージ）

あたりの情報が必要

この画面の粒度としてはコンシューマ単位ではあるのでコンシューマ/育成指標（職業）/成長段階（キャリアステージ）の階層を持ったレスポンスが返ってくるAPIがあると楽かもしれない（またそれぞれの階層の並びの保持が必要？）

**Comment by dynamis** [comment]
育成指標から成長段階リストを得るのは現状では一括で呼べないのを複数回の fetch が必要だがサーバが HTTP/2 以降であれば並列 fetch できるしサーバの負荷も利用者数が増えなければ大したことはないだろうから取りあえずはクライアント側での並列 fetch で取得する想定になった。

**Comment by knokmki612** [comment]
以降は https://github.com/npocccties/oku-private/wiki/chiloportal-API%E4%B8%80%E8%A6%A7#%E8%82%B2%E6%88%90%E6%8C%87%E6%A8%99%E3%81%8B%E3%82%89%E6%88%90%E9%95%B7%E6%AE%B5%E9%9A%8E%E3%82%92%E9%81%B8%E3%81%B6 でAPIとして用意されているか等管理されるのでそちらを参照してください
