### ISSUE TITLE
トップに並ぶバナーは任意に表示したい

### ISSUE THREAD

**Issue by ties-makimura** [npocccties/chiloportal#809]
issuerが全て表示されるのではなく，任意のissuerのみ表示させたり，issuerと関係ないバナーと外部リンクを表示させたい

現状だと以下のような状況が出た場合に困る
- トップには表示させないissuerが出た場合
- 単純に外部スポンサーが出た場合
- issuerでも大学のホームページなど，/issuers/ 以外にリンクを向けたい場合

**Comment by Hidetaro7** [comment]
@ties-makimura 
現在、トップページの印象を崩さないために、学校のロゴをモノクロにしているのですが、そういったルールは今後適用できそうですか？

例 https://nuxt.com/

おそらく営業的に考えるとあまり制約を設けないほうがやりやすいという意見はあるかと思いますが、見た目の印象が変わってくるような気がします。

静的なHTMLとして生成する実装でよければ（変更都度でビルドが必要）、外観やレイアウトにおけるルールを定めておけば良いと思われますが、 最終的な判断として @knokmki612 さんのご意見が欲しいと思います。

**Comment by knokmki612** [comment]
トップページにおいてIssuer以外に表示するコンテンツを制御したい、というのは見た目だけではなくコンテンツ管理の機能に変更、整理が必要です。
やるのだとしても次回の改修期間に取り組ませてください。

**Comment by ties-makimura** [comment]
> 現在、トップページの印象を崩さないために、学校のロゴをモノクロにしているのですが、そういったルールは今後適用できそうですか？

外部バナーを登録するとなった場合は先方の規約によるので分からないです。
モノクロOKかどうかは毎回確認が必要そうですね。

**Comment by horimasumi** [comment]
バナーもコンテンツ管理に影響するのでしょうか。
あまり，きっちり作ると自由度がなくて，かえって使いにくくなるような気がしています。
トップページのバナーの出し入れは，しょっちゅう変わらないので，とりあえず，静的なHTMLで良いと思います。

**Comment by ties-makimura** [comment]
> 現状の実装では利用者が差し替え可能な部分的なHTMLの挿入などは想定していないので、機能の実装が必要です。やるのだとしても次回の改修期間に取り組ませてください。

@knokmki612 

運用的な話ですと，とりあえず現状は以下を直接変更しておけば，バナー追加などはできますよね？
https://github.com/npocccties/chiloportal/blob/develop/frontend/templates/Top.tsx#L35-L41

**Comment by knokmki612** [comment]
その箇所のテンプレート（JSX）を変更すれば描画されるHTML要素を変えることはできますが、期待する内容にカスタマイズ可能かは不明です。

また、ソースコードを変更した部分については、最新のソースコードに更新した際に変更が保持されず、また、競合が発生する可能性がありますので注意してください。

**Comment by Hidetaro7** [comment]
バナーの大きさとバナーの余白のルールは決めておいたほうがいい。
Figmaにて見た目がわかればよいかと思われる。

認識はあったのでクローズする。

**Comment by knokmki612** [comment]
> > 現状の実装では利用者が差し替え可能な部分的なHTMLの挿入などは想定していないので、機能の実装が必要です。やるのだとしても次回の改修期間に取り組ませてください。
> 
> @knokmki612
> 
> 運用的な話ですと，とりあえず現状は以下を直接変更しておけば，バナー追加などはできますよね？ https://github.com/npocccties/chiloportal/blob/develop/frontend/templates/Top.tsx#L35-L41

#827 にてカスタマイズのための機能を用意したので、代わりにそちらを使ってください。カスタマイズの方法についてはexamplesやREADMEを参照してください。
