### ISSUE TITLE
APIのレスポンスに含まれるプロパティを厳格化したい

### ISSUE THREAD

**Issue by knokmki612** [npocccties/chiloportal#82]
`additionalProperties: true` がデフォルト値として使われるが、この場合任意のプロパティが含まれうることになるので、 `additionalProperties: false` などとして定義済みのプロパティ以外含まれないことを表明したい

> additionalProperties - Value can be boolean or object. Inline or referenced schema MUST be of a [Schema Object](https://swagger.io/specification/#schema-object) and not a standard JSON Schema. Consistent with JSON Schema, additionalProperties defaults to true.

https://swagger.io/specification/#schema-object

また必ずレスポンスに含まれるプロパティについては必須項目であることを表明したい

リンク先の例を参照のこと https://swagger.io/specification/#schema-object

**Comment by m-takay** [comment]
additionalProperties: falseとrequiredを付けておきました。

**Comment by knokmki612** [comment]
https://github.com/npocccties/chiloportal/commit/e7bbb779995d97ec2bd3c4d88e4d41b29e07f6de にて対応いただいた
