### ISSUE TITLE
ページネーションの挙動が正常でない

### ISSUE THREAD

**Issue by ties-makimura** [npocccties/chiloportal#847]
例えば，「学びを探す」ページからバッジ一覧を表示する際，ページネーションで3つ目（もしくは末尾？）をクリックすると，ページネーションのエリアに新しく番号が追加され，それが選択された状態になった。

**再現手順**　
（今回は,developブランチが動作している https://dev-portal.oku.cccties.org/ で確認）
1. ページネーションを出すため，backend/.envの PER_PAGE を調整する。10とか
2. 「学びを探す」ページに移動，すべてのバッジが選択された状態
3. ページネーションで3つ目をクリック
4. URLは https://dev-portal.oku.cccties.org/discover?by=all&p=3 だが，画像の通り，4つ目が選択された状態になっている。バッジの表示は3つ目のように見える
  ![image](https://github.com/npocccties/chiloportal/assets/8957521/d8cc1c00-6a2b-4739-89fa-1e09711d7272)

**その他**　
キーワード検索など他の所でも再現しているように見える。

**Comment by knokmki612** [comment]
- バックエンドのPER_PAGEにあたる値の管理がフロントエンドでも必要かも
- 再現するテストケースは把握しているので少なくともそのケースはパスする形で実装の見直しが必要

**Comment by knokmki612** [comment]
> ページあたり件数を開始地点と終了地点で算出し可変であることが原因
> ページあたり件数は環境変数 NEXT_PUBLIC_API_PER_PAGE に指定し、
> バックエンドの環境変数 PER_PAGE と揃えてください @ties-makimura

https://github.com/npocccties/chiloportal/issues/847 にて対応しました。上記変更ありますのでデプロイ時留意いただければと思います。

**Comment by knokmki612** [comment]
NEXT_PUBLIC_API_PER_PAGE 未指定時期待しない値（NaN）が使用される点については別途対応します。
