### ISSUE TITLE
グローバルメニューの検索キーワードにある文字削除アイコンが表示されない

### ISSUE THREAD

**Issue by ties-makimura** [npocccties/chiloportal#848]
Mac-Safari の時にだけ再現確認できる。
ただ，実体はあるようで，マウスカーソルあわせてクリックしたらSafariでも機能する。見えないだけ。

上がSafari，下がChrome
![image](https://github.com/npocccties/chiloportal/assets/8957521/4799d52f-616f-4a37-8499-85778c851823)

**Comment by knokmki612** [comment]
クリアボタンが表示されるかどうかは `<input type="search">` に対するブラウザの取扱いに依存します

**Comment by knokmki612** [comment]
> ただ，実体はあるようで，マウスカーソルあわせてクリックしたらSafariでも機能する。見えないだけ。

見えないというのはCSSによって指定した色とブラウザが使用している色のコントラストの問題かもしれないです

**Comment by knokmki612** [comment]
視認性や見た目の一貫性を重視して、検索をキャンセルするボタンは実体として表示しないようにしました。クローズします。
