### ISSUE TITLE
学びを探すの教員育成指標のステージが切り替わらない

### ISSUE THREAD

**Issue by ties-makimura** [npocccties/chiloportal#849]
develop環境

学びを探すの教員育成指標で，複数のステージがある場合，タブのリンク先が同じになってステージが切り替わらない

![image](https://github.com/npocccties/chiloportal/assets/8957521/8e131b61-24c1-4202-afc4-7a6d21a01e81)

APIからは，それぞれのidが正しく取得されている

```
GET /api/v1/framework/stage/list/?framework_id=7
HTTP 200 OK
Allow: GET, HEAD, OPTIONS
Content-Type: application/json
Vary: Accept

[
    {
        "stage_id": 2,
        "name": "大阪府教育委員会",
        "sub_name": "",
        "description": ""
    },
    {
        "stage_id": 9,
        "name": "大阪府教育委員会2",
        "sub_name": " ",
        "description": " "
    }
]
```

**Comment by knokmki612** [comment]
stage.stage_idを参照すべきところをprops.stage.stage_idを参照している点に起因しているようです

https://github.com/npocccties/chiloportal/blob/71af5bd230bc1b9cedcc5d978c589b5cb36a3376/frontend/templates/Discover.tsx#L155

**Comment by knokmki612** [comment]
以下のように解消しました。クローズします。

![image](https://github.com/npocccties/chiloportal/assets/9744580/4f8e2de0-e585-4760-b44b-70197a8df67f)
