### ISSUE TITLE
継続的デプロイの検討

### ISSUE THREAD

**Issue by knokmki612** [npocccties/chiloportal#9]
最新時点での状態、各プルリクエスト等による変更での状態を動作確認する際に有用

https://github.com/npocccties/chibichilo では

- [Vercel](https://vercel.com/)
- [Heroku](https://jp.heroku.com/)

を使用していた記憶

**Comment by knokmki612** [comment]
バックエンドについては作業済み #295

**Comment by knokmki612** [comment]
> > 動作確認は https://github.com/npocccties/chiloportal/tree/develop/frontend#%E3%83%AD%E3%83%BC%E3%82%AB%E3%83%AB%E7%92%B0%E5%A2%83 に記載のある、モックサーバーを無効化しバックエンドの開発サーバーを使用する手順で実施します
> 
> これだとインポートされた画像が参照できないので、バックエンドの開発サーバーが起動している環境でフロントエンドサーバーを起動させる必要があるように思う

_Originally posted by @knokmki612 in https://github.com/npocccties/chiloportal/issues/132#issuecomment-1291675364_

backend-cd.yml を拡張するような形で、（バックエンドサーバーでのインポート処理実行後）フロントエンドサーバーもDockerで起動するような変更をお願いできたりしますでしょうか？ @yoshinobu-etou-id 

実行する必要があるのは次のリンクにある内容です https://github.com/npocccties/chiloportal/tree/develop/frontend#docker-%E7%92%B0%E5%A2%83

ビルド時インポート画像を参照するのでVolume等は作成不要です

```shell
docker build -t frontend . # Docker イメージのビルド
docker run --rm -p 3000:3000 frontend # Docker コンテナの起動
```

**Comment by yoshinobu-etou-id** [comment]
確認してみます

**Comment by knokmki612** [comment]
ありがとうございます… :pray:

**Comment by yoshinobu-etou-id** [comment]
@knokmki612 
開発サーバーでビルドしようとしたら、以下のエラーが発生しました。
チェックサムの値が古いのでしょうか。
```
Step 5/23 : RUN echo "e6edd1972de261fdbd11bbfeb4c76dee  ../backend/doc/openapi.yaml" > md5sum.txt && md5sum -c md5sum.txt
 ---> Running in cf06694c144d
md5sum: WARNING: 1 computed checksum did NOT match
../backend/doc/openapi.yaml: FAILED
```

**Comment by yoshinobu-etou-id** [comment]
404を消した影響かもしれないですね。

**Comment by knokmki612** [comment]
openapi.yaml を GitHub から取得している都合上、md5ハッシュ値を検証するようにしてまして、最新の openapi.yaml のハッシュ値を Dockerfile に反映する必要がありそうです
オフトピックですが openapi.yaml がこの Dockerfile のビルドコンテキストに含まれないので GitHub から取得していますが、ローカルから取得できるに越したことはないという気もします

https://github.com/npocccties/chiloportal/blob/e5fa20e6741ffb4189c1e1932049a4d7a42b90e3/frontend/Dockerfile#L5

**Comment by knokmki612** [comment]
今対応しますのでお待ちください

**Comment by yoshinobu-etou-id** [comment]
一旦、開発サーバー上ではコメントアウトして動作を見ていますので、ぼちぼちで大丈夫です。

**Comment by knokmki612** [comment]
ありがとうございます、 https://github.com/npocccties/chiloportal/pull/350/commits/5022f1bcbd0ec6ac59871324537c032c57a9655e にて反映しました

**Comment by yoshinobu-etou-id** [comment]
@knokmki612 
とりあえず以下の場合に frontend:3000 に転送するようにしました。
https://dev-portal.oku.cccties.org/

**Comment by yoshinobu-etou-id** [comment]
インポートが可能な状況になってきたら、デプロイ時にインポート処理を行うようにする予定です。
