### ISSUE TITLE
バッジ画像の作成ガイドライン

### ISSUE THREAD

**Issue by Hidetaro7** [npocccties/chiloportal#91]
現在検討中のバッジの見た目は
能力バッジ... 丸くリボンが付いている
知識バッジ... 角丸四角形

であるが、そもそもこのデザインについて議論があまりされていないのでどこかでやる。

さらに運用において禁止ルールを設けたほうが作成しやすい場合もあるかもしれないので、ガイドラインを作成するほうがいいかも。

**Comment by knokmki612** [comment]
duplicate of #173
