### ISSUE TITLE
インポートされた画像の出力先を明確化する

### ISSUE THREAD

**Issue by knokmki612** [npocccties/chiloportal#93]
インポートされた画像の配置先はクライアント側アプリの静的アセットを取り扱うディレクトリが適切という話になったのでその配置先を明示して共有する必要がある

_Originally posted by @knokmki612 in https://github.com/npocccties/oku-private/issues/35#issuecomment-1247726137_

---

フロントエンドのドキュメンテーション、その他なにかしらリポジトリに反映できたら完了

**Comment by knokmki612** [comment]
> Next.js can serve static files, like images, under a folder called public in the root directory. Files inside public can then be referenced by your code starting from the base URL (/).

https://nextjs.org/docs/basic-features/static-file-serving

Next.js では public ディレクトリで静的ファイルがサーブされるので、インポートされた画像の出力先は少なくともpublicディレクトリ配下になるということではあると思った。
本リポジトリのディレクトリ構成としては `frontend/public` になる https://github.com/npocccties/chiloportal/tree/develop/frontend/public

インポートされた画像であるか識別したい&インポートされた画像については.gitignoreでリポジトリに管理しないようにしたいので、なにかしらのさらなるサブディレクトリかファイルの命名規則にしたがって画像が配置されるとうれしいと思った。

@yoshinobu-etou-id ここまででインポート実装にあたり疑問点ありますでしょうか？

また、ここでサブディレクトリ名あるいはファイルの命名規則が決められるとうれしいと思いました。

**Comment by yoshinobu-etou-id** [comment]
@knokmki612 
画像出力は物理パスに出力するので、Webサーバで公開される絶対パスを教えていただけますでしょうか？

Webサーバで公開される絶対パス例：
`/var/www/images`

サブディレクトリに出力する想定はございません。
ファイル命名規則ですが、能力バッジのjsonのimage.idのパスの部分のスラッシュをドットに変換し、
拡張子を付与したうえで、テーブルに格納しますので、APIから返された画像ファイル名を
フロントから参照可能な画像が格納されたパス（上記例でいうと images）に付与すれば画像参照できるかと思います。

ファイル名変換例：
https://opedu.lib.osaka-kyoiku.ac.jp/pluginfile.php/1/badges/badgeimage/41/f1
↓
`pluginfile.php.1.badges.badgeimage.41.f1.png`

フロントから参照する際のパス例：
`images/pluginfile.php.1.badges.badgeimage.41.f1.png`

**Comment by knokmki612** [comment]
> 画像出力は物理パスに出力するので、Webサーバで公開される絶対パスを教えていただけますでしょうか？
> 
> Webサーバで公開される絶対パス例：
> `/var/www/images`

現状絶対パスは不定という認識です。理由としてはフロントエンド側のアプリケーションのデプロイ先がVercelその他PaaSなのかそれともベアメタル環境なのかなど、とくに決まっていないためです。

> フロントから参照可能な画像が格納されたパス（上記例でいうと images）に付与すれば画像参照できるかと思います。

とくにこの点に関して異論ありません。

---

https://github.com/npocccties/oku-private/issues/35#issuecomment-1247726137 に基づいてこのissueを作成しましたが、

現状の方針から見直したほうがいいような気がしてきました

インポートされた画像（静的ファイル）をバックエンド側のサーバーで配信いただくか、別途そのためのサーバーを立てるかしたほうがいいような気がしてきました（Vercelなどのデプロイインスタンスごとにバックエンド側から画像（静的ファイル）の書き込みを受け付けてデプロイする方法がいまいち想像つかなかったため）

まだ確定ではないですが `next/future/image` をつかって画像表示することを検討しています。これは適切に設定すれば外部URLも受け付けられるようなので画像を外部のサーバーから取得表示することはフロントエンド側の実装としては可能と思っています。 https://nextjs.org/docs/api-reference/next/future/image#src

cc: @dynamis

**Comment by dynamis** [comment]
> 現状絶対パスは不定という認識です。

webroot を環境変数、そこから先を固定にするとかで良いのではないでしょうか。

先の例でいえば `/var/www` までは何処かの環境変数あたりで設定、 `/images` パス配下に出力するとか。いずれにしても後日変更もし易くさえしておけば仮に何処でも良いのでは無いかと。

**Comment by knokmki612** [comment]
> Vercelなどのデプロイインスタンスごとにバックエンド側から画像（静的ファイル）の書き込みを受け付けてデプロイする方法がいまいち想像つかなかったため

この点に関してはいかがでしょう？ @dynamis（なにか的はずれな疑問でしたらすみません）

**Comment by knokmki612** [comment]
> Vercelなどのデプロイインスタンスごとにバックエンド側から画像（静的ファイル）の書き込みを受け付けてデプロイする方法がいまいち想像つかなかったため

このケースは今の時点では想定しないことになった

**Comment by knokmki612** [comment]
> webroot を環境変数、そこから先を固定にするとかで良いのではないでしょうか。

https://github.com/npocccties/chiloportal/tree/develop/backend#%E7%92%B0%E5%A2%83%E5%A4%89%E6%95%B0%E3%81%AE%E8%AA%AC%E6%98%8E にあるとおりバックエンドとしては環境変数 `IMAGE_DIR` が存在しているので、

- [ ] フロントエンド側でインポート用のディレクトリを用意する
- [ ] [env.dev-server-debug](https://github.com/npocccties/chiloportal/blob/develop/backend/.env.dev-server-debug)のIMAGE_DIRを用意したディレクトリへの相対パスに変更する

という作業が必要かなと思いました
